import "dotenv/config";
import fs from "node:fs/promises";
import path from "node:path";
import mongoose from "mongoose";
import Bloque from "../models/Bloque";
import DetalleBloque from "../models/DetalleBloque";
import Fraterno from "../models/Fraterno";
import PerfilUsuario from "../models/PerfilUsuario";
import Rol from "../models/Rol";
import Cuota from "../models/Cuota";
import DetalleCuota from "../models/DetalleCuota";
import Preregistro from "../models/Preregistro";

const n=(v:any)=>Number((Number(v)||0).toFixed(2)), sid=(v:any)=>String(v?._id??v??"");
const tipo=(v:any)=>["INTERNO","INTERNO_UMSA"].includes(String(v??"").toUpperCase())?"INTERNO":["EXTERNO","EXTERNO_UMSA","EXTERNO_NO_UMSA"].includes(String(v??"").toUpperCase())?"EXTERNO":"SIN CLASIFICAR";
const suma=(xs:any[],k:string)=>n(xs.reduce((a,x)=>a+Number(x[k]||0),0));
function resumen(xs:any[],bloque:string){const i=xs.filter(x=>x.tipo==="INTERNO"),e=xs.filter(x=>x.tipo==="EXTERNO"),t=suma(xs,"montoEsperado");return{bloque,personas:xs.length,internos:i.length,externos:e.length,sinClasificar:xs.length-i.length-e.length,montoInternos:i.length*770,montoExternos:e.length*850,montoTeorico:t,exentos:0,montoExento:0,montoEsperadoRealProvisional:t,montoRegistrado:suma(xs,"montoRegistrado"),montoVerificado:suma(xs,"montoVerificado"),montoPendienteRevision:suma(xs,"montoPendienteRevision"),saldoPorCobrarProvisional:suma(xs,"saldo"),sinPago:xs.filter(x=>x.estadoPago==="SIN PAGO").length,pagoParcial:xs.filter(x=>x.estadoPago==="PAGO PARCIAL").length,pagoCompleto:xs.filter(x=>x.estadoPago==="PAGO COMPLETO").length,conPagoPendienteRevision:xs.filter(x=>x.pagosPendientes>0).length,conPagoVerificado:xs.filter(x=>x.pagosVerificados>0).length}}

async function main(){
 if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL no está configurada");await mongoose.connect(process.env.DATABASE_URL,{serverSelectionTimeoutMS:10000});
 const bs:any[]=await Bloque.find({estado:"ACTIVO"}).select("nombre").lean(), bm=new Map(bs.map(b=>[sid(b),b]));
 const as:any[]=await DetalleBloque.find({estado:"ACTIVO",fechaEliminado:null,bloqueId:{$in:bs.map(b=>b._id)}}).lean(), fids=[...new Set(as.map(a=>sid(a.fraternoId)))];
 const fsx:any[]=await Fraterno.find({_id:{$in:fids}}).lean(), fm=new Map(fsx.map(f=>[sid(f),f]));
 const us:any[]=await PerfilUsuario.find({_id:{$in:fsx.map(f=>f.usuarioId)}}).select("nombres apellidoPaterno apellidoMaterno ci telefono sexo tipoOrigen roles estado fechaEliminado").lean(),um=new Map(us.map(u=>[sid(u),u]));
 const rs:any[]=await Rol.find({_id:{$in:us.flatMap(u=>u.roles??[])}}).select("codigo nombre").lean(),rm=new Map(rs.map(r=>[sid(r),String(r.codigo||r.nombre)]));
 const cs:any[]=await Cuota.find({preregistroId:{$in:fsx.map(f=>f.preregistroId)},fechaEliminado:null}).lean(),cm=new Map(cs.map(c=>[sid(c.preregistroId),c]));
 const ps:any[]=await DetalleCuota.find({cuotaId:{$in:cs.map(c=>c._id)},fechaEliminado:null}).sort({fechaPago:1}).lean(),pm=new Map<string,any[]>();for(const p of ps)pm.set(sid(p.cuotaId),[...(pm.get(sid(p.cuotaId))??[]),p]);
 const ac=new Map<string,number>();for(const a of as)ac.set(sid(a.fraternoId),(ac.get(sid(a.fraternoId))??0)+1);
 const seen=new Set<string>(),personas:any[]=[];for(const a of as){const f:any=fm.get(sid(a.fraternoId));if(!f||seen.has(sid(f.usuarioId)))continue;seen.add(sid(f.usuarioId));const u:any=um.get(sid(f.usuarioId)),c:any=cm.get(sid(f.preregistroId)),p=c?(pm.get(sid(c))??[]):[],cl=c?.tipoOrigenTarifa??tipo(u?.tipoOrigen),esperado=cl==="INTERNO"?770:cl==="EXTERNO"?850:0,v=p.filter(x=>x.estadoRevision==="VERIFICADO"),q=p.filter(x=>x.estadoRevision==="PENDIENTE"),mv=n(v.reduce((s,x)=>s+x.monto,0)),saldo=n(Math.max(0,esperado-mv));personas.push({nombre:[u?.nombres,u?.apellidoPaterno,u?.apellidoMaterno].filter(Boolean).join(" "),ci:String(u?.ci??""),telefono:String(u?.telefono??""),whatsapp:u?.telefono?`+591${String(u.telefono).replace(/\D/g,"")}`:"",sexo:u?.sexo??"SIN REGISTRO",roles:(u?.roles??[]).map((r:any)=>rm.get(sid(r))??"ROL DESCONOCIDO").join(" / ")||"SIN ROLES",bloque:bm.get(sid(a.bloqueId))?.nombre??"BLOQUE NO ENCONTRADO",tipo:cl,datoClasificacion:c?.tipoOrigenTarifa?"Cuota.tipoOrigenTarifa":u?.tipoOrigen?"PerfilUsuario.tipoOrigen":"FALTA tipoOrigen y cuota",montoEsperado:esperado,exento:false,motivoExencion:"NO EXISTE CAMPO DE EXENCIÓN",montoRegistrado:n(p.reduce((s,x)=>s+x.monto,0)),montoVerificado:mv,montoPendienteRevision:n(q.reduce((s,x)=>s+x.monto,0)),saldo,estadoPago:mv>=esperado&&esperado>0?"PAGO COMPLETO":mv>0?"PAGO PARCIAL":"SIN PAGO",estadoCuota:c?.estado??"SIN CUOTA",montoTotalCuota:n(c?.montoTotal),montoPagadoCuota:n(c?.montoPagado),saldoCuota:c?n(c.saldo):null,cantidadPagos:p.length,pagosVerificados:v.length,pagosPendientes:q.length,ultimoPago:p.at(-1)?.fechaPago??null,estadoFraterno:f.estado,estadoUsuario:u?.estado??"USUARIO NO ENCONTRADO",asignacionesActivas:ac.get(sid(f))??0})}
 const inc:any[]=[];for(const p of personas){if(p.asignacionesActivas>1)inc.push({tipo:"DOBLE ASIGNACIÓN ACTIVA",nombre:p.nombre,ci:p.ci});if(p.tipo==="SIN CLASIFICAR")inc.push({tipo:"SIN CLASIFICACIÓN",nombre:p.nombre,ci:p.ci});if(p.estadoCuota==="SIN CUOTA")inc.push({tipo:"CON BLOQUE SIN CUOTA",nombre:p.nombre,ci:p.ci});if(p.montoVerificado>p.montoEsperado&&p.montoEsperado>0)inc.push({tipo:"PAGO MAYOR AL ESPERADO",nombre:p.nombre,ci:p.ci});if(p.estadoCuota==="PAGADA"&&p.saldoCuota>0)inc.push({tipo:"PAGADA CON SALDO",nombre:p.nombre,ci:p.ci});if(p.saldoCuota===0&&p.montoVerificado===0)inc.push({tipo:"SALDO 0 SIN VERIFICADOS",nombre:p.nombre,ci:p.ci});if(["INACTIVO","RETIRADO"].includes(p.estadoFraterno)||p.estadoUsuario==="INACTIVO")inc.push({tipo:"ASIGNACIÓN ACTIVA DE INACTIVO/RETIRADO",nombre:p.nombre,ci:p.ci});if(p.montoPagadoCuota!==p.montoVerificado)inc.push({tipo:"CUOTA.montoPagado DIFIERE DE VERIFICADOS",nombre:p.nombre,ci:p.ci,detalle:`${p.montoPagadoCuota}/${p.montoVerificado}`})}
 const pagosConDinero:any[]=await DetalleCuota.find({fechaEliminado:null,estadoRevision:{$in:["VERIFICADO","PENDIENTE"]}}).lean(),cuotaGlobalIds=[...new Set(pagosConDinero.map(p=>sid(p.cuotaId)))],cuotasGlobal:any[]=await Cuota.find({_id:{$in:cuotaGlobalIds},fechaEliminado:null}).lean(),cg=new Map(cuotasGlobal.map(c=>[sid(c),c])),preGlobal:any[]=await Preregistro.find({_id:{$in:cuotasGlobal.map(c=>c.preregistroId)}}).lean(),pg=new Map(preGlobal.map(p=>[sid(p),p])),frGlobal:any[]=await Fraterno.find({preregistroId:{$in:preGlobal.map(p=>p._id)},fechaEliminado:null}).lean(),fg=new Map(frGlobal.map(f=>[sid(f.preregistroId),f])),asignados=new Set(as.map(a=>sid(a.fraternoId))),userGlobal:any[]=await PerfilUsuario.find({_id:{$in:preGlobal.map(p=>p.usuarioId)}}).select("nombres apellidoPaterno apellidoMaterno ci telefono tipoOrigen roles estado").lean(),ug=new Map(userGlobal.map(u=>[sid(u),u]));
 const historial=new Map<string,any[]>();for(const p of pagosConDinero)historial.set(sid(p.cuotaId),[...(historial.get(sid(p.cuotaId))??[]),p]);const pagaronNoParticipan:any[]=[],requierenRevision:any[]=[];for(const c of cuotasGlobal){const pre:any=pg.get(sid(c.preregistroId)),f:any=fg.get(sid(c.preregistroId)),u:any=ug.get(sid(pre?.usuarioId));if(!pre||!u)continue;const hp=historial.get(sid(c))??[],ver=n(hp.filter(x=>x.estadoRevision==="VERIFICADO").reduce((s,x)=>s+x.monto,0)),pend=n(hp.filter(x=>x.estadoRevision==="PENDIENTE").reduce((s,x)=>s+x.monto,0));if(ver<=0&&pend<=0)continue;const fila={nombre:[u.nombres,u.apellidoPaterno,u.apellidoMaterno].filter(Boolean).join(" "),ci:u.ci??"",telefono:u.telefono??"",roles:(u.roles??[]).map((r:any)=>rm.get(sid(r))??"ROL DESCONOCIDO").join(" / ")||"SIN ROLES",tipo:c.tipoOrigenTarifa??tipo(u.tipoOrigen),montoRegistrado:n(hp.reduce((s,x)=>s+x.monto,0)),montoVerificado:ver,montoPendienteRevision:pend,cantidadPagos:hp.length,fechaUltimoPago:hp.sort((a,b)=>+new Date(a.fechaPago)-+new Date(b.fechaPago)).at(-1)?.fechaPago??null,estadoFraterno:f?.estado??"SIN FRATERNO",estadoUsuario:u.estado??"SIN ESTADO",bloqueActivo:Boolean(f&&asignados.has(sid(f)))};if(["INACTIVO","RETIRADO"].includes(fila.estadoFraterno)||fila.estadoUsuario==="INACTIVO")pagaronNoParticipan.push(fila);else if(!fila.bloqueActivo)requierenRevision.push(fila)}
 const bloques=[...new Set(personas.map(p=>p.bloque))].sort().map(b=>resumen(personas.filter(p=>p.bloque===b),b));const out={generadoEn:new Date().toISOString(),soloLectura:true,reglaClasificacion:"Cuota.tipoOrigenTarifa; fallback explícito PerfilUsuario.tipoOrigen",exenciones:{determinables:false,totalConfirmado:0,advertencia:"No existe campo/modelo de exención; no se asumió por rol."},resumen:resumen(personas,"GENERAL"),porBloque:bloques,pagaronPeroYaNoParticipan:pagaronNoParticipan,pagosQueRequierenRevisionParticipacion:requierenRevision,personas,inconsistencias:inc};const destino=process.env.AUDITORIA_FINANCIERA_SALIDA||path.resolve(process.cwd(),"..","AUDITORIA_FINANCIERA_BLOQUES_PRODUCCION.json");await fs.writeFile(destino,JSON.stringify(out,null,2)+"\n","utf8");console.log(JSON.stringify({destino,resumen:out.resumen,bloques,pagaronPeroYaNoParticipan:pagaronNoParticipan.length,pagosQueRequierenRevisionParticipacion:requierenRevision.length,inconsistencias:inc.length},null,2));await mongoose.disconnect();
}
main().catch(async e=>{console.error(e);await mongoose.disconnect();process.exitCode=1});
