import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { toast } from "react-toastify";
import { cambiarEstadoEvento, crearEvento, listarEventos, registrarAsistenciaEvento, type Evento } from "@/api/EventoApi";
import { buscarIdentidades, type ResultadoBusquedaIdentidad } from "@/api/CredencialQrApi";

const TIPOS=["ELECCION_CHACHA_WARMI","FIESTA_PREENTRADA","PREENTRADA","ENTRADA_UNIVERSITARIA","REUNION","OTRO"];
export default function EventosView(){
 const qc=useQueryClient(),q=useQuery({queryKey:["eventos"],queryFn:listarEventos});
 const [form,setForm]=useState({nombre:"",tipo:"REUNION",fecha:"",horaInicio:"",horaFin:"",descripcion:""});
 const accion=useMutation({mutationFn:(fn:()=>Promise<any>)=>fn(),onSuccess:async(r)=>{toast.success(r.message);setForm({nombre:"",tipo:"REUNION",fecha:"",horaInicio:"",horaFin:"",descripcion:""});await qc.invalidateQueries({queryKey:["eventos"]})},onError:(e:any)=>toast.error(e.response?.data?.error??"No se pudo completar la operación")});
 return <main className="space-y-5"><header><p className="text-xs font-black uppercase tracking-widest text-[#8F5F2A]">Administración</p><h1 className="text-3xl font-black text-[#841534]">Eventos y asistencias especiales</h1><p className="text-slate-500">Cada persona puede asistir a varios eventos el mismo día sin afectar la asistencia general.</p></header>
 <form onSubmit={e=>{e.preventDefault();accion.mutate(()=>crearEvento(form))}} className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-2 xl:grid-cols-6"><input required value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})} placeholder="Nombre del evento" className="rounded-xl border p-3 xl:col-span-2"/><select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})} className="rounded-xl border p-3">{TIPOS.map(t=><option key={t}>{t}</option>)}</select><input required type="date" value={form.fecha} onChange={e=>setForm({...form,fecha:e.target.value})} className="rounded-xl border p-3"/><input type="time" value={form.horaInicio} onChange={e=>setForm({...form,horaInicio:e.target.value})} className="rounded-xl border p-3"/><button disabled={accion.isPending} className="rounded-xl bg-[#841534] p-3 font-black text-white">Crear evento</button></form>
 <section className="grid gap-4 lg:grid-cols-2">{q.data?.eventos.map(ev=><EventoCard key={ev._id} evento={ev} cambiar={(estado)=>accion.mutate(()=>cambiarEstadoEvento(ev._id,estado))}/>)}</section>{q.isLoading&&<p>Cargando eventos...</p>}{!q.isLoading&&!q.data?.eventos.length&&<p className="rounded-xl bg-white p-8 text-center text-slate-500">No existen eventos registrados.</p>}</main>
}
function EventoCard({evento,cambiar}:{evento:Evento;cambiar:(e:Evento["estado"])=>void}){
 const qc=useQueryClient(),[texto,setTexto]=useState(""),[resultados,setResultados]=useState<ResultadoBusquedaIdentidad[]>([]),[ocupado,setOcupado]=useState(false);
 const buscar=async()=>{if(texto.trim().length<2)return;setOcupado(true);try{setResultados((await buscarIdentidades(texto)).resultados)}catch(e:any){toast.error(e.message)}finally{setOcupado(false)}};
 const registrar=async(usuario:ResultadoBusquedaIdentidad)=>{setOcupado(true);try{const r=await registrarAsistenciaEvento(evento._id,usuario._id,"MANUAL");toast.success(r.message);setResultados([]);setTexto("");await qc.invalidateQueries({queryKey:["eventos"]})}catch(e:any){toast.error(e.response?.data?.error??e.message)}finally{setOcupado(false)}};
 return <article className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><div><h2 className="text-xl font-black text-[#841534]">{evento.nombre}</h2><p className="text-sm text-slate-500">{evento.tipo.replaceAll("_"," ")} · {new Date(evento.fecha).toLocaleDateString("es-BO")}</p></div><span className="h-fit rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{evento.estado}</span></div><p className="mt-4 text-3xl font-black">{evento.presentes}</p><p className="text-xs text-slate-500">asistencias registradas</p><div className="mt-4 flex gap-2">{evento.estado!=="ACTIVO"&&evento.estado!=="CANCELADO"?<button onClick={()=>cambiar("ACTIVO")} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white">Abrir registro</button>:null}{evento.estado!=="CERRADO"&&evento.estado!=="CANCELADO"?<button onClick={()=>confirm("¿Cerrar este evento?")&&cambiar("CERRADO")} className="rounded-lg bg-slate-700 px-3 py-2 text-xs font-bold text-white">Cerrar</button>:null}</div>
 {evento.estado==="ACTIVO"?<div className="mt-4 border-t pt-4"><label className="text-xs font-black uppercase text-slate-600">Registrar por nombre o CI</label><div className="mt-2 flex gap-2"><input value={texto} onChange={e=>setTexto(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void buscar()} className="min-w-0 flex-1 rounded-xl border p-2" placeholder="Nombre o CI"/><button disabled={ocupado} onClick={()=>void buscar()} className="rounded-xl bg-[#841534] px-4 font-bold text-white">Buscar</button></div>{resultados.map(u=><button key={u._id} disabled={ocupado} onClick={()=>void registrar(u)} className="mt-2 block w-full rounded-xl bg-slate-50 p-3 text-left hover:bg-emerald-50"><b>{u.nombres} {u.apellidoPaterno} {u.apellidoMaterno}</b><small className="block">CI {u.ci} · Registrar asistencia</small></button>)}</div>:null}
 </article>}
