import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { actualizarPreregistro, crearPreregistro } from "@/api/PreregistroApi";
import { ESTADOS_PREREGISTRO, type EstadoPreregistro } from "@/types/PreregistroType";

type Props={usuarioId:string;nombre:string;telefono?:string|null;cerrar:()=>void;completado?:(estado:EstadoPreregistro)=>void};
export default function AsignarEstadoPreregistroModal({usuarioId,nombre,telefono,cerrar,completado}:Props){
 const qc=useQueryClient(),[estado,setEstado]=useState<EstadoPreregistro>("APROBADO"),[observacion,setObservacion]=useState(""),[resultado,setResultado]=useState<{tipo:"ok"|"error";mensaje:string;estado?:EstadoPreregistro}|null>(null);
 const digitos=String(telefono??"").replace(/\D/g,""),numeroWhatsApp=digitos.startsWith("591")?digitos:digitos.length===8?`591${digitos}`:digitos;
 const abrirWhatsApp=()=>{if(!numeroWhatsApp||!observacion.trim())return;const mensaje=[`Hola ${nombre},`,"Tu registro en el sistema Tinkus fue observado por administración.",`Observación: ${observacion.trim()}`,"Por favor, corrige tus datos o documentos para continuar con el proceso."].join("\n\n");window.open(`https://wa.me/${numeroWhatsApp}?text=${encodeURIComponent(mensaje)}`,"_blank","noopener,noreferrer")};
 const finalizar=()=>{if(resultado?.tipo==="ok"&&resultado.estado)completado?.(resultado.estado);cerrar()};
 const guardar=useMutation({mutationFn:async()=>{if(["OBSERVADO","RECHAZADO","LISTA_ESPERA","CANCELADO"].includes(estado)&&!observacion.trim())throw new Error("Debe escribir una observación o el motivo de la decisión");const pre=await crearPreregistro({usuarioId});return actualizarPreregistro({id:pre._id,datos:{estado,observacion:observacion.trim()}})},onSuccess:async()=>{setResultado({tipo:"ok",estado,mensaje:`El preregistro fue asignado como ${estado.replace("_"," ")}.`});await Promise.all([qc.invalidateQueries({queryKey:["preregistros"]}),qc.invalidateQueries({queryKey:["mis-preregistros"]})])},onError:(e:Error)=>setResultado({tipo:"error",mensaje:e.message})});
 return <div className="fixed inset-0 z-[130] grid place-items-center overflow-y-auto bg-[#21181b]/70 p-3 sm:p-4" role="dialog" aria-modal="true" aria-labelledby="estado-preregistro-titulo"><section className="my-4 w-full max-w-xl overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex items-center justify-between bg-gradient-to-r from-[#841534] to-[#C59A3A] p-5 text-white"><div><p className="text-xs uppercase tracking-[.18em]">Perfil activado</p><h2 id="estado-preregistro-titulo" className="text-xl font-black">Asignar estado del preregistro</h2></div><button type="button" onClick={resultado?.tipo==="ok"?finalizar:cerrar} className="grid h-10 w-10 place-items-center rounded-full bg-white/15 text-2xl" aria-label="Cerrar">×</button></header><div className="space-y-5 p-5 sm:p-6"><p className="text-sm text-slate-600">Define el siguiente paso de <strong>{nombre}</strong>. La cuenta ya puede ingresar; esta decisión controla su proceso de admisión.</p>{resultado&&<div className={`rounded-xl p-4 text-sm font-semibold ${resultado.tipo==="ok"?"bg-emerald-50 text-emerald-800":"bg-red-50 text-red-700"}`}>{resultado.mensaje}</div>}<div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{ESTADOS_PREREGISTRO.map(opcion=><button type="button" key={opcion} onClick={()=>setEstado(opcion)} className={`rounded-xl border px-3 py-3 text-xs font-bold ${estado===opcion?"border-[#841534] bg-[#841534] text-white":"border-[#d8cbbb] bg-[#faf7f1] text-[#5d4a42]"}`}>{opcion.replace("_"," ")}</button>)}</div><textarea value={observacion} onChange={e=>setObservacion(e.target.value)} maxLength={1000} className="input-preregistro min-h-28 w-full" placeholder={["OBSERVADO","RECHAZADO","LISTA_ESPERA","CANCELADO"].includes(estado)?"Motivo obligatorio. Ej.: el CI no coincide con el documento...":"Observación opcional para el postulante..."}/>{resultado?.tipo==="ok"&&resultado.estado==="OBSERVADO"&&(numeroWhatsApp?<button type="button" onClick={abrirWhatsApp} className="w-full rounded-xl bg-[#25D366] px-5 py-3 font-black text-white">Enviar observación por WhatsApp · {telefono}</button>:<p className="rounded-xl bg-amber-50 p-4 text-sm font-semibold text-amber-800">El usuario no tiene un teléfono registrado.</p>)}<div className="flex flex-col-reverse justify-end gap-3 sm:flex-row">{resultado?.tipo==="ok"?<button type="button" onClick={finalizar} className="rounded-xl border px-5 py-3 font-bold">Continuar</button>:<><button type="button" onClick={cerrar} className="rounded-xl border px-5 py-3 font-bold">Cancelar</button><button type="button" disabled={guardar.isPending} onClick={()=>guardar.mutate()} className="rounded-xl bg-[#841534] px-5 py-3 font-bold text-white disabled:opacity-50">{guardar.isPending?"Guardando...":"Guardar decisión"}</button></>}</div></div></section></div>;
}
