import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { obtenerReporteFacultades } from "@/api/FacultadApi";
import UsuarioMiniatura from "@/components/UsuarioMiniatura";

export default function FacultadesView() {
  const [facultad, setFacultad] = useState("TODAS"); const [buscar, setBuscar] = useState("");
  const consulta = useQuery({ queryKey: ["reporte-facultades"], queryFn: obtenerReporteFacultades });
  const integrantes = useMemo(() => (consulta.data?.integrantes ?? []).filter((p) => (facultad === "TODAS" || p.facultadNormalizada === facultad) && `${p.nombres} ${p.apellidoPaterno} ${p.apellidoMaterno ?? ""} ${p.ci} ${p.carrera ?? ""} ${p.registroUniversitario ?? ""}`.toLowerCase().includes(buscar.toLowerCase())), [consulta.data, facultad, buscar]);
  return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[.2em] text-[#8F5F2A]">Información institucional</p><h1 className="text-3xl font-black text-[#74122A]">Integrantes por facultad</h1><p className="text-sm text-[#735f55]">Resumen y listado de integrantes agrupando las distintas formas de escribir cada facultad.</p></header>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><button onClick={()=>setFacultad("TODAS")} className={`rounded-2xl border p-5 text-left ${facultad==="TODAS"?"bg-[#841534] text-white":"bg-white"}`}><p className="text-sm">Total de integrantes</p><strong className="text-3xl">{consulta.data?.total ?? 0}</strong></button>{consulta.data?.facultades.map(f=><button key={f.facultad} onClick={()=>setFacultad(f.facultad)} className={`rounded-2xl border p-5 text-left ${facultad===f.facultad?"bg-[#841534] text-white":"bg-white"}`}><p className="line-clamp-2 text-sm font-bold">{f.facultad}</p><strong className="text-3xl">{f.total}</strong></button>)}</section>
  <section className="grid gap-3 rounded-2xl bg-white p-4 md:grid-cols-[1fr_320px]"><input type="search" className="input-preregistro" placeholder="Buscar nombre, CI, RU o carrera..." value={buscar} onChange={e=>setBuscar(e.target.value)}/><select className="input-preregistro" value={facultad} onChange={e=>setFacultad(e.target.value)}><option value="TODAS">Todas las facultades</option>{consulta.data?.facultades.map(f=><option key={f.facultad} value={f.facultad}>{f.facultad} ({f.total})</option>)}</select></section>
  <section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-[#841534] text-white"><tr>{["Integrante","CI","RU","Facultad","Carrera","Origen","Estado"].map(t=><th key={t} className="p-4 text-left">{t}</th>)}</tr></thead><tbody>{integrantes.map(p=><tr key={p._id} className="border-b"><td className="p-4"><div className="flex items-center gap-3"><UsuarioMiniatura usuario={p}/><div><strong>{p.nombres} {p.apellidoPaterno} {p.apellidoMaterno}</strong><p className="text-xs text-slate-500">{p.email}</p></div></div></td><td className="p-4">{p.ci}</td><td className="p-4">{p.registroUniversitario || "—"}</td><td className="p-4"><strong>{p.facultadNormalizada}</strong>{p.facultadOriginal && p.facultadOriginal.toUpperCase()!==p.facultadNormalizada && <p className="text-xs text-slate-400">Registrado: {p.facultadOriginal}</p>}</td><td className="p-4">{p.carrera || "—"}</td><td className="p-4">{p.tipoOrigen.replaceAll("_"," ")}</td><td className="p-4"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{p.estado}</span></td></tr>)}</tbody></table>{!consulta.isLoading&&!integrantes.length&&<p className="p-10 text-center text-slate-500">No se encontraron integrantes.</p>}</section></div>;
}
