import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { toast } from "react-toastify";
import { agregarFraternoExistente, obtenerPendientesBloque, type PendienteBloque } from "@/api/BloqueGuiaApi";

export default function PendientesBloquePanel(){
 const qc=useQueryClient(),q=useQuery({queryKey:["pendientes-bloque"],queryFn:obtenerPendientesBloque});
 const [abierto,setAbierto]=useState(false),[filtro,setFiltro]=useState("TODOS"),[buscar,setBuscar]=useState("");
 const asignar=useMutation({mutationFn:({bloqueId,fraternoId}:{bloqueId:string;fraternoId:string})=>agregarFraternoExistente(bloqueId,fraternoId),onSuccess:async()=>{toast.success("Persona asignada al bloque");await Promise.all([qc.invalidateQueries({queryKey:["pendientes-bloque"]}),qc.invalidateQueries({queryKey:["guias-bloques"]})])},onError:(e:any)=>toast.error(e.response?.data?.error??"No se pudo asignar")});
 const personas=useMemo(()=>(q.data?.personas??[]).filter(p=>(filtro==="TODOS"||p.estado===filtro||p.sexo===filtro)&&(!buscar||`${p.nombre} ${p.ci} ${p.facultad??""}`.toLowerCase().includes(buscar.toLowerCase()))),[q.data,filtro,buscar]);
 const exportar=async()=>{const{default:ExcelJS}=await import("exceljs");const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet("Pendientes de bloque");ws.addRow(["Nombre","CI","Sexo","Teléfono","Facultad","Condición","Primera cuota","Fecha","Polera","Chamarra","Resultado"]);personas.forEach(p=>ws.addRow([p.nombre,p.ci,p.sexo,p.telefono,p.facultad,p.condicion,p.primeraCuota,p.fechaPrimeraCuota?new Date(p.fechaPrimeraCuota):"",p.tallaPolera,p.tallaChamarra,p.estado]));ws.getRow(1).font={bold:true};const data=await wb.xlsx.writeBuffer(),url=URL.createObjectURL(new Blob([data]));const a=document.createElement("a");a.href=url;a.download="pendientes-asignacion-bloques.xlsx";a.click();URL.revokeObjectURL(url)};
 const listos=(q.data?.personas??[]).filter(p=>p.listo).length;
 return <section className="rounded-2xl border bg-white shadow-sm"><button onClick={()=>setAbierto(v=>!v)} className="flex w-full items-center justify-between gap-4 p-5 text-left"><div><h2 className="text-xl font-black text-[#841534]">Pendientes de asignación</h2><p className="text-sm text-slate-500">{listos} listos · {(q.data?.personas??[]).length} personas sin bloque</p></div><span className="font-black text-[#841534]">{abierto?"Ocultar −":"Ver lista +"}</span></button>{abierto&&<div className="border-t p-5"><div className="flex flex-wrap gap-2"><input value={buscar} onChange={e=>setBuscar(e.target.value)} placeholder="Buscar nombre, CI o facultad" className="min-w-64 flex-1 rounded-xl border p-3"/><select value={filtro} onChange={e=>setFiltro(e.target.value)} className="rounded-xl border p-3"><option value="TODOS">Todos</option><option value="LISTO_PARA_ASIGNAR">Listos para asignar</option><option value="FALTA_TALLA">Falta talla</option><option value="FALTA_PRIMERA_CUOTA">Falta primera cuota</option><option value="HOMBRE">Hombres</option><option value="MUJER">Mujeres</option></select><button onClick={()=>void exportar()} className="rounded-xl bg-emerald-700 px-4 py-2 font-bold text-white">Exportar Excel</button></div><div className="mt-4 overflow-x-auto"><table className="min-w-[1100px] w-full text-xs"><thead><tr className="bg-[#841534] text-white">{["Persona","CI / Teléfono","Sexo","Condición","Primera cuota","Tallas","Resultado","Asignar"].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{personas.map(p=><Fila key={p.fraternoId} persona={p} bloques={(q.data?.bloques??[]).filter(b=>Boolean(p.sexo)&&b.capacidad[p.sexo!]>0)} asignar={(bloqueId)=>confirm(`¿Asignar a ${q.data?.bloques.find(b=>b._id===bloqueId)?.nombre}?`)&&asignar.mutate({bloqueId,fraternoId:p.fraternoId})}/>)}</tbody></table></div>{q.isLoading&&<p className="p-5">Calculando condiciones...</p>}{!q.isLoading&&!personas.length&&<p className="p-5 text-center text-slate-500">No existen registros para este filtro.</p>}</div>}</section>;
}
function Fila({persona:p,bloques,asignar}:{persona:PendienteBloque;bloques:any[];asignar:(id:string)=>void}){return <tr className="border-b"><td className="p-3 font-bold">{p.nombre}<small className="block text-slate-500">{p.facultad||"Sin facultad"}</small></td><td className="p-3">{p.ci}<small className="block">{p.telefono}</small></td><td className="p-3">{p.sexo}</td><td className="p-3">{p.condicion}</td><td className="p-3">{p.primeraCuota}<small className="block">{p.fechaPrimeraCuota?new Date(p.fechaPrimeraCuota).toLocaleDateString("es-BO"):"—"}</small></td><td className="p-3">Polera: {p.tallaPolera||"—"}<br/>Chamarra: {p.tallaChamarra||"—"}</td><td className="p-3 font-bold">{p.estado.replaceAll("_"," ")}</td><td className="p-3">{p.listo?<select defaultValue="" onChange={e=>e.target.value&&asignar(e.target.value)} className="rounded-lg border p-2"><option value="">Elegir bloque</option>{bloques.map(b=><option key={b._id} value={b._id}>{b.nombre} ({b.capacidad[p.sexo!]})</option>)}</select>:<span className="text-slate-400">No habilitado</span>}</td></tr>}
