import api from "@/lib/axios";
import { obtenerMensajeError } from "./apiError";
import type { Cuota, DetalleCuota, EstadoRevisionPago, MetodoPago } from "@/types/CuotaType";
const manejar = (e: unknown, m: string): never => { throw new Error(obtenerMensajeError(e, m)); };
export async function listarCuotas(): Promise<Cuota[]> { try { return (await api.get("/cuotas")).data.cuotas; } catch (e) { return manejar(e, "No se pudieron cargar las cuotas"); } }
export async function habilitarCuotasMasivas(datos: { tarifaInterno: number; tarifaExterno: number; fechaVencimiento?: string }): Promise<{ message: string; creadas: number; yaExistentes: number; totalEvaluados: number }> { try { return (await api.post("/cuotas/habilitar-masivo", datos)).data; } catch (e) { return manejar(e, "No se pudieron habilitar las cuotas masivamente"); } }
export async function crearCuota(datos: { preregistroId: string; montoTotal: number; fechaVencimiento?: string; observacion?: string }): Promise<Cuota> { try { return (await api.post("/cuotas", datos)).data.cuota; } catch (e) { return manejar(e, "No se pudo crear la cuota"); } }
export async function obtenerCuota(id: string): Promise<{ cuota: Cuota; pagos: DetalleCuota[] }> { try { return (await api.get(`/cuotas/${id}`)).data; } catch (e) { return manejar(e, "No se pudo cargar el detalle de cuota"); } }
export async function obtenerMiCuota(): Promise<{ cuota: Cuota; pagos: DetalleCuota[]; listaEspera?: boolean; prorrogaActiva?: boolean; pagoSiguienteVencido?: boolean; plazoVencido?: boolean; pagoHabilitado?: boolean; numeroPagoActual?: number }> { try { return (await api.get("/cuotas/mia")).data; } catch (e) { return manejar(e, "No se pudo cargar tu cuota"); } }
export async function elegirPlanCuotas(cuotaId: string, numeroCuotas: 1 | 2 | 3): Promise<Cuota> { try { return (await api.patch(`/cuotas/${cuotaId}/plan`, { numeroCuotas })).data.cuota; } catch (e) { return manejar(e, "No se pudo guardar el plan de cuotas"); } }
export async function editarPlanCuotasAdmin(cuotaId: string, numeroCuotas: 1 | 2 | 3): Promise<Cuota> { try { return (await api.patch(`/cuotas/${cuotaId}/plan/admin`, { numeroCuotas })).data.cuota; } catch (e) { return manejar(e, "No se pudo editar el plan de cuotas"); } }
export async function solicitarQrPago(cuotaId: string, numeroCuotas: 1 | 2 | 3, numeroPago: number): Promise<{ message: string }> { try { return (await api.post(`/cuotas/${cuotaId}/solicitar-qr`, { numeroCuotas, numeroPago })).data; } catch (e) { return manejar(e, "No se pudo notificar a administración"); } }
export async function prorrogarPrimeraCuota(cuotaId: string, datos: { horas: number; motivo: string }): Promise<{ message: string; cuota: Cuota }> { try { return (await api.patch(`/cuotas/${cuotaId}/prorroga-primera-cuota`, datos)).data; } catch (e) { return manejar(e, "No se pudo habilitar el nuevo plazo"); } }
export async function solicitarProrrogaPago(cuotaId: string): Promise<{ message: string }> { try { return (await api.post(`/cuotas/${cuotaId}/solicitar-prorroga`)).data; } catch (e) { return manejar(e, "No se pudo solicitar un nuevo plazo"); } }
export async function prorrogarCuotasVencidas(datos: { horas: number; motivo: string }): Promise<{ message: string; actualizadas: number }> { try { return (await api.patch("/cuotas/prorroga/vencidas", datos)).data; } catch (e) { return manejar(e, "No se pudo ampliar el plazo general"); } }
export async function registrarPago(cuotaId: string, datos: { monto: number; metodoPago: MetodoPago; montoEfectivo?: number; montoQr?: number; nombrePagador: string; fechaPago: string; baucher?: File | null }): Promise<DetalleCuota> { const form = new FormData(); form.append("monto", String(datos.monto)); form.append("metodoPago", datos.metodoPago); form.append("montoEfectivo", String(datos.montoEfectivo ?? 0)); form.append("montoQr", String(datos.montoQr ?? 0)); form.append("nombrePagador", datos.nombrePagador); form.append("fechaPago", datos.fechaPago); if (datos.baucher) form.append("baucher", datos.baucher); try { return (await api.post(`/cuotas/${cuotaId}/pagos`, form)).data.pago; } catch (e) { return manejar(e, "No se pudo registrar el pago"); } }
export async function revisarPago(cuotaId: string, pagoId: string, datos: { estadoRevision: EstadoRevisionPago; observacionRevision?: string; respaldoAdmin?: File | null }): Promise<DetalleCuota> { const form = new FormData(); form.append("estadoRevision", datos.estadoRevision); if (datos.observacionRevision) form.append("observacionRevision", datos.observacionRevision); if (datos.respaldoAdmin) form.append("respaldoAdmin", datos.respaldoAdmin); try { return (await api.patch(`/cuotas/${cuotaId}/pagos/${pagoId}/revision`, form)).data.pago; } catch (e) { return manejar(e, "No se pudo revisar el pago"); } }
export async function eliminarPago(cuotaId: string, pagoId: string) { try { return (await api.delete(`/cuotas/${cuotaId}/pagos/${pagoId}`)).data; } catch (e) { return manejar(e, "No se pudo eliminar el pago"); } }
