import api from "@/lib/axios";
import { obtenerMensajeError } from "./apiError";
import type { Anuncio, EventoAuditoria, MeritoGuia, Notificacion, PostulanteGuia } from "@/types/GuiaType";
const manejar = (e: unknown, m: string): never => { throw new Error(obtenerMensajeError(e, m)); };
export async function listarGuias(): Promise<PostulanteGuia[]> { try { return (await api.get("/postulantes-guia")).data.postulantes; } catch (e) { return manejar(e, "No se pudieron cargar los postulantes a guía"); } }
export async function habilitarGuia(preregistroId: string): Promise<PostulanteGuia> { try { return (await api.post("/postulantes-guia", { preregistroId })).data.postulante; } catch (e) { return manejar(e, "No se pudo habilitar al postulante"); } }
export async function habilitarGuiaPorUsuario(usuarioId: string): Promise<PostulanteGuia> { try { return (await api.post(`/postulantes-guia/por-usuario/${usuarioId}`)).data.postulante; } catch (e) { return manejar(e, "No se pudo nombrar al postulante a guía"); } }
export async function decidirPostulanteGuia(id: string, decision: "GUIA" | "FRATERNO") { try { return (await api.post(`/guias/postulantes/${id}/decision`, { decision })).data as { message: string }; } catch (e) { return manejar(e, "No se pudo registrar la decisión"); } }
export async function retirarPostulanteGuia(id: string) { try { return (await api.delete(`/postulantes-guia/${id}`)).data as { message: string }; } catch (e) { return manejar(e, "No se pudo retirar al postulante"); } }
export async function detalleGuia(id: string): Promise<{ postulante: PostulanteGuia; meritos: MeritoGuia[] }> { try { return (await api.get(`/postulantes-guia/${id}`)).data; } catch (e) { return manejar(e, "No se pudo cargar el detalle"); } }
export async function actualizarGuia(id: string, datos: Partial<PostulanteGuia>): Promise<PostulanteGuia> { try { return (await api.put(`/postulantes-guia/${id}`, datos)).data.postulante; } catch (e) { return manejar(e, "No se pudo evaluar al postulante"); } }
export async function agregarMerito(id: string, datos: { titulo: string; descripcion?: string; tipo: string; puntos: number }): Promise<MeritoGuia> { try { return (await api.post(`/postulantes-guia/${id}/meritos`, datos)).data.merito; } catch (e) { return manejar(e, "No se pudo registrar el mérito"); } }
export async function quitarMerito(id: string, meritoId: string) { try { return (await api.delete(`/postulantes-guia/${id}/meritos/${meritoId}`)).data; } catch (e) { return manejar(e, "No se pudo eliminar el mérito"); } }
export async function listarAnuncios(): Promise<Anuncio[]> { try { return (await api.get("/comunicacion/anuncios")).data.anuncios; } catch (e) { return manejar(e, "No se pudieron cargar los anuncios"); } }
export async function crearAnuncio(datos: Omit<Anuncio, "_id" | "fechaCreado"> & { aficheArchivo?: File | null }): Promise<Anuncio> { try { const formulario = new FormData(); Object.entries(datos).forEach(([clave, valor]) => { if (clave === "aficheArchivo" && valor instanceof File) formulario.append("afiche", valor); else if (valor !== undefined && valor !== null) formulario.append(clave, String(valor)); }); return (await api.post("/comunicacion/anuncios", formulario)).data.anuncio; } catch (e) { return manejar(e, "No se pudo crear el anuncio"); } }
export async function editarAnuncio(id: string, datos: Partial<Anuncio>): Promise<Anuncio> { try { return (await api.put(`/comunicacion/anuncios/${id}`, datos)).data.anuncio; } catch (e) { return manejar(e, "No se pudo editar el anuncio"); } }
export async function borrarAnuncio(id: string) { try { return (await api.delete(`/comunicacion/anuncios/${id}`)).data; } catch (e) { return manejar(e, "No se pudo eliminar el anuncio"); } }
export async function misNotificaciones(): Promise<{ notificaciones: Notificacion[]; noLeidas: number }> { try { return (await api.get("/comunicacion/notificaciones/mias")).data; } catch (e) { return manejar(e, "No se pudieron cargar las notificaciones"); } }
export async function leerNotificacion(id: string) { try { return (await api.patch(`/comunicacion/notificaciones/${id}/leida`)).data; } catch (e) { return manejar(e, "No se pudo marcar la notificación"); } }
export async function listarAuditoria(): Promise<EventoAuditoria[]> { try { return (await api.get("/comunicacion/auditoria", { params: { limite: 500 } })).data.eventos; } catch (e) { return manejar(e, "No se pudo cargar la auditoría"); } }
export async function registrarCierreSesion() { try { await api.post("/comunicacion/auditoria/logout"); } catch { /* no bloquea el cierre */ } }
