import api from "@/lib/axios";
export type Prenda = { _id: string; nombre: string; requiereTalla: boolean; activo: boolean };
type ReferenciaFraterno = string | { _id: string; numeroFraterno?: string };
export type Entrega = { _id: string; fraternoId: ReferenciaFraterno; prendaId: Prenda; cantidad: number; talla?: string; estado: string; fechaEntrega: string };
export type TallaFraterno = { _id: string; fraternoId?: ReferenciaFraterno; usuarioId?: string; tallaPolera: string; tallaChamarra: string; edicionBloqueada?: boolean; fechaActualizado?: string };
export type ConfiguracionTallas = { habilitado: boolean; fechaLimite: string | null; gestion?: string };
export type ResumenTallas = Record<"POLERA" | "CHAMARRA", Record<"HOMBRE" | "MUJER", { tallas: Array<{ talla: string; cantidad: number }>; total: number }>> & { totalGeneral: number };
export const obtenerIndumentaria = async () => (await api.get("/indumentaria")).data as { tallas: TallaFraterno[]; prendas: Prenda[]; entregas: Entrega[]; cuotas: Array<{ preregistroId: string; montoTotal: number; montoPagado: number; saldo: number; estado: string }>; configuracionTallas: ConfiguracionTallas; resumenTallas: ResumenTallas };
export const obtenerMiIndumentaria = async () => (await api.get("/indumentaria/mia")).data as { fraterno: { _id: string; numeroFraterno: string } | null; talla: TallaFraterno | null; entregas: Entrega[]; edicionTallasBloqueada: boolean; pago: { tieneCuota: boolean; envioBaucher: boolean; primeraCuotaVerificada: boolean; estadoPrimeraCuota: "NO_ENVIADA" | "PENDIENTE" | "VERIFICADO" | "OBSERVADO" | "RECHAZADO" }; configuracionTallas?: ConfiguracionTallas };
export const guardarMisTallas = async (datos:{tallaPolera:string;tallaChamarra:string}) => (await api.put("/indumentaria/mia/tallas",datos)).data;
export const guardarTalla = async (datos: { fraternoId: string; tallaPolera: string; tallaChamarra: string }) => (await api.put("/indumentaria/tallas", datos)).data as { message: string; talla: TallaFraterno };
export const guardarTallaUsuario = async (datos: { usuarioId: string; tallaPolera: string; tallaChamarra: string }) => (await api.put("/indumentaria/tallas/usuario", datos)).data as { message: string; talla: TallaFraterno };
export const cambiarBloqueoTalla = async (fraternoId: string, bloqueada: boolean) => (await api.patch(`/indumentaria/tallas/${fraternoId}/bloqueo`, { bloqueada })).data;
export const crearPrenda = async (datos: { nombre: string; requiereTalla: boolean }) => (await api.post("/indumentaria/prendas", datos)).data;
export const crearEntrega = async (datos: { fraternoId: string; prendaId: string; cantidad: number; talla?: string }) => (await api.post("/indumentaria/entregas", datos)).data;
export const cambiarEntrega = async (id: string, estado: string) => (await api.patch(`/indumentaria/entregas/${id}`, { estado })).data;
export const configurarRegistroTallas = async (datos: { habilitado: boolean; sinFechaLimite: boolean; fechaLimite?: string | null }) => (await api.put("/indumentaria/configuracion-tallas", datos)).data;
