import api from "@/lib/axios";
import { obtenerMensajeError } from "./apiError";
import axios from "axios";

export type PersonaReporte = {
  usuarioId: string;
  nombres?: string;
  apellidoPaterno?: string;
  apellidoMaterno?: string;
  nombre: string;
  ci: string;
  telefono?: string;
  email: string;
  genero: string;
  facultad: string;
  carrera: string;
  origen: string;
  estadoUsuario: string;
  estadoPreregistro: string;
  cuota: { clasificacion: string; montoTotal: number; montoPagado: number; saldo: number; cantidadPagos: number };
};
export type Reporte = { generadoEn: string; gestion: { _id: string; nombre: string; anio: number }; resumen: Record<string, number>; finanzas: Record<string, number>; distribuciones: Record<string, { nombre: string; total: number }[]>; personas: PersonaReporte[] };
export type EstadoAlmacenamiento = { archivos: { total: number; bytes: number }; comprobantes: { total: number; bytes: number; promedioBytes: number }; disco: { disponibleBytes: number }; alerta: string };
export type RegistroTallaReporte = { fraternoId: string; nombres?: string; apellidoPaterno?: string; apellidoMaterno?: string; nombre: string; ci: string; telefono?: string; genero?: string; bloque: string; tallaPolera?: string; tallaChamarra?: string };
export type RegistroFormacionReporte = { id: string; nombres?: string; apellidoPaterno?: string; apellidoMaterno?: string; nombre: string; ci: string; telefono?: string; email?: string; bloque?: string; estado: string; puntajeTotal?: number };
export type ResumenTallaCuota = { total: number; conTalla: number; sinTalla: number; conPolera: number; sinPolera: number; conChamarra: number; sinChamarra: number; sinNingunaTalla: number; primeraCuotaPagada: number; primeraCuotaPendiente: number; sinTallaYSinPrimeraCuota: number; conTallaSinPago: number; conTallaPagoPendiente: number; conTallaPagoVerificado: number; conTallaPagoParcial: number; conTallaPagoCompleto: number };
export type PersonaTallaCuota = { usuarioId: string; fraternoId: string; nombre: string; ci: string; codigoFraterno: string; sexo: string; telefono: string; whatsapp: string | null; correo: string; roles: string[]; tipoRegistro: string; perfilFraterno: boolean; participante: boolean; estadoInscripcion: string; estadoUsuario: string; bloque: string; asignacion: string; tallaPolera: string | null; tallaChamarra: string | null; estadoCampoPolera: "VALIDA" | "SIN TALLA" | "SIN DEFINIR"; estadoCampoChamarra: "VALIDA" | "SIN TALLA" | "SIN DEFINIR"; estadoTallaPolera: "REGISTRADA" | "SIN REGISTRAR" | "SIN DEFINIR" | "NO APLICA"; estadoTallaChamarra: "REGISTRADA" | "SIN REGISTRAR" | "SIN DEFINIR" | "NO APLICA"; tienePolera: boolean; tieneChamarra: boolean; conTalla: boolean; pendienteTalla: "POLERA" | "CHAMARRA" | "AMBAS" | null; estadoTalla: "TALLAS COMPLETAS" | "SOLO POLERA" | "SOLO CHAMARRA" | "SIN TALLA" | "SIN DEFINIR"; estadoMedicion: string; primeraCuota: "PAGADA" | "PENDIENTE" | "SIN REGISTRO / NO APLICA"; estadoPago: string; verificacionPrimeraCuota: string; estadoPagoReporte: string; estadoVerificacionPago: string; montoPrimeraCuota: number; montoRegistradoPrimeraCuota: number; montoVerificadoPrimeraCuota: number; saldoPrimeraCuota: number; montoPagadoPrimeraCuota: number; planPagos: string; numeroCuotas: number; cuotasPagadas: number; cuotasPendientes: number; cuotasPorVerificar: number; montoRegistradoTotal: number; montoVerificadoTotal: number; totalPagado: number; saldoTotal: number; estadoPagoGeneral: string; fechaUltimoPago: string | null; fechaRegistro: string | null; prioridadSeguimiento: "ALTA" | "MEDIA" | "BAJA"; motivoSeguimiento: string; problemasCalidad: string[]; estadoGeneral: string };
export type DistribucionTalla = { talla: string; poleraHombres: number; poleraMujeres: number; chamarraHombres: number; chamarraMujeres: number };
export type ReporteTallasPrimeraCuota = { generadoEn: string; gestion: { _id: string; nombre: string; anio: number }; resumen: ResumenTallaCuota & { totalUsuarios: number; conPerfilFraterno: number; sinPerfilFraterno: number; administradores: number; guias: number; totalHombres: number; totalMujeres: number; sinBloque: number; hombres: ResumenTallaCuota; mujeres: ResumenTallaCuota }; resumenGeneralTallas: { totalUsuarios: number; totalHombres: number; totalMujeres: number; tallasCompletas: number; soloPolera: number; soloChamarra: number; sinTalla: number; sinDefinir: number }; tallasDisponibles: string[]; distribucionTallas: DistribucionTalla[]; resumenSinDefinir: { personasUnicas: number; camposPrenda: number }; personasSinDefinir: PersonaTallaCuota[]; bloques: string[]; personas: PersonaTallaCuota[] };
export type PagoCronologico = { fechaPago: string; fechaRevision?: string; monto: number; numeroPago: number };
export type PersonaPagoCronologico = { cuotaId: string; fraternoId: string; nombre: string; ci: string; bloque: string; planElegido: number | null; pagosVerificados: number; montoTotal: number; montoVerificado: number; saldoVerificado: number; primera: PagoCronologico | null; segunda: PagoCronologico | null; tercera: PagoCronologico | null; fechaCompleto: string | null; estado: "PAGO_COMPLETO" | "PAGO_PARCIAL" | "SIN_PAGO"; revisiones: { pendientes: number; observados: number; rechazados: number } };
export type ReportePagosCronologicos = { gestion: { _id: string; nombre: string; anio: number } | null; personas: PersonaPagoCronologico[]; rankings: { primera: PersonaPagoCronologico[]; segunda: PersonaPagoCronologico[]; tercera: PersonaPagoCronologico[]; completos: PersonaPagoCronologico[] } };
export type CentroControl = { gestion: { _id: string; nombre: string; anio: number } | null; personas?: { total: number }; pagos?: { completos: number; parciales: number; sinPago: number; pendientesRevision: number; observados: number }; bloques?: { total: number; conBloque: number; sinBloque: number; listos: number; faltaPago: number; faltaTalla: number }; indumentaria?: { completos: number; parciales: number; sinEntrega: number; conAlgunaTalla: number } };
export type PagoReporteMatricula = { estado:string;monto:number;fechaPago:string|null;fechaVerificacion:string|null;metodo:string };
export type ClasificacionPagoMatricula = "PAGO_COMPLETO"|"SOLO_PRIMER_PAGO"|"HASTA_SEGUNDO_PAGO"|"TRES_PAGOS_VERIFICADOS"|"SIN_PAGO"|"REVISAR";
export type IntegranteMatricula = { usuarioId:string;fraternoId:string;detalleBloqueId:string;matricula:string;nombreCompleto:string;ci:string;sexo:string;telefono:string;facultad:string;carrera:string;numeroFraterno:string;bloqueId:string;bloque:string;guiasHombres:string;guiasMujeres:string;tallaPolera:string;tallaChamarra:string;condicion:string;estado:string;planPagos:number|null;estadoCuota:string;pagosVerificados:number;montoVerificado:number;saldo:number|null;primerPago:PagoReporteMatricula;segundoPago:PagoReporteMatricula;tercerPago:PagoReporteMatricula;fechaPagoCompleto:string|null;clasificacionPago:ClasificacionPagoMatricula;pendientes:number;observados:number;rechazados:number;observaciones:string };
export type ResumenBloqueMatricula = {_id:string;nombre:string;total:number;pagoCompleto:number;soloPrimerPago:number;hastaSegundoPago:number;tresPagos:number;sinPago:number;pendientes:number};
export type ReporteIntegrantesMatricula = { gestion:{_id:string;nombre:string;anio:number};generadoEn:string;personas:IntegranteMatricula[];resumen:{total:number;conMatricula:number;sinMatricula:number;hombres:number;mujeres:number;bloques:number;inconsistencias:number;pagoCompleto:number;soloPrimerPago:number;hastaSegundoPago:number;tresPagosVerificados:number;sinPago:number;pendientes:number;observados:number;rechazados:number;detalleBloques:ResumenBloqueMatricula[]} };
export type MovimientoControl={pagoId:string;numeroPago:number;monto:number;fechaPago:string;estado:string};
export type PersonaControlFinanciero={usuarioId:string;preregistroId:string;fraternoId:string;cuotaId:string;codigo:string;nombre:string;ci:string;sexo:string;telefono:string;whatsapp:string;roles:string[];bloque:string;estadoBloqueActual:string;bloqueAnterior:string;tipo:"INTERNO"|"EXTERNO"|"SIN CLASIFICAR";datoClasificacion:string;exento:boolean;motivoExencion:string;observacionExencion:string;fechaExencion:string|null;montoPlan:number;montoTotal:number;montoRegistrado:number;montoVerificado:number;montoPendienteRevision:number;saldo:number;cuotasRegistradas:number;cuotasVerificadas:number;pagosPendientes:number;pagosPendientesDetalle:MovimientoControl[];pagosVerificadosDetalle:MovimientoControl[];estadoPago:string;participacion:string;estadoFraterno:string;estadoUsuario:string;asignacionActiva:boolean;motivoFuera:string;categoriaFaltante?:string;fechaUltimoPago:string|null;problemas:string[]};
export type ResumenControlFinanciero={nombre:string;personas:number;internos:number;externos:number;sinClasificar:number;montoInternos:number;montoExternos:number;montoTeorico:number;exentos:number;exentosInternos:number;exentosExternos:number;montoExento:number;montoExentoInterno:number;montoExentoExterno:number;exentosConPago:number;obligados:number;montoRealEsperado:number;montoVerificado:number;montoVerificadoObligados:number;montoVerificadoExentos:number;montoPendienteRevision:number;personasPendientes:number;pagosPendientes:number;saldoPorCobrar:number;sinPago:number;montoSinPago:number;pagoParcial:number;montoEsperadoParcial:number;montoVerificadoParcial:number;saldoParcial:number;pagoCompleto:number;montoVerificadoCompleto:number;diferencia:number};
export type CategoriaDesglose={personas:number;monto:number};
export type ControlFinancieroBloques={generadoEn:string;gestion:{_id:string;nombre:string;anio:number}|null;resumenGeneral:{personas:number;cuotas:number;montoEsperado:number;montoVerificado:number;saldo:number;montoPendienteRevision:number;registrosVerificados:number;registrosPendientes:number;personasPendientes:number};resumen:ResumenControlFinanciero;desgloseFaltante:{inconsistencias:CategoriaDesglose;participacionRevisar:CategoriaDesglose;pagoPendiente:CategoriaDesglose;sinPago:CategoriaDesglose;pagoParcial:CategoriaDesglose;otros:CategoriaDesglose;total:number;noExplicado:number};porBloque:ResumenControlFinanciero[];personas:PersonaControlFinanciero[];fueraBloques:PersonaControlFinanciero[];resumenFuera:{personas:number;montoEsperado:number;montoVerificado:number;montoPendienteRevision:number;registrosVerificados:number;registrosPendientes:number;retirados:number;sinBloqueActivo:number;otros:number};reconciliacion:{esperado:{general:number;bloques:number;diferencia:number;detalleExplicado:number;noExplicada:number};verificado:{general:number;bloques:number;diferencia:number;detalleExplicado:number;noExplicada:number;desglose:{obligadosConBloque:number;exentosConBloque:number;sinBloqueActivo:number;retirados:number;otros:number}}};validaciones:Record<string,boolean>;inconsistencias:Array<{nombre:string;ci:string;bloque:string;problemas:string[]}>};
export type TipoPagoAuditoria="FREE"|"DESCUENTO"|"NORMAL"|"EXENTO"|"REVISAR";
export type PagoAuditoriaFinanciera={pagoId:string;usuarioId:string;cuotaId:string;nombre:string;ci:string;roles:string[];bloque:string;participacion:string;tipo:string;tipoPagoAuditoria:TipoPagoAuditoria;numeroPago:number;monto:number;fechaPago:string;fechaRevision:string|null;estado:string;metodo:string;tieneComprobante:boolean};
export type AjusteFinancieroActual={ajusteId:string;accion:string;motivo:string;tipoExencion:string;porcentajeDescuento:number;montoEsperadoOriginal:number;montoEsperadoFinal:number;fecha:string};
export type HistorialAjusteFinanciero=AjusteFinancieroActual&{usuarioId:string;nombre:string;ci:string;administrador:string};
export type PersonaAuditoriaFinanciera=PersonaControlFinanciero&{usuarioActivo:boolean;montoEsperadoRegistrado:number;montoEsperadoAjustado:number;montoDescontado:number;montoObservado:number;montoRechazado:number;saldoCalculado:number;saldoGuardado:number;estadoCuota:string;tipoPagoAuditoria:TipoPagoAuditoria;estadoBeneficio:string;referenciaBeneficio:string;estadoAjusteFinanciero:string;incluidoCalculo:boolean;ajusteFinanciero:AjusteFinancieroActual|null;pagosDetalle:PagoAuditoriaFinanciera[];ultimaActividad:string|null};
export type ResumenAuditoriaGeneral={cantidad:number;montoEsperadoBruto:number;montoEsperado:number;montoPagado:number;montoVerificado:number;montoPendiente:number;montoPorVerificar:number;montoObservado:number;montoRechazado:number;registros:number;registrosVerificados:number;registrosPorVerificar:number};
export type ResumenAuditoriaBloques={cantidad:number;internos:number;externos:number;sinClasificar:number;exentos:number;montoTeorico:number;montoExento:number;montoEsperado:number;montoVerificado:number;montoPendiente:number;montoPorVerificar:number};
export type AuditoriaFinancieraGeneral={generadoEn:string;gestion:{_id:string;nombre:string;anio:number}|null;definiciones:Record<string,string>;universoGeneral:ResumenAuditoriaGeneral;universoBloques:ResumenAuditoriaBloques;diferencias:{esperado:{general:number;bloques:number;diferencia:number;fueraDeBloque:number;exencionesEnBloque:number;noExplicada:number};verificado:{general:number;bloques:number;diferencia:number;fueraDeBloque:number;noExplicada:number}};resumenAjustes:{totalGeneral:number;totalExcluido:number;totalExento:number;totalDescuento:number;totalParticipacionReal:number};historialAjustes:HistorialAjusteFinanciero[];personas:PersonaAuditoriaFinanciera[];pagos:PagoAuditoriaFinanciera[];conBloque:PersonaAuditoriaFinanciera[];sinBloque:PersonaAuditoriaFinanciera[];pagosSinBloque:PersonaAuditoriaFinanciera[];pagosSinParticipacion:PersonaAuditoriaFinanciera[];personasSinPago:PersonaAuditoriaFinanciera[];inconsistencias:PersonaAuditoriaFinanciera[];referencias:Array<{alias:string;tipo:"FREE"|"DESCUENTO"|"REVISAR";detalle:string;estado:string;candidatos:Array<{usuarioId:string;nombre:string;ci:string;tipoPagoAuditoria:TipoPagoAuditoria;estadoBeneficio:string}>}>;clasificaciones:Array<{tipo:TipoPagoAuditoria;personas:number}>;validaciones:Record<string,boolean>};
export type EstadoCuotaAuditoriaParticipacion={estado:string;monto:number;fecha:string|null};
export type PersonaAuditoriaParticipacion={usuarioId:string;preregistroId:string;fraternoId:string;cuotaId:string;nombre:string;ci:string;ru:string;codigoFraterno:string;celular:string;whatsapp:string;correo:string;sexo:string;roles:string[];rolActual:string;bloque:string;guiasBloque:string[];estadoParticipacion:string;evidencias:string[];tienePolera:boolean;tallaPolera:string;tieneChamarra:boolean;tallaChamarra:string;fechaMedicion:string|null;origen:string;tipoParticipante:"INTERNO"|"EXTERNO"|"EXENTO"|"DESCUENTO"|"FREE"|"SIN CLASIFICAR";montoOriginal:number;montoEsperadoRegistrado:number;montoEsperado:number;porcentajeDescuento:number;primeraCuota:EstadoCuotaAuditoriaParticipacion;segundaCuota:EstadoCuotaAuditoriaParticipacion;terceraCuota:EstadoCuotaAuditoriaParticipacion;totalPagado:number;totalVerificado:number;saldoPendiente:number;estadoCuota:string;exento:boolean;motivoExencion:string;administradorExencion:string;fechaExencion:string|null;beneficioReferenciado:string;estadoBeneficio:string;ultimaActividad:string|null;problemas:string[]};
export type ResumenAuditoriaParticipacion={participantes:number;personasQueFormanMonto:number;conBloque:number;conTalla:number;conCuota:number;internos:number;externos:number;exentos:number;descuentos:number;descuentosReferenciados:number;free:number;totalGeneralRegistrado:number;montoInternos:number;montoExternos:number;montoSinClasificar:number;montoExentoRegistrado:number;montoDescuentoOriginal:number;montoDescuentoFinal:number;montoRealEsperado:number;totalPagado:number;totalVerificado:number;saldoPendiente:number;montoExplicado:number;montoSinExplicacion:number;inconsistencias:number};
export type AuditoriaParticipacion={generadoEn:string;gestion:{_id:string;nombre:string;anio:number}|null;definicionUniverso:string;tarifas:{interno:number;externo:number};resumen:ResumenAuditoriaParticipacion;personas:PersonaAuditoriaParticipacion[];conBloque:PersonaAuditoriaParticipacion[];sinBloqueConPago:PersonaAuditoriaParticipacion[];sinBloqueConTalla:PersonaAuditoriaParticipacion[];exentos:PersonaAuditoriaParticipacion[];descuentos:PersonaAuditoriaParticipacion[];sinPago:PersonaAuditoriaParticipacion[];inconsistencias:PersonaAuditoriaParticipacion[];controlExenciones:PersonaAuditoriaParticipacion[];referenciasBeneficio:Array<{etiqueta:string;tipo:"FREE"|"EXENTO"|"DESCUENTO"|"REVISAR";porcentaje?:number;detalle:string;estado:string;candidatos:Array<{usuarioId:string;nombre:string;ci:string;tipoParticipante:string;estadoBeneficio:string}>}>;validaciones:Record<string,boolean>;consultas:string[]};
export type TipoOrigenNomina="INTERNO"|"EXTERNO"|"SIN CLASIFICAR";
export type PersonaNominaMatricula={usuarioId:string;documentoId:string;preregistroId:string;fraternoId:string;nombres:string;apellidoPaterno:string;apellidoMaterno:string;nombreCompleto:string;ci:string;sexo:string;telefono:string;telefonoRegistrado:string;whatsapp:string;email:string;roles:string[];tipoOrigen:TipoOrigenNomina;origenRegistrado:string;tipoFraterno:string;facultad:string;carrera:string;bloque:string;asignacion:string;codigoFraterno:string;numeroPreregistro:string;registroUniversitario:string;numeroMatricula:null;estadoDocumento:string;observacionDocumento:string;fechaCargaMatricula:string|null;nombreArchivo:string;extensionArchivo:string;archivoDisponible:boolean|null;tallaPolera:string;tallaChamarra:string;pago:{estado:string;plan:number|null;montoTotal:number;montoRegistrado:number;montoVerificado:number;montoPendienteRevision:number;saldo:number;cuotasVerificadas:number;cuotasPendientesRevision:number};listoNomina:boolean;inconsistencias:string[]};
export type ReporteNominaMatriculas={generadoEn:string;gestion:{_id:string;nombre:string;anio:number}|null;plantilla:{nombre:string;capacidad:number};resumen:{totalConMatricula:number;internos:number;externos:number;sinClasificar:number;hombres:number;mujeres:number;conBloque:number;sinBloque:number;conRu:number;sinRu:number;listosNomina:number;inconsistencias:number};bloques:string[];roles:string[];personas:PersonaNominaMatricula[]};
export async function obtenerReporteEjecutivo() { try { return (await api.get<Reporte>("/reportes/ejecutivo")).data; } catch (e) { throw new Error(obtenerMensajeError(e, "No se pudo generar el reporte")); } }
export async function obtenerAlmacenamiento() { try { return (await api.get<EstadoAlmacenamiento>("/reportes/almacenamiento")).data; } catch (e) { throw new Error(obtenerMensajeError(e, "No se pudo medir el almacenamiento")); } }
export async function obtenerReporteTallas() { try { return (await api.get<{ registros: RegistroTallaReporte[] }>("/reportes/tallas")).data; } catch (e) { throw new Error(obtenerMensajeError(e, "No se pudo generar el reporte de tallas")); } }
export async function obtenerReporteFormacion() { try { return (await api.get<{ guias: RegistroFormacionReporte[]; postulantes: RegistroFormacionReporte[] }>("/reportes/formacion")).data; } catch (e) { throw new Error(obtenerMensajeError(e, "No se pudo generar el reporte de guías")); } }
export async function obtenerReporteTallasPrimeraCuota() { try { return (await api.get<ReporteTallasPrimeraCuota>("/reportes/tallas-primera-cuota")).data; } catch (e) { throw new Error(obtenerMensajeError(e, "No se pudo generar el reporte general de tallas y primera cuota")); } }
export async function obtenerReportePagosCronologicos() { try { return (await api.get<ReportePagosCronologicos>("/reportes/pagos-cronologicos")).data; } catch (e) { throw new Error(obtenerMensajeError(e, "No se pudo generar el reporte cronológico de pagos")); } }
export async function obtenerCentroControl() { try { return (await api.get<CentroControl>("/reportes/centro-control")).data; } catch (e) { throw new Error(obtenerMensajeError(e, "No se pudo cargar el centro de control")); } }
export async function obtenerReporteIntegrantesMatricula() { try { return (await api.get<ReporteIntegrantesMatricula>("/reportes/integrantes-matricula")).data; } catch (e) { throw new Error(obtenerMensajeError(e, "No se pudo generar el reporte de integrantes por matrícula")); } }
export async function obtenerControlFinancieroBloques() { try { return (await api.get<ControlFinancieroBloques>("/reportes/control-financiero-bloques")).data; } catch (e) { throw new Error(obtenerMensajeError(e, "No se pudo cargar el control financiero de bloques")); } }
export async function obtenerAuditoriaFinancieraGeneral(){try{return(await api.get<AuditoriaFinancieraGeneral>("/reportes/auditoria-financiera")).data}catch(e){throw new Error(obtenerMensajeError(e,"No se pudo cargar la auditoría financiera general"))}}
export async function obtenerAuditoriaParticipacion(){try{return(await api.get<AuditoriaParticipacion>("/reportes/auditoria-participacion")).data}catch(e){throw new Error(obtenerMensajeError(e,"No se pudo cargar la auditoría de participación"))}}
export async function obtenerNominaMatriculas(){try{return(await api.get<ReporteNominaMatriculas>("/reportes/nomina-matriculas")).data}catch(e){throw new Error(obtenerMensajeError(e,"No se pudo cargar el control de matrículas"))}}

const guardarBlob=(contenido:Blob,nombre:string)=>{const url=URL.createObjectURL(contenido),enlace=document.createElement("a");enlace.href=url;enlace.download=nombre;enlace.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
const mensajeErrorBlob=async(error:unknown,predeterminado:string)=>{if(axios.isAxiosError(error)&&error.response?.data instanceof Blob){try{const datos=JSON.parse(await error.response.data.text());if(typeof datos?.error==="string")return datos.error}catch{return predeterminado}}return obtenerMensajeError(error,predeterminado)};
const nombreDescarga=(cabecera:unknown,respaldo:string)=>{const coincidencia=String(cabecera??"").match(/filename="?([^";]+)"?/i);return coincidencia?.[1]||respaldo};
export async function descargarNominaOficial(usuarioIds:string[]){try{const respuesta=await api.post<Blob>("/reportes/nomina-matriculas/oficial",{usuarioIds},{responseType:"blob"});guardarBlob(respuesta.data,nombreDescarga(respuesta.headers["content-disposition"],`Nomina_Oficial_Tinkus_${new Date().toISOString().slice(0,10)}.xlsx`))}catch(e){throw new Error(await mensajeErrorBlob(e,"No se pudo generar la nómina oficial"))}}
export async function descargarDocumentosMatriculasZip(usuarioIds:string[]){try{const respuesta=await api.post<Blob>("/reportes/nomina-matriculas/documentos-zip",{usuarioIds},{responseType:"blob"});guardarBlob(respuesta.data,nombreDescarga(respuesta.headers["content-disposition"],"Documentos_Matriculas_Tinkus_2026.zip"))}catch(e){throw new Error(await mensajeErrorBlob(e,"No se pudo generar el ZIP de documentos"))}}
export async function auditarReporteMatriculas(cantidad:number){try{await api.post("/reportes/nomina-matriculas/reporte-exportado",{cantidad})}catch(e){throw new Error(obtenerMensajeError(e,"El reporte se generó, pero no se pudo registrar la auditoría"))}}
export async function abrirDocumentoMatricula(documentoId:string,descargar=false){const ventana=descargar?null:window.open("about:blank","_blank");try{const respuesta=await api.get<Blob>(`/reportes/nomina-matriculas/documentos/${documentoId}`,{params:{download:descargar?"1":"0"},responseType:"blob"});const url=URL.createObjectURL(respuesta.data);if(descargar){const enlace=document.createElement("a");enlace.href=url;enlace.download=nombreDescarga(respuesta.headers["content-disposition"],`MATRICULA_${documentoId}`);enlace.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return}if(ventana){ventana.opener=null;ventana.location.href=url}else window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){ventana?.close();throw new Error(await mensajeErrorBlob(e,"No se pudo recuperar el documento de matrícula"))}}
