import api from "@/lib/axios";
import { obtenerMensajeError } from "./apiError";

export type PersonaReporte = {
  usuarioId: string;
  nombres?: string;
  apellidoPaterno?: string;
  apellidoMaterno?: string;
  nombre: string;
  ci: string;
  telefono?: string;
  email: string;
  genero: string;
  facultad: string;
  carrera: string;
  origen: string;
  estadoUsuario: string;
  estadoPreregistro: string;
  cuota: { clasificacion: string; montoTotal: number; montoPagado: number; saldo: number; cantidadPagos: number };
};
export type Reporte = { generadoEn: string; gestion: { _id: string; nombre: string; anio: number }; resumen: Record<string, number>; finanzas: Record<string, number>; distribuciones: Record<string, { nombre: string; total: number }[]>; personas: PersonaReporte[] };
export type EstadoAlmacenamiento = { archivos: { total: number; bytes: number }; comprobantes: { total: number; bytes: number; promedioBytes: number }; disco: { disponibleBytes: number }; alerta: string };
export type RegistroTallaReporte = { fraternoId: string; nombres?: string; apellidoPaterno?: string; apellidoMaterno?: string; nombre: string; ci: string; telefono?: string; genero?: string; bloque: string; tallaPolera?: string; tallaChamarra?: string };
export type RegistroFormacionReporte = { id: string; nombres?: string; apellidoPaterno?: string; apellidoMaterno?: string; nombre: string; ci: string; telefono?: string; email?: string; bloque?: string; estado: string; puntajeTotal?: number };
export type ResumenTallaCuota = { total: number; conTalla: number; sinTalla: number; conPolera: number; sinPolera: number; conChamarra: number; sinChamarra: number; sinNingunaTalla: number; primeraCuotaPagada: number; primeraCuotaPendiente: number; sinTallaYSinPrimeraCuota: number; conTallaSinPago: number; conTallaPagoPendiente: number; conTallaPagoVerificado: number; conTallaPagoParcial: number; conTallaPagoCompleto: number };
export type PersonaTallaCuota = { usuarioId: string; fraternoId: string; nombre: string; ci: string; codigoFraterno: string; sexo: string; telefono: string; whatsapp: string | null; correo: string; roles: string[]; tipoRegistro: string; perfilFraterno: boolean; participante: boolean; estadoInscripcion: string; estadoUsuario: string; bloque: string; asignacion: string; tallaPolera: string | null; tallaChamarra: string | null; estadoCampoPolera: "VALIDA" | "SIN TALLA" | "SIN DEFINIR"; estadoCampoChamarra: "VALIDA" | "SIN TALLA" | "SIN DEFINIR"; estadoTallaPolera: "REGISTRADA" | "SIN REGISTRAR" | "SIN DEFINIR" | "NO APLICA"; estadoTallaChamarra: "REGISTRADA" | "SIN REGISTRAR" | "SIN DEFINIR" | "NO APLICA"; tienePolera: boolean; tieneChamarra: boolean; conTalla: boolean; pendienteTalla: "POLERA" | "CHAMARRA" | "AMBAS" | null; estadoTalla: "TALLAS COMPLETAS" | "SOLO POLERA" | "SOLO CHAMARRA" | "SIN TALLA" | "SIN DEFINIR"; estadoMedicion: string; primeraCuota: "PAGADA" | "PENDIENTE" | "SIN REGISTRO / NO APLICA"; estadoPago: string; verificacionPrimeraCuota: string; estadoPagoReporte: string; estadoVerificacionPago: string; montoPrimeraCuota: number; montoRegistradoPrimeraCuota: number; montoVerificadoPrimeraCuota: number; saldoPrimeraCuota: number; montoPagadoPrimeraCuota: number; planPagos: string; numeroCuotas: number; cuotasPagadas: number; cuotasPendientes: number; cuotasPorVerificar: number; montoRegistradoTotal: number; montoVerificadoTotal: number; totalPagado: number; saldoTotal: number; estadoPagoGeneral: string; fechaUltimoPago: string | null; fechaRegistro: string | null; prioridadSeguimiento: "ALTA" | "MEDIA" | "BAJA"; motivoSeguimiento: string; problemasCalidad: string[]; estadoGeneral: string };
export type DistribucionTalla = { talla: string; poleraHombres: number; poleraMujeres: number; chamarraHombres: number; chamarraMujeres: number };
export type ReporteTallasPrimeraCuota = { generadoEn: string; gestion: { _id: string; nombre: string; anio: number }; resumen: ResumenTallaCuota & { totalUsuarios: number; conPerfilFraterno: number; sinPerfilFraterno: number; administradores: number; guias: number; totalHombres: number; totalMujeres: number; sinBloque: number; hombres: ResumenTallaCuota; mujeres: ResumenTallaCuota }; resumenGeneralTallas: { totalUsuarios: number; totalHombres: number; totalMujeres: number; tallasCompletas: number; soloPolera: number; soloChamarra: number; sinTalla: number; sinDefinir: number }; tallasDisponibles: string[]; distribucionTallas: DistribucionTalla[]; resumenSinDefinir: { personasUnicas: number; camposPrenda: number }; personasSinDefinir: PersonaTallaCuota[]; bloques: string[]; personas: PersonaTallaCuota[] };
export type PagoCronologico = { fechaPago: string; fechaRevision?: string; monto: number; numeroPago: number };
export type PersonaPagoCronologico = { cuotaId: string; fraternoId: string; nombre: string; ci: string; bloque: string; planElegido: number | null; pagosVerificados: number; montoTotal: number; montoVerificado: number; saldoVerificado: number; primera: PagoCronologico | null; segunda: PagoCronologico | null; tercera: PagoCronologico | null; fechaCompleto: string | null; estado: "PAGO_COMPLETO" | "PAGO_PARCIAL" | "SIN_PAGO"; revisiones: { pendientes: number; observados: number; rechazados: number } };
export type ReportePagosCronologicos = { gestion: { _id: string; nombre: string; anio: number } | null; personas: PersonaPagoCronologico[]; rankings: { primera: PersonaPagoCronologico[]; segunda: PersonaPagoCronologico[]; tercera: PersonaPagoCronologico[]; completos: PersonaPagoCronologico[] } };
export type CentroControl = { gestion: { _id: string; nombre: string; anio: number } | null; personas?: { total: number }; pagos?: { completos: number; parciales: number; sinPago: number; pendientesRevision: number; observados: number }; bloques?: { total: number; conBloque: number; sinBloque: number; listos: number; faltaPago: number; faltaTalla: number }; indumentaria?: { completos: number; parciales: number; sinEntrega: number; conAlgunaTalla: number } };
export type PagoReporteMatricula = { estado:string;monto:number;fechaPago:string|null;fechaVerificacion:string|null;metodo:string };
export type ClasificacionPagoMatricula = "PAGO_COMPLETO"|"SOLO_PRIMER_PAGO"|"HASTA_SEGUNDO_PAGO"|"TRES_PAGOS_VERIFICADOS"|"SIN_PAGO"|"REVISAR";
export type IntegranteMatricula = { usuarioId:string;fraternoId:string;detalleBloqueId:string;matricula:string;nombreCompleto:string;ci:string;sexo:string;telefono:string;facultad:string;carrera:string;numeroFraterno:string;bloqueId:string;bloque:string;guiasHombres:string;guiasMujeres:string;tallaPolera:string;tallaChamarra:string;condicion:string;estado:string;planPagos:number|null;estadoCuota:string;pagosVerificados:number;montoVerificado:number;saldo:number|null;primerPago:PagoReporteMatricula;segundoPago:PagoReporteMatricula;tercerPago:PagoReporteMatricula;fechaPagoCompleto:string|null;clasificacionPago:ClasificacionPagoMatricula;pendientes:number;observados:number;rechazados:number;observaciones:string };
export type ResumenBloqueMatricula = {_id:string;nombre:string;total:number;pagoCompleto:number;soloPrimerPago:number;hastaSegundoPago:number;tresPagos:number;sinPago:number;pendientes:number};
export type ReporteIntegrantesMatricula = { gestion:{_id:string;nombre:string;anio:number};generadoEn:string;personas:IntegranteMatricula[];resumen:{total:number;conMatricula:number;sinMatricula:number;hombres:number;mujeres:number;bloques:number;inconsistencias:number;pagoCompleto:number;soloPrimerPago:number;hastaSegundoPago:number;tresPagosVerificados:number;sinPago:number;pendientes:number;observados:number;rechazados:number;detalleBloques:ResumenBloqueMatricula[]} };
export async function obtenerReporteEjecutivo() { try { return (await api.get<Reporte>("/reportes/ejecutivo")).data; } catch (e) { throw new Error(obtenerMensajeError(e, "No se pudo generar el reporte")); } }
export async function obtenerAlmacenamiento() { try { return (await api.get<EstadoAlmacenamiento>("/reportes/almacenamiento")).data; } catch (e) { throw new Error(obtenerMensajeError(e, "No se pudo medir el almacenamiento")); } }
export async function obtenerReporteTallas() { try { return (await api.get<{ registros: RegistroTallaReporte[] }>("/reportes/tallas")).data; } catch (e) { throw new Error(obtenerMensajeError(e, "No se pudo generar el reporte de tallas")); } }
export async function obtenerReporteFormacion() { try { return (await api.get<{ guias: RegistroFormacionReporte[]; postulantes: RegistroFormacionReporte[] }>("/reportes/formacion")).data; } catch (e) { throw new Error(obtenerMensajeError(e, "No se pudo generar el reporte de guías")); } }
export async function obtenerReporteTallasPrimeraCuota() { try { return (await api.get<ReporteTallasPrimeraCuota>("/reportes/tallas-primera-cuota")).data; } catch (e) { throw new Error(obtenerMensajeError(e, "No se pudo generar el reporte general de tallas y primera cuota")); } }
export async function obtenerReportePagosCronologicos() { try { return (await api.get<ReportePagosCronologicos>("/reportes/pagos-cronologicos")).data; } catch (e) { throw new Error(obtenerMensajeError(e, "No se pudo generar el reporte cronológico de pagos")); } }
export async function obtenerCentroControl() { try { return (await api.get<CentroControl>("/reportes/centro-control")).data; } catch (e) { throw new Error(obtenerMensajeError(e, "No se pudo cargar el centro de control")); } }
export async function obtenerReporteIntegrantesMatricula() { try { return (await api.get<ReporteIntegrantesMatricula>("/reportes/integrantes-matricula")).data; } catch (e) { throw new Error(obtenerMensajeError(e, "No se pudo generar el reporte de integrantes por matrícula")); } }
