import Bloque from "../models/Bloque";
import DetalleBloque from "../models/DetalleBloque";
import Fraterno from "../models/Fraterno";
import PerfilUsuario from "../models/PerfilUsuario";
import Rol from "../models/Rol";
import Cuota from "../models/Cuota";
import DetalleCuota from "../models/DetalleCuota";
import Preregistro from "../models/Preregistro";
import Gestion from "../models/Gestion";

const sid=(v:any)=>String(v?._id??v??""), n=(v:any)=>Number((Number(v)||0).toFixed(2));
const sum=(xs:any[],campo:string)=>n(xs.reduce((a,x)=>a+Number(x[campo]||0),0));
const origen=(v:any)=>["INTERNO","INTERNO_UMSA"].includes(String(v??"").toUpperCase())?"INTERNO":["EXTERNO","EXTERNO_UMSA","EXTERNO_NO_UMSA"].includes(String(v??"").toUpperCase())?"EXTERNO":"SIN CLASIFICAR";
const nombre=(u:any)=>[u?.nombres,u?.apellidoPaterno,u?.apellidoMaterno].filter(Boolean).join(" ");

export function resumirControlFinanciero(xs:any[],nombreResumen:string){
 const internos=xs.filter(x=>x.tipo==="INTERNO"),externos=xs.filter(x=>x.tipo==="EXTERNO"),exentos=xs.filter(x=>x.exento),obligados=xs.filter(x=>!x.exento),teorico=sum(xs,"montoTotal"),montoExento=sum(exentos,"montoTotal"),esperado=n(teorico-montoExento),verificado=sum(xs,"montoVerificado"),verificadoObligados=sum(obligados,"montoVerificado"),verificadoExentos=sum(exentos,"montoVerificado"),sinPago=obligados.filter(x=>x.estadoPago==="SIN PAGO"),parciales=obligados.filter(x=>x.estadoPago==="PAGO PARCIAL"),completos=obligados.filter(x=>x.estadoPago==="PAGO COMPLETO"),pendientes=obligados.filter(x=>x.pagosPendientes>0);
 return {nombre:nombreResumen,personas:xs.length,internos:internos.length,externos:externos.length,sinClasificar:xs.length-internos.length-externos.length,montoInternos:sum(internos,"montoTotal"),montoExternos:sum(externos,"montoTotal"),montoTeorico:teorico,exentos:exentos.length,exentosInternos:exentos.filter(x=>x.tipo==="INTERNO").length,exentosExternos:exentos.filter(x=>x.tipo==="EXTERNO").length,montoExento,montoExentoInterno:sum(exentos.filter(x=>x.tipo==="INTERNO"),"montoTotal"),montoExentoExterno:sum(exentos.filter(x=>x.tipo==="EXTERNO"),"montoTotal"),exentosConPago:exentos.filter(x=>x.montoVerificado>0).length,obligados:obligados.length,montoRealEsperado:esperado,montoVerificado:verificado,montoVerificadoObligados:verificadoObligados,montoVerificadoExentos:verificadoExentos,montoPendienteRevision:sum(pendientes,"montoPendienteRevision"),personasPendientes:pendientes.length,pagosPendientes:pendientes.reduce((a,x)=>a+Number(x.pagosPendientes||0),0),saldoPorCobrar:sum(obligados,"saldo"),sinPago:sinPago.length,montoSinPago:sum(sinPago,"saldo"),pagoParcial:parciales.length,montoEsperadoParcial:sum(parciales,"montoTotal"),montoVerificadoParcial:sum(parciales,"montoVerificado"),saldoParcial:sum(parciales,"saldo"),pagoCompleto:completos.length,montoVerificadoCompleto:sum(completos,"montoVerificado"),diferencia:n(esperado-verificadoObligados)};
}

export async function obtenerControlFinancieroBloques(){
 const gestion:any=await Gestion.findOne({estado:{$in:["ACTIVA","INSCRIPCIONES"]},fechaEliminado:null}).sort({anio:-1}).lean();
 if(!gestion)return {generadoEn:new Date(),gestion:null,resumen:resumirControlFinanciero([],"GENERAL"),porBloque:[],personas:[],fueraBloques:[],inconsistencias:[],reconciliacion:{}};
 const preregistros:any[]=await Preregistro.find({gestionId:gestion._id,fechaEliminado:null}).lean();
 const usuarios:any[]=await PerfilUsuario.find({_id:{$in:preregistros.map(p=>p.usuarioId)},fechaEliminado:null}).select("nombres apellidoPaterno apellidoMaterno ci telefono sexo tipoOrigen roles estado fechaEliminado").lean();
 const usuarioMap=new Map(usuarios.map(u=>[sid(u),u])),preregistrosValidos=preregistros.filter(p=>usuarioMap.has(sid(p.usuarioId)));
 const cuotas:any[]=await Cuota.find({preregistroId:{$in:preregistrosValidos.map(p=>p._id)},fechaEliminado:null}).lean(),cuotaMap=new Map(cuotas.map(c=>[sid(c.preregistroId),c]));
 const pagos:any[]=await DetalleCuota.find({cuotaId:{$in:cuotas.map(c=>c._id)},fechaEliminado:null}).sort({fechaPago:1}).lean(),pagosMap=new Map<string,any[]>();for(const p of pagos)pagosMap.set(sid(p.cuotaId),[...(pagosMap.get(sid(p.cuotaId))??[]),p]);
 const fraternos:any[]=await Fraterno.find({gestionId:gestion._id,usuarioId:{$in:usuarios.map(u=>u._id)},fechaEliminado:null}).lean(),fraternoUsuario=new Map(fraternos.map(f=>[sid(f.usuarioId),f]));
 const bloques:any[]=await Bloque.find({gestionId:gestion._id}).select("nombre estado").lean(),bloqueMap=new Map(bloques.map(b=>[sid(b),b])),bloquesActivos=bloques.filter(b=>b.estado==="ACTIVO");
 const asignaciones:any[]=await DetalleBloque.find({fraternoId:{$in:fraternos.map(f=>f._id)},fechaEliminado:null}).sort({fechaAsignacion:-1}).lean(),asignacionActiva=new Map<string,any>(),historialAsignaciones=new Map<string,any[]>();for(const a of asignaciones){historialAsignaciones.set(sid(a.fraternoId),[...(historialAsignaciones.get(sid(a.fraternoId))??[]),a]);if(a.estado==="ACTIVO"&&bloqueMap.get(sid(a.bloqueId))?.estado==="ACTIVO"&&!asignacionActiva.has(sid(a.fraternoId)))asignacionActiva.set(sid(a.fraternoId),a)}
 const roles:any[]=await Rol.find({_id:{$in:usuarios.flatMap(u=>u.roles??[])}}).select("codigo nombre").lean(),rolMap=new Map(roles.map(r=>[sid(r),r.codigo||r.nombre]));
 const fila=(pre:any,c:any,u:any,f:any,a:any)=>{const mov=pagosMap.get(sid(c))??[],ver=mov.filter(p=>p.estadoRevision==="VERIFICADO"),pen=mov.filter(p=>p.estadoRevision==="PENDIENTE"),tipo=c?.tipoOrigenTarifa??origen(u?.tipoOrigen),total=tipo==="INTERNO"?770:tipo==="EXTERNO"?850:0,montoVerificado=n(ver.reduce((s,p)=>s+p.monto,0)),montoPendienteRevision=n(pen.reduce((s,p)=>s+p.monto,0)),exento=Boolean(c?.exentoPago),saldo=exento?0:n(Math.max(0,total-montoVerificado)),estadoPago=exento?"EXENTO":montoVerificado>=total&&total>0?"PAGO COMPLETO":montoVerificado>0?"PAGO PARCIAL":pen.length?"PENDIENTE DE VERIFICACIÓN":"SIN PAGO",bloque:any=a?bloqueMap.get(sid(a.bloqueId)):null,historial=f?(historialAsignaciones.get(sid(f))??[]):[],anterior=historial.find((x:any)=>x.estado!=="ACTIVO"||bloqueMap.get(sid(x.bloqueId))?.estado!=="ACTIVO"),bloqueAnterior:any=anterior?bloqueMap.get(sid(anterior.bloqueId)):null;return{usuarioId:sid(u),preregistroId:sid(pre),fraternoId:sid(f),cuotaId:sid(c),codigo:f?.numeroFraterno??pre.numeroPreRegistro??"",nombre:nombre(u),ci:u?.ci??"",sexo:u?.sexo??"SIN REGISTRO",telefono:u?.telefono??"",whatsapp:u?.telefono?`+591${String(u.telefono).replace(/\D/g,"")}`:"",roles:(u?.roles??[]).map((r:any)=>rolMap.get(sid(r))??"ROL DESCONOCIDO"),bloque:bloque?.nombre??"SIN BLOQUE",estadoBloqueActual:bloque?.estado??"SIN BLOQUE ACTIVO",bloqueAnterior:bloqueAnterior?.nombre??"SIN REGISTRO",tipo,datoClasificacion:c?.tipoOrigenTarifa?"Cuota.tipoOrigenTarifa":u?.tipoOrigen?"PerfilUsuario.tipoOrigen":"FALTA CLASIFICACIÓN",exento,motivoExencion:c?.motivoExencion??"",observacionExencion:c?.observacionExencion??"",fechaExencion:c?.fechaExencion??null,montoPlan:n(c?.montoTotal),montoTotal:total,montoRegistrado:n(mov.reduce((s,p)=>s+p.monto,0)),montoVerificado,montoPendienteRevision,saldo,cuotasRegistradas:mov.length,cuotasVerificadas:ver.length,pagosPendientes:pen.length,pagosPendientesDetalle:pen.map(p=>({pagoId:sid(p),numeroPago:p.numeroPago,monto:n(p.monto),fechaPago:p.fechaPago,estado:p.estadoRevision})),pagosVerificadosDetalle:ver.map(p=>({pagoId:sid(p),numeroPago:p.numeroPago,monto:n(p.monto),fechaPago:p.fechaPago,estado:p.estadoRevision})),estadoPago,participacion:["RETIRADO","INACTIVO"].includes(f?.estado)||u?.estado==="INACTIVO"?"RETIRADO":a?"ACTIVO":"REVISAR",estadoFraterno:f?.estado??"SIN FRATERNO",estadoUsuario:u?.estado??"SIN USUARIO",fechaUltimoPago:mov.at(-1)?.fechaPago??null,asignacionActiva:Boolean(a),motivoFuera:a?"":!f?"SIN PERFIL FRATERNO":["RETIRADO","INACTIVO"].includes(f.estado)?`FRATERNO ${f.estado}`:bloqueAnterior?`SIN ASIGNACIÓN ACTIVA; ÚLTIMO BLOQUE: ${bloqueAnterior.nombre}`:"SIN ASIGNACIÓN ACTIVA A BLOQUE",problemas:[] as string[]}};
 const todas=preregistrosValidos.map(pre=>{const u=usuarioMap.get(sid(pre.usuarioId)),c=cuotaMap.get(sid(pre)),f=fraternoUsuario.get(sid(pre.usuarioId)),a=f?asignacionActiva.get(sid(f)):null;return c&&u?fila(pre,c,u,f,a):null}).filter(Boolean) as any[];
 const personas=todas.filter(p=>p.asignacionActiva),fueraBloques=todas.filter(p=>!p.asignacionActiva),conteoAsignacion=new Map<string,number>();for(const a of asignaciones.filter(a=>a.estado==="ACTIVO"&&bloqueMap.get(sid(a.bloqueId))?.estado==="ACTIVO"))conteoAsignacion.set(sid(a.fraternoId),(conteoAsignacion.get(sid(a.fraternoId))??0)+1);
 const preregistrosPorUsuario=new Map<string,number>(),cuotasPorPreregistro=new Map<string,number>(),fraternosPorUsuario=new Map<string,number>();for(const pre of preregistrosValidos)preregistrosPorUsuario.set(sid(pre.usuarioId),(preregistrosPorUsuario.get(sid(pre.usuarioId))??0)+1);for(const c of cuotas)cuotasPorPreregistro.set(sid(c.preregistroId),(cuotasPorPreregistro.get(sid(c.preregistroId))??0)+1);for(const f of fraternos)fraternosPorUsuario.set(sid(f.usuarioId),(fraternosPorUsuario.get(sid(f.usuarioId))??0)+1);
 for(const p of todas){p.problemas=[(conteoAsignacion.get(p.fraternoId)??0)>1?"MÁS DE UN BLOQUE ACTIVO":"",(preregistrosPorUsuario.get(p.usuarioId)??0)>1?"MÁS DE UN PRERREGISTRO EN LA GESTIÓN":"",(fraternosPorUsuario.get(p.usuarioId)??0)>1?"MÁS DE UN FRATERNO EN LA GESTIÓN":"",(cuotasPorPreregistro.get(p.preregistroId)??0)>1?"MÁS DE UNA CUOTA PARA EL PRERREGISTRO":"",!p.cuotaId?"SIN CUOTA/PLAN":"",p.tipo==="SIN CLASIFICAR"?"SIN CLASIFICACIÓN":"",p.montoPlan&&p.montoPlan!==p.montoTotal?`PLAN ${p.montoPlan} DIFIERE DE TARIFA ${p.montoTotal}`:"",p.estadoPago==="PAGO COMPLETO"&&p.saldo!==0?"PAGO COMPLETO CON SALDO":"",p.montoVerificado>p.montoTotal&&p.montoTotal>0?"PAGO MAYOR AL PLAN":"",p.exento&&!p.motivoExencion?"EXENTO SIN MOTIVO":"",p.exento&&p.saldo!==0?"EXENTO CON DEUDA":"",p.participacion==="RETIRADO"&&p.asignacionActiva?"RETIRADO CON ASIGNACIÓN ACTIVA":""].filter(Boolean)}
 const resumenGeneral={personas:new Set(todas.map(p=>p.usuarioId)).size,cuotas:todas.length,montoEsperado:sum(todas,"montoPlan"),montoVerificado:sum(todas,"montoVerificado"),saldo:n(sum(todas,"montoPlan")-sum(todas,"montoVerificado")),montoPendienteRevision:sum(todas,"montoPendienteRevision"),registrosVerificados:todas.reduce((a,p)=>a+p.cuotasVerificadas,0),registrosPendientes:todas.reduce((a,p)=>a+p.pagosPendientes,0),personasPendientes:new Set(todas.filter(p=>p.pagosPendientes>0).map(p=>p.usuarioId)).size};
 const resumen=resumirControlFinanciero(personas,"GENERAL"),porBloque=bloquesActivos.map(b=>resumirControlFinanciero(personas.filter(p=>p.bloque===b.nombre),b.nombre)),inconsistencias=todas.filter(p=>p.problemas.length).map(p=>({nombre:p.nombre,ci:p.ci,bloque:p.bloque,problemas:p.problemas}));
 let pendientesDesglose=personas.filter(p=>!p.exento&&p.saldo>0);const tomar=(categoria:string,predicado:(p:any)=>boolean)=>{const elegidos=pendientesDesglose.filter(predicado);pendientesDesglose=pendientesDesglose.filter(p=>!predicado(p));for(const p of elegidos)p.categoriaFaltante=categoria;return{personas:elegidos.length,monto:sum(elegidos,"saldo")}};const desgloseFaltante={inconsistencias:tomar("INCONSISTENCIAS",p=>p.problemas.length>0),participacionRevisar:tomar("PARTICIPACIÓN POR REVISAR",p=>p.participacion!=="ACTIVO"),pagoPendiente:tomar("PAGO PENDIENTE DE VERIFICACIÓN",p=>p.pagosPendientes>0),sinPago:tomar("SIN NINGÚN PAGO",p=>p.montoVerificado===0),pagoParcial:tomar("PAGO PARCIAL",p=>p.montoVerificado>0),otros:tomar("OTROS",()=>true)};
 const esperadoFuera=sum(fueraBloques,"montoPlan"),verificadoFuera=sum(fueraBloques,"montoVerificado"),diferenciaEsperado=n(resumenGeneral.montoEsperado-resumen.montoTeorico),diferenciaVerificado=n(resumenGeneral.montoVerificado-resumen.montoVerificado);
 const fueraRetirados=fueraBloques.filter(p=>p.participacion==="RETIRADO"),fueraSinBloque=fueraBloques.filter(p=>p.participacion!=="RETIRADO"&&p.estadoFraterno!=="SIN FRATERNO"),fueraOtros=fueraBloques.filter(p=>p.participacion!=="RETIRADO"&&p.estadoFraterno==="SIN FRATERNO");
 const reconciliacion={esperado:{general:resumenGeneral.montoEsperado,bloques:resumen.montoTeorico,diferencia:diferenciaEsperado,detalleExplicado:esperadoFuera,noExplicada:n(diferenciaEsperado-esperadoFuera)},verificado:{general:resumenGeneral.montoVerificado,bloques:resumen.montoVerificado,diferencia:diferenciaVerificado,detalleExplicado:verificadoFuera,noExplicada:n(diferenciaVerificado-verificadoFuera),desglose:{obligadosConBloque:resumen.montoVerificadoObligados,exentosConBloque:resumen.montoVerificadoExentos,sinBloqueActivo:sum(fueraSinBloque,"montoVerificado"),retirados:sum(fueraRetirados,"montoVerificado"),otros:sum(fueraOtros,"montoVerificado")}}};
 const totalDesgloseFaltante=n(Object.values(desgloseFaltante).reduce((a:any,x:any)=>a+x.monto,0));
 return{generadoEn:new Date(),gestion:{_id:gestion._id,nombre:gestion.nombre,anio:gestion.anio},resumenGeneral,resumen,desgloseFaltante:{...desgloseFaltante,total:totalDesgloseFaltante,noExplicado:n(resumen.saldoPorCobrar-totalDesgloseFaltante)},porBloque,personas,fueraBloques,resumenFuera:{personas:fueraBloques.length,montoEsperado:esperadoFuera,montoVerificado:verificadoFuera,montoPendienteRevision:sum(fueraBloques,"montoPendienteRevision"),registrosVerificados:fueraBloques.reduce((a,p)=>a+p.cuotasVerificadas,0),registrosPendientes:fueraBloques.reduce((a,p)=>a+p.pagosPendientes,0),retirados:fueraRetirados.length,sinBloqueActivo:fueraSinBloque.length,otros:fueraOtros.length},reconciliacion,inconsistencias,validaciones:{personas:resumen.internos+resumen.externos+resumen.sinClasificar===resumen.personas,montoTeorico:n(resumen.montoInternos+resumen.montoExternos)===resumen.montoTeorico,montoReal:n(resumen.montoTeorico-resumen.montoExento)===resumen.montoRealEsperado,bloquesPersonas:porBloque.reduce((a,b)=>a+b.personas,0)===resumen.personas,bloquesEsperado:n(porBloque.reduce((a,b)=>a+b.montoRealEsperado,0))===resumen.montoRealEsperado,bloquesVerificado:n(porBloque.reduce((a,b)=>a+b.montoVerificado,0))===resumen.montoVerificado,reconciliacionEsperado:reconciliacion.esperado.noExplicada===0,reconciliacionVerificado:reconciliacion.verificado.noExplicada===0,desgloseFaltante:n(resumen.saldoPorCobrar-totalDesgloseFaltante)===0}};
}
