import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import { useAuth } from "@/hooks/useAuth";
import { updatePasswordPerfilUsuario } from "@/api/PerfilUsuarioApi";

export default function CambiarPasswordObligatorioView() {
  const { data: usuario, isLoading } = useAuth(); const navigate=useNavigate(); const qc=useQueryClient();
  const [actual,setActual]=useState(""); const [nueva,setNueva]=useState(""); const [confirmar,setConfirmar]=useState("");
  const mutation=useMutation({mutationFn:()=>updatePasswordPerfilUsuario({id:usuario!._id,passwordActual:actual,passwordNueva:nueva}),onSuccess:async r=>{toast.success(r.message);await qc.invalidateQueries({queryKey:["usuario"]});navigate("/comunicados",{replace:true});},onError:e=>toast.error(e instanceof Error?e.message:"No se pudo cambiar la contraseña")});
  if(isLoading||!usuario)return <div className="grid min-h-screen place-items-center">Cargando...</div>;
  const noCoinciden = confirmar.length > 0 && nueva !== confirmar;
  return <main className="grid min-h-screen place-items-center bg-[#eee8dc] p-4"><form onSubmit={e=>{e.preventDefault();if(nueva!==confirmar)return toast.error("La nueva contraseña y su confirmación no son iguales. Revísalas antes de continuar.");mutation.mutate();}} className="w-full max-w-md space-y-4 rounded-3xl bg-white p-7 shadow-xl"><div><p className="text-xs font-bold uppercase tracking-widest text-[#C59A3A]">Seguridad obligatoria</p><h1 className="mt-2 text-2xl font-black text-[#841534]">Cambia tu contraseña temporal</h1><p className="mt-2 text-sm text-slate-500">Antes de continuar debes crear una contraseña personal de al menos 8 caracteres.</p></div><label className="block text-sm font-bold">Contraseña temporal<input type="password" required value={actual} onChange={e=>setActual(e.target.value)} className="mt-1 w-full rounded-xl border p-3" /></label><label className="block text-sm font-bold">Nueva contraseña<input type="password" required minLength={8} value={nueva} onChange={e=>setNueva(e.target.value)} className="mt-1 w-full rounded-xl border p-3" /></label><label className="block text-sm font-bold">Confirmar nueva contraseña<input type="password" required minLength={8} value={confirmar} onChange={e=>setConfirmar(e.target.value)} aria-invalid={noCoinciden} aria-describedby={noCoinciden ? "error-confirmacion-password" : undefined} className={`mt-1 w-full rounded-xl border p-3 ${noCoinciden ? "border-red-500 bg-red-50" : ""}`} />{noCoinciden ? <span id="error-confirmacion-password" role="alert" className="mt-2 block rounded-lg bg-red-50 p-2 text-sm font-semibold text-red-700">Las contraseñas no son iguales. Vuelve a escribir la confirmación.</span> : null}</label><button disabled={mutation.isPending || noCoinciden} className="w-full rounded-xl bg-[#841534] p-3 font-bold text-white disabled:opacity-50">{mutation.isPending?"Actualizando...":"Guardar nueva contraseña"}</button></form></main>;
}
