import type { Request, Response } from "express";
import { promises as fs } from "node:fs";
import path from "node:path";
import TallaFraterno from "../models/TallaFraterno";
import DetalleBloque from "../models/DetalleBloque";
import Guia from "../models/Guia";
import PostulanteGuia from "../models/PostulanteGuia";
import Bloque from "../models/Bloque";
type Conteo = { archivos: number; bytes: number };
async function medir(carpeta: string): Promise<Conteo> { const total={archivos:0,bytes:0};let entradas:import("node:fs").Dirent[]=[];try{entradas=await fs.readdir(carpeta,{withFileTypes:true});}catch{return total;}for(const entrada of entradas){const ruta=path.join(carpeta,entrada.name);if(entrada.isDirectory()){const sub=await medir(ruta);total.archivos+=sub.archivos;total.bytes+=sub.bytes;}else if(entrada.isFile()){const stat=await fs.stat(ruta);total.archivos++;total.bytes+=stat.size;}}return total; }
export async function estadoAlmacenamiento(_req:Request,res:Response){try{const raiz=path.resolve(process.cwd(),"public","uploads");const[total,comprobantes,perfiles,comunicados,disco]=await Promise.all([medir(raiz),medir(path.join(raiz,"bauchers")),medir(path.join(raiz,"cuentas-perfil")),medir(path.join(raiz,"comunicados")),fs.statfs(raiz)]);const totalDisco=disco.blocks*disco.bsize,disponible=disco.bavail*disco.bsize,usado=totalDisco-disponible,porcentajeUsado=totalDisco?Number((usado/totalDisco*100).toFixed(2)):0;return res.json({generadoEn:new Date(),archivos:{total:total.archivos,bytes:total.bytes,perfiles,comunicados},comprobantes:{total:comprobantes.archivos,bytes:comprobantes.bytes,promedioBytes:comprobantes.archivos?Math.round(comprobantes.bytes/comprobantes.archivos):0},disco:{totalBytes:totalDisco,usadoBytes:usado,disponibleBytes:disponible,porcentajeUsado},alerta:porcentajeUsado>=90?"CRITICA":porcentajeUsado>=80?"ADVERTENCIA":"NORMAL",nota:"La ampliación del disco se realiza desde el proveedor o sistema operativo del servidor."});}catch(e){console.error(e);return res.status(500).json({error:"No se pudo medir el almacenamiento"});}}
export async function reporteTallas(_req:Request,res:Response){const tallas=await TallaFraterno.find().populate("usuarioId","nombres apellidoPaterno apellidoMaterno ci telefono").populate({path:"fraternoId",populate:{path:"usuarioId",select:"nombres apellidoPaterno apellidoMaterno ci telefono"}}).lean();const ids=tallas.map((t:any)=>t.fraternoId?._id).filter(Boolean);const posiciones=await DetalleBloque.find({fraternoId:{$in:ids}}).populate("bloqueId","nombre").lean();const mapa=new Map(posiciones.map((p:any)=>[String(p.fraternoId),p]));return res.json({registros:tallas.map((t:any)=>{const f=t.fraternoId,u=f?.usuarioId||t.usuarioId,p=mapa.get(String(f?._id))as any;return{fraternoId:f?._id||`usuario-${u?._id}`,nombres:u?.nombres,apellidoPaterno:u?.apellidoPaterno,apellidoMaterno:u?.apellidoMaterno,nombre:[u?.nombres,u?.apellidoPaterno,u?.apellidoMaterno].filter(Boolean).join(" "),ci:u?.ci,telefono:u?.telefono,tallaPolera:t.tallaPolera,tallaChamarra:t.tallaChamarra,bloque:p?.bloqueId?.nombre||"SIN BLOQUE",bloqueId:p?.bloqueId?._id};})});}
