import type { Request, Response } from "express";
import PostulanteGuia from "../models/PostulanteGuia";
import MeritoGuia from "../models/MeritoGuia";
import Preregistro from "../models/Preregistro";
import { registrarAuditoria } from "../services/AuditoriaService";

const poblar = [{ path: "preregistroId", populate: [{ path: "usuarioId", select: "nombres apellidoPaterno apellidoMaterno ci email fotoPerfil" }, { path: "gestionId", select: "nombre anio" }] }, { path: "usuarioHabilitador", select: "nombres apellidoPaterno" }];
const recalcularMeritos = async (id: string) => {
  const suma = await MeritoGuia.aggregate([{ $match: { postulanteGuiaId: new (await import("mongoose")).default.Types.ObjectId(id), verificado: true, fechaEliminado: null } }, { $group: { _id: null, total: { $sum: "$puntos" } } }]);
  const postulante = await PostulanteGuia.findById(id); if (postulante) { postulante.puntajeMeritos = suma[0]?.total ?? 0; await postulante.save(); }
};
export const listarPostulantesGuia = async (req: Request, res: Response) => { const filtro: Record<string, unknown> = { fechaEliminado: null }; if (req.query.estado) filtro.estado = req.query.estado; const postulantes = await PostulanteGuia.find(filtro).populate(poblar).sort({ puntajeTotal: -1 }); res.json({ postulantes }); };
export const obtenerPostulanteGuia = async (req: Request, res: Response) => { const postulante = await PostulanteGuia.findOne({ _id: req.params.id, fechaEliminado: null }).populate(poblar); if (!postulante) return res.status(404).json({ error: "Postulante a guía no encontrado" }); const meritos = await MeritoGuia.find({ postulanteGuiaId: postulante._id, fechaEliminado: null }).sort({ fechaCreado: -1 }); return res.json({ postulante, meritos }); };
export const habilitarPostulanteGuia = async (req: Request, res: Response) => { try { const preregistro = await Preregistro.findOne({ _id: req.body.preregistroId, fechaEliminado: null }); if (!preregistro) return res.status(404).json({ error: "Preregistro no encontrado" }); const existente = await PostulanteGuia.findOne({ preregistroId: preregistro._id }); if (existente && !existente.fechaEliminado) return res.status(409).json({ error: "El preregistro ya está habilitado como postulante a guía" }); const postulante = existente ? await PostulanteGuia.findByIdAndUpdate(existente._id, { habilitado: true, estado: "HABILITADO", fechaHabilitacion: new Date(), usuarioHabilitador: req.usuario?._id, fechaEliminado: null, usuarioEliminador: null, fechaEditado: new Date(), usuarioEditor: req.usuario?._id }, { new: true, runValidators: true }) : await PostulanteGuia.create({ preregistroId: preregistro._id, usuarioHabilitador: req.usuario?._id, usuarioCreador: req.usuario?._id, habilitado: true }); await postulante!.populate(poblar); await registrarAuditoria(req, { accion: "HABILITAR", modulo: "GUIAS", entidad: "PostulanteGuia", entidadId: postulante!._id, descripcion: "Se habilitó un postulante a guía", datosDespues: postulante!.toObject() }); return res.status(201).json({ message: "Postulante habilitado", postulante }); } catch (e) { if ((e as { code?: number }).code === 11000) return res.status(409).json({ error: "El preregistro ya está habilitado como postulante a guía" }); return res.status(500).json({ error: "No se pudo habilitar al postulante" }); } };
export const habilitarPostulanteGuiaPorUsuario = async (req: Request, res: Response) => {
  const preregistro = await Preregistro.findOne({ usuarioId: req.params.usuarioId, fechaEliminado: null, estado: "APROBADO" }).sort({ fechaRegistro: -1 });
  if (!preregistro) return res.status(409).json({ error: "El preregistro debe estar APROBADO antes de nombrar a la persona postulante a guía" });
  req.body = { ...(req.body ?? {}), preregistroId: String(preregistro._id) };
  return habilitarPostulanteGuia(req, res);
};
export const retirarPostulanteGuia = async (req: Request, res: Response) => {
  const postulante = await PostulanteGuia.findOne({ _id: req.params.id, fechaEliminado: null });
  if (!postulante) return res.status(404).json({ error: "Postulante a guía no encontrado" });
  if (["ELEGIDO", "NO_ELEGIDO"].includes(postulante.estado)) return res.status(409).json({ error: "No se puede retirar porque ya fue convertido en guía o fraterno" });
  const antes = postulante.toObject();
  postulante.estado = "RETIRADO"; postulante.habilitado = false; postulante.fechaEliminado = new Date(); postulante.usuarioEliminador = req.usuario?._id as any;
  await postulante.save();
  await registrarAuditoria(req, { accion: "RETIRAR", modulo: "GUIAS", entidad: "PostulanteGuia", entidadId: postulante._id, descripcion: "Se retiró al usuario de postulantes a guía", datosAntes: antes, datosDespues: postulante.toObject() });
  return res.json({ message: "Postulante retirado de la lista de candidatos" });
};
export const actualizarPostulanteGuia = async (req: Request, res: Response) => { const anterior = await PostulanteGuia.findById(req.params.id).lean(); const campos = ["habilitado", "estado", "iniciativaDescripcion", "puntajeIniciativa", "organizaBloque", "bloqueOrganizado", "organizacionDescripcion", "puntajeOrganizacion", "puntajeEleccion", "observacion"]; const cambios = Object.fromEntries(campos.filter((c) => req.body[c] !== undefined).map((c) => [c, req.body[c]])); const postulante = await PostulanteGuia.findOneAndUpdate({ _id: req.params.id, fechaEliminado: null }, { $set: { ...cambios, fechaEditado: new Date(), usuarioEditor: req.usuario?._id, ...(req.body.estado === "ELEGIDO" ? { fechaEleccion: new Date(), usuarioEvaluador: req.usuario?._id } : {}) } }, { new: true, runValidators: true }).populate(poblar); if (!postulante) return res.status(404).json({ error: "Postulante no encontrado" }); await postulante.save(); await registrarAuditoria(req, { accion: "ACTUALIZAR", modulo: "GUIAS", entidad: "PostulanteGuia", entidadId: postulante._id, descripcion: "Se actualizó la evaluación de guía", datosAntes: anterior, datosDespues: postulante.toObject() }); return res.json({ message: "Postulante actualizado", postulante }); };
export const agregarMerito = async (req: Request, res: Response) => { const postulanteId = String(req.params.id); const merito = await MeritoGuia.create({ ...req.body, postulanteGuiaId: postulanteId, usuarioCreador: req.usuario?._id, usuarioVerificador: req.usuario?._id }); await recalcularMeritos(postulanteId); await registrarAuditoria(req, { accion: "CREAR", modulo: "GUIAS", entidad: "MeritoGuia", entidadId: merito._id, descripcion: `Se registró el mérito ${merito.titulo}`, datosDespues: merito.toObject() }); res.status(201).json({ message: "Mérito registrado", merito }); };
export const eliminarMerito = async (req: Request, res: Response) => { const postulanteId = String(req.params.id); const merito = await MeritoGuia.findOneAndUpdate({ _id: req.params.meritoId, postulanteGuiaId: postulanteId, fechaEliminado: null }, { fechaEliminado: new Date(), usuarioEliminador: req.usuario?._id }, { new: true }); if (!merito) return res.status(404).json({ error: "Mérito no encontrado" }); await recalcularMeritos(postulanteId); await registrarAuditoria(req, { accion: "ELIMINAR", modulo: "GUIAS", entidad: "MeritoGuia", entidadId: merito._id, descripcion: "Se eliminó un mérito" }); return res.json({ message: "Mérito eliminado" }); };
