import { Router } from "express"; import { body, param, query } from "express-validator"; import { authenticate } from "../middleware/auth"; import { soloAdministracion, soloAdministradorReal } from "../middleware/soloAdministracion"; import { authorizePermission } from "../middleware/authorizePermission"; import { handleInputErrors } from "../middleware/validation"; import { asignarEnMiBloque, asignarIntegrante, buscarCandidatoGuia, buscarFraternosParaMiBloque, buscarUsuariosParaBloqueComoAdmin, convertirFraternoEnGuia, crearBloque, decidirPostulante, designarGuia, eliminarBloqueComoAdmin, listarGuias, moverGuiaComoAdmin, obtenerDirectorioBloques, obtenerMiBloque, quitarIntegranteComoAdmin, quitarRolGuiaComoAdmin, registrarFraternoEnBloqueComoAdmin, registrarFraternoEnMiBloque, renombrarBloqueComoAdmin, renombrarMiBloque } from "../controllers/GuiaController";
const r=Router();
r.get("/mi-bloque",authenticate,authorizePermission("VISTA_MI_BLOQUE_GUIA"),obtenerMiBloque);
r.get("/mi-bloque/buscar-fraternos",authenticate,authorizePermission("BLOQUES_PROPIOS_GESTIONAR"),query("buscar").trim().isLength({min:2,max:100}),handleInputErrors,buscarFraternosParaMiBloque);
r.post("/mi-bloque/registrar-fraterno",authenticate,authorizePermission("BLOQUES_PROPIOS_GESTIONAR"),body("usuarioId").isMongoId(),handleInputErrors,registrarFraternoEnMiBloque);
r.get("/directorio-bloques",authenticate,authorizePermission("VISTA_DIRECTORIO_BLOQUES"),obtenerDirectorioBloques);
r.patch("/mi-bloque/nombre",authenticate,authorizePermission("BLOQUES_PROPIOS_GESTIONAR"),body("nombre").trim().notEmpty(),handleInputErrors,renombrarMiBloque);
r.post("/mi-bloque/integrantes",authenticate,authorizePermission("BLOQUES_PROPIOS_GESTIONAR"),body("bloqueId").isMongoId(),body("fraternoId").isMongoId(),handleInputErrors,asignarEnMiBloque);
r.use(authenticate,soloAdministracion); r.get("/",listarGuias); r.get("/candidato",soloAdministradorReal,query("ci").trim().notEmpty(),handleInputErrors,buscarCandidatoGuia); r.post("/",soloAdministradorReal,body("postulanteGuiaId").isMongoId(),handleInputErrors,designarGuia); r.post("/convertir-fraterno",soloAdministradorReal,body("ci").optional().trim().notEmpty(),body("fraternoId").optional().isMongoId(),handleInputErrors,convertirFraternoEnGuia); r.post("/postulantes/:id/decision",soloAdministradorReal,param("id").isMongoId(),body("decision").isIn(["GUIA","FRATERNO"]),handleInputErrors,decidirPostulante); r.patch("/bloques/guias/:guiaId",soloAdministradorReal,param("guiaId").isMongoId(),body("bloqueId").optional({nullable:true}).isMongoId(),body("confirmarMovimiento").optional().isBoolean(),handleInputErrors,moverGuiaComoAdmin); r.delete("/:guiaId/rol",soloAdministradorReal,param("guiaId").isMongoId(),handleInputErrors,quitarRolGuiaComoAdmin); r.post("/bloques",soloAdministradorReal,body("guiaId").optional({nullable:true}).isMongoId(),body("gestionId").optional({nullable:true}).isMongoId(),body("nombre").trim().isLength({min:2,max:100}),handleInputErrors,crearBloque); r.get("/bloques/buscar-usuarios",soloAdministradorReal,query("bloqueId").isMongoId(),query("buscar").trim().isLength({min:2,max:100}),handleInputErrors,buscarUsuariosParaBloqueComoAdmin); r.post("/bloques/registrar-fraterno",soloAdministradorReal,body("bloqueId").isMongoId(),body("usuarioId").isMongoId(),handleInputErrors,registrarFraternoEnBloqueComoAdmin); r.patch("/bloques/:bloqueId/nombre",soloAdministradorReal,param("bloqueId").isMongoId(),body("nombre").trim().isLength({min:2,max:100}),handleInputErrors,renombrarBloqueComoAdmin); r.delete("/bloques/:bloqueId",soloAdministradorReal,param("bloqueId").isMongoId(),handleInputErrors,eliminarBloqueComoAdmin); r.post("/bloques/integrantes",soloAdministradorReal,body("bloqueId").isMongoId(),body("fraternoId").isMongoId(),handleInputErrors,asignarIntegrante); r.delete("/bloques/integrantes/:detalleId",soloAdministradorReal,param("detalleId").isMongoId(),handleInputErrors,quitarIntegranteComoAdmin); export default r;
