import { Router } from "express";
import { body, param } from "express-validator";
import { authenticate } from "../middleware/auth";
import { soloAdministracion } from "../middleware/soloAdministracion";
import { handleInputErrors } from "../middleware/validation";
import { cambiarBloqueoTalla, cambiarEstadoEntrega, configurarRegistroTallas, crearPrenda, entregar, guardarMiTalla, guardarTalla, guardarTallaUsuario, miIndumentaria, resumenIndumentaria } from "../controllers/IndumentariaController";
const router = Router();
router.get("/mia", authenticate, miIndumentaria);
router.put("/mia/tallas", authenticate, body("tallaPolera").trim().notEmpty(), body("tallaChamarra").trim().notEmpty(), handleInputErrors, guardarMiTalla);
router.use(authenticate, soloAdministracion);
router.get("/", resumenIndumentaria);
router.put("/configuracion-tallas", body("habilitado").isBoolean(), body("sinFechaLimite").isBoolean(), body("fechaLimite").optional({ nullable: true, checkFalsy: true }).isISO8601(), handleInputErrors, configurarRegistroTallas);
router.put("/tallas", body("fraternoId").isMongoId(), body("tallaPolera").trim().notEmpty(), body("tallaChamarra").trim().notEmpty(), handleInputErrors, guardarTalla);
router.put("/tallas/usuario", body("usuarioId").isMongoId(), body("tallaPolera").trim().notEmpty(), body("tallaChamarra").trim().notEmpty(), handleInputErrors, guardarTallaUsuario);
router.patch("/tallas/:fraternoId/bloqueo", param("fraternoId").isMongoId(), body("bloqueada").isBoolean(), handleInputErrors, cambiarBloqueoTalla);
router.post("/prendas", body("nombre").trim().notEmpty(), handleInputErrors, crearPrenda);
router.post("/entregas", body("fraternoId").isMongoId(), body("prendaId").isMongoId(), body("cantidad").optional().isInt({ min: 1 }).toInt(), handleInputErrors, entregar);
router.patch("/entregas/:id", param("id").isMongoId(), body("estado").isIn(["ENTREGADO", "DEVUELTO", "PERDIDO", "DANADO"]), handleInputErrors, cambiarEstadoEntrega);
export default router;
