import { Router } from "express";
import { body, param } from "express-validator";
import { authenticate } from "../middleware/auth";
import { soloAdministracion } from "../middleware/soloAdministracion";
import { handleInputErrors } from "../middleware/validation";
import { anularToken, generarToken, guardarConfiguracionTokens, listarTokens, obtenerConfiguracionTokens, validarTokenPublico } from "../controllers/TokenRegistroController";
const r = Router();
r.post("/validar", body("codigo").trim().notEmpty(), handleInputErrors, validarTokenPublico);
r.get("/configuracion", authenticate, soloAdministracion, obtenerConfiguracionTokens);
r.put("/configuracion", authenticate, soloAdministracion, body("gestionId").isMongoId(), body("cupoMaximoHombres").isInt({ min: 0 }).toInt(), body("cupoMaximoMujeres").isInt({ min: 0 }).toInt(), body("tarifaInterno").isFloat({ min: .01 }).toFloat(), body("tarifaExterno").isFloat({ min: .01 }).toFloat(), body("primeraCuota").isFloat({ min: .01 }).toFloat(), body("vigenciaTokenHoras").isInt({ min: 1, max: 8760 }).toInt(), body("plazoPrimeraCuotaHoras").isInt({ min: 1, max: 8760 }).toInt(), body("cantidadBloques").isInt({ min: 1, max: 100 }).toInt(), handleInputErrors, guardarConfiguracionTokens);
r.get("/", authenticate, soloAdministracion, listarTokens);
r.post("/", authenticate, soloAdministracion, body("gestionId").isMongoId(), body("vigenciaHoras").optional().isInt({ min: 1, max: 8760 }).toInt(), body("plazoPagoHoras").optional().isInt({ min: 1, max: 8760 }).toInt(), handleInputErrors, generarToken);
r.patch("/:id/anular", authenticate, soloAdministracion, param("id").isMongoId(), handleInputErrors, anularToken);
export default r;
