import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import { crearCuota, habilitarCuotasMasivas, listarCuotas, prorrogarCuotasVencidas } from "@/api/CuotaApi";
import { obtenerPreregistros } from "@/api/PreregistroApi";
import ConfiguracionQrPago from "@/components/cuota/ConfiguracionQrPago";
import { useAuth } from "@/hooks/useAuth";

export default function CuotaView() {
  const { data: usuario } = useAuth();
  const roles = Array.isArray(usuario?.roles) ? usuario.roles.filter((rol) => typeof rol === "object" && rol) : [];
  const esAdministrador = roles.some((rol) => [rol.codigo, rol.nombre].some((valor) => String(valor ?? "").toUpperCase().replace(/[\s_-]/g, "") === "ADMINISTRADOR"));
  const permisos = new Set(roles.flatMap((rol) => rol.permisos ?? []));
  const puedeConfigurar = esAdministrador || permisos.has("PAGOS_CONFIGURAR");
  const puedeGestionar = esAdministrador || permisos.has("PAGOS_GESTIONAR");
  const nav = useNavigate(); const qc = useQueryClient();
  const [buscar, setBuscar] = useState(""); const [limite, setLimite] = useState(() => window.innerWidth < 640 ? 5 : 20); const [pagina, setPagina] = useState(1);
  const [config, setConfig] = useState({ tarifaInterno: 750, tarifaExterno: 850, fechaVencimiento: "" });
  const [prorrogaGeneral, setProrrogaGeneral] = useState({ horas: 24, motivo: "Habilitación general autorizada por administración" });
  const q = useQuery({ queryKey: ["cuotas"], queryFn: listarCuotas });
  const preregistrosQuery = useQuery({ queryKey: ["preregistros", "cuotas-faltantes"], queryFn: () => obtenerPreregistros({ limite: 1000 }), enabled: puedeGestionar });
  const habilitar = useMutation({
    mutationFn: habilitarCuotasMasivas,
    onSuccess: async (resultado) => {
      toast.success(`Proceso completado: ${resultado.creadas} cuotas creadas y ${resultado.yaExistentes} ya existentes`);
      await qc.invalidateQueries({ queryKey: ["cuotas"] });
    },
    onError: (error) => toast.error(error instanceof Error ? error.message : "No se pudo completar el proceso"),
  });
  const ampliarVencidas = useMutation({ mutationFn: prorrogarCuotasVencidas, onSuccess: async (resultado) => { toast.success(resultado.message); await qc.invalidateQueries({ queryKey: ["cuotas"] }); }, onError: (error) => toast.error(error instanceof Error ? error.message : "No se pudo ampliar el plazo") });
  const crearIndividual = useMutation({ mutationFn: ({ preregistroId }: { preregistroId: string; montoTotal: number }) => crearCuota({ preregistroId, fechaVencimiento: config.fechaVencimiento || undefined, observacion: "Cuota vinculada individualmente por Administración" }), onSuccess: async () => { toast.success("Cuota vinculada con la tarifa de su origen"); await qc.invalidateQueries({ queryKey: ["cuotas"] }); }, onError: (error) => toast.error(error instanceof Error ? error.message : "No se pudo crear la cuota") });
  const idsConCuota = new Set((q.data ?? []).map((cuota) => cuota.preregistroId._id));
  const preregistrosSinCuota = (preregistrosQuery.data?.preregistros ?? []).filter((preregistro) => preregistro.estado === "APROBADO" && preregistro.aprobado && !idsConCuota.has(preregistro._id));
  const preregistrosObservados = (preregistrosQuery.data?.preregistros ?? []).filter((preregistro) => preregistro.estado === "OBSERVADO" && !idsConCuota.has(preregistro._id));
  const cuotasVencidas = (q.data ?? []).filter((cuota) => cuota.saldo > 0 && Boolean(cuota.fechaVencimiento && new Date(cuota.fechaVencimiento) < new Date()) && !["PAGADA", "CANCELADA"].includes(cuota.estado));
  const filtradas = (q.data ?? []).filter((cuota) => { const usuario = cuota.preregistroId.usuarioId; return `${cuota.preregistroId.numeroPreRegistro} ${usuario?.nombres ?? ""} ${usuario?.apellidoPaterno ?? ""} ${usuario?.ci ?? ""} ${cuota.estado} ${cuota.tipoOrigenTarifa ?? ""}`.toLowerCase().includes(buscar.toLowerCase()); });
  const paginas = Math.max(1, Math.ceil(filtradas.length / limite)); const paginaSegura = Math.min(pagina, paginas); const visibles = filtradas.slice((paginaSegura - 1) * limite, paginaSegura * limite);
  return <div className="space-y-6">
    <header><p className="text-xs font-bold uppercase tracking-widest text-[#8F5F2A]">Administración de pagos</p><h1 className="text-3xl font-black text-[#74122A]">Cuotas</h1><p className="text-sm text-[#735f55]">Habilitación masiva, pagos parciales, saldo y revisión de bauchers.</p></header>
    {puedeConfigurar ? <ConfiguracionQrPago /> : null}
    {puedeGestionar ? <><section className="rounded-2xl border border-amber-300 bg-amber-50 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black text-[#74122A]">Nuevo plazo general para cuotas vencidas</h2><p className="mt-1 max-w-3xl text-sm text-amber-900">Aplica a todos los usuarios vencidos, hayan elegido un plan de 1, 2 o 3 cuotas. Habilita el próximo pago pendiente sin cambiar el plan elegido.</p></div><span className="rounded-full bg-amber-200 px-4 py-2 text-sm font-black text-amber-950">{cuotasVencidas.length} vencida(s)</span></div><div className="mt-4 grid gap-3 sm:grid-cols-[180px_1fr_auto]"><input type="number" min="1" max="8760" value={prorrogaGeneral.horas} onChange={(e) => setProrrogaGeneral({ ...prorrogaGeneral, horas: Number(e.target.value) })} className="input-preregistro" aria-label="Horas de ampliación"/><input value={prorrogaGeneral.motivo} onChange={(e) => setProrrogaGeneral({ ...prorrogaGeneral, motivo: e.target.value })} className="input-preregistro" aria-label="Motivo de ampliación"/><button type="button" disabled={!cuotasVencidas.length || ampliarVencidas.isPending || prorrogaGeneral.motivo.trim().length < 3} onClick={() => confirm(`¿Dar ${prorrogaGeneral.horas} horas a las ${cuotasVencidas.length} cuotas vencidas?`) && ampliarVencidas.mutate(prorrogaGeneral)} className="rounded-xl bg-[#74122A] px-5 py-3 font-bold text-white disabled:opacity-50">{ampliarVencidas.isPending ? "Habilitando..." : "Dar nuevo plazo a todas"}</button></div></section>
    <section className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black text-[#74122A]">Aprobados sin cuota</h2><p className="mt-1 text-sm text-blue-900">Estos usuarios fueron dados de alta y aprobados, pero todavía no tienen una cuota. Puedes crearla individualmente con la tarifa interna o externa configurada abajo.</p></div><span className="rounded-full bg-blue-200 px-4 py-2 text-sm font-black text-blue-950">{preregistrosSinCuota.length} pendiente(s)</span></div>{preregistrosSinCuota.length ? <div className="mt-4 grid gap-3 lg:grid-cols-2">{preregistrosSinCuota.map((preregistro) => { const persona = typeof preregistro.usuarioId === "object" ? preregistro.usuarioId : null; return <article key={preregistro._id} className="rounded-xl border border-blue-200 bg-white p-4"><strong>{persona?.nombres} {persona?.apellidoPaterno}</strong><p className="text-xs text-slate-500">CI {persona?.ci} · {preregistro.numeroPreRegistro}</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={crearIndividual.isPending} onClick={() => crearIndividual.mutate({ preregistroId: preregistro._id, montoTotal: config.tarifaInterno })} className="rounded-lg bg-[#74122A] px-3 py-2 text-xs font-bold text-white">Crear interna · Bs {config.tarifaInterno}</button><button type="button" disabled={crearIndividual.isPending} onClick={() => crearIndividual.mutate({ preregistroId: preregistro._id, montoTotal: config.tarifaExterno })} className="rounded-lg border border-[#74122A] px-3 py-2 text-xs font-bold text-[#74122A]">Crear externa · Bs {config.tarifaExterno}</button></div></article>; })}</div> : <p className="mt-4 rounded-xl bg-white p-4 text-sm font-bold text-emerald-700">Todos los aprobados ya tienen cuota.</p>}{preregistrosObservados.length ? <details className="mt-4 rounded-xl border border-orange-200 bg-orange-50 p-4"><summary className="cursor-pointer font-black text-orange-900">{preregistrosObservados.length} observado(s) sin cuota — ver motivos</summary><div className="mt-3 space-y-2">{preregistrosObservados.map((preregistro) => { const persona = typeof preregistro.usuarioId === "object" ? preregistro.usuarioId : null; return <p key={preregistro._id} className="rounded-lg bg-white p-3 text-sm"><strong>{persona?.nombres} {persona?.apellidoPaterno}</strong>: {preregistro.observacion || "Sin detalle de observación"}</p>; })}</div></details> : null}</section>
    <section className="rounded-2xl border border-[#d3c9bb] bg-white p-5 shadow-sm"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-xl font-black text-[#74122A]">Habilitar cuotas para todos</h2><p className="mt-1 max-w-2xl text-sm text-slate-500">Se crearán únicamente las cuotas faltantes tomando el tipo de origen del perfil. Las cuotas existentes no se duplican ni se modifican.</p></div><span className="rounded-full bg-[#C59A3A]/15 px-3 py-1 text-xs font-bold text-[#74122A]">Proceso seguro e idempotente</span></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><label><span className="mb-1 block text-xs font-bold uppercase text-[#735f55]">Tarifa internos FCJyT</span><input type="number" min="0.01" step="0.01" value={config.tarifaInterno} onChange={(e) => setConfig({ ...config, tarifaInterno: Number(e.target.value) })} className="input-preregistro" /></label><label><span className="mb-1 block text-xs font-bold uppercase text-[#735f55]">Tarifa externos</span><input type="number" min="0.01" step="0.01" value={config.tarifaExterno} onChange={(e) => setConfig({ ...config, tarifaExterno: Number(e.target.value) })} className="input-preregistro" /></label><label><span className="mb-1 block text-xs font-bold uppercase text-[#735f55]">Fecha de vencimiento</span><input type="date" value={config.fechaVencimiento} onChange={(e) => setConfig({ ...config, fechaVencimiento: e.target.value })} className="input-preregistro" /></label></div><button disabled={habilitar.isPending} onClick={() => { if (confirm(`¿Crear las cuotas faltantes?\nInternos: Bs ${config.tarifaInterno}\nExternos: Bs ${config.tarifaExterno}`)) habilitar.mutate({ ...config, fechaVencimiento: config.fechaVencimiento || undefined }); }} className="mt-4 w-full rounded-xl bg-[#74122A] px-5 py-3 font-bold text-white disabled:opacity-60">{habilitar.isPending ? "Generando cuotas..." : "Habilitar cuotas para todos los preregistros"}</button></section></> : null}
    <section className="grid gap-3 rounded-2xl bg-white p-4 sm:grid-cols-[1fr_auto]"><input type="search" value={buscar} onChange={(e) => { setBuscar(e.target.value); setPagina(1); }} className="input-preregistro" placeholder="Buscar nombre, CI, preregistro, origen o estado..." /><select value={limite} onChange={(e) => { setLimite(Number(e.target.value)); setPagina(1); }} className="input-preregistro">{[5, 10, 20, 50, 100].map((cantidad) => <option key={cantidad} value={cantidad}>{cantidad} filas</option>)}</select></section>
    <div className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-[#74122A] text-white"><tr>{["Preregistro", "Postulante", "Origen", "Total", "Pagado", "Saldo", "Estado", "Acción"].map((titulo) => <th key={titulo} className="p-4">{titulo}</th>)}</tr></thead><tbody>{visibles.map((cuota) => { const usuario = cuota.preregistroId.usuarioId; return <tr key={cuota._id} className="border-b"><td className="p-4 font-bold text-[#74122A]">{cuota.preregistroId.numeroPreRegistro}</td><td className="p-4"><strong>{usuario?.nombres} {usuario?.apellidoPaterno}</strong><p className="text-xs text-slate-500">{usuario?.ci}</p></td><td className="p-4"><span className="rounded-full bg-[#C59A3A]/15 px-3 py-1 text-xs font-bold text-[#74122A]">{cuota.tipoOrigenTarifa ?? "SIN DATO"}</span></td><td className="p-4">Bs {cuota.montoTotal.toFixed(2)}</td><td className="p-4 text-emerald-700">Bs {cuota.montoPagado.toFixed(2)}</td><td className="p-4 font-bold">Bs {cuota.saldo.toFixed(2)}</td><td className="p-4">{cuota.estado.replace("_", " ")}</td><td className="p-4"><button onClick={() => nav(`/cuotas/${cuota._id}`)} className="rounded-lg bg-blue-100 px-3 py-2 font-bold text-blue-700">Pagos y bauchers</button></td></tr>; })}</tbody></table></div><footer className="flex items-center justify-between border-t p-4 text-sm"><span>Página {paginaSegura} de {paginas} · {filtradas.length} cuotas</span><div className="flex gap-2"><button disabled={paginaSegura === 1} onClick={() => setPagina(paginaSegura - 1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Anterior</button><button disabled={paginaSegura === paginas} onClick={() => setPagina(paginaSegura + 1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Siguiente</button></div></footer></div>
  </div>;
}
