import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import { habilitarCuotasMasivas, listarCuotas, prorrogarCuotasVencidas } from "@/api/CuotaApi";
import ConfiguracionQrPago from "@/components/cuota/ConfiguracionQrPago";

export default function CuotaView() {
  const nav = useNavigate(); const qc = useQueryClient();
  const [buscar, setBuscar] = useState(""); const [limite, setLimite] = useState(() => window.innerWidth < 640 ? 5 : 20); const [pagina, setPagina] = useState(1);
  const [config, setConfig] = useState({ tarifaInterno: 750, tarifaExterno: 850, fechaVencimiento: "" });
  const [prorrogaGeneral, setProrrogaGeneral] = useState({ horas: 24, motivo: "Habilitación general autorizada por administración" });
  const q = useQuery({ queryKey: ["cuotas"], queryFn: listarCuotas });
  const habilitar = useMutation({
    mutationFn: habilitarCuotasMasivas,
    onSuccess: async (resultado) => {
      toast.success(`Proceso completado: ${resultado.creadas} cuotas creadas y ${resultado.yaExistentes} ya existentes`);
      await qc.invalidateQueries({ queryKey: ["cuotas"] });
    },
    onError: (error) => toast.error(error instanceof Error ? error.message : "No se pudo completar el proceso"),
  });
  const ampliarVencidas = useMutation({ mutationFn: prorrogarCuotasVencidas, onSuccess: async (resultado) => { toast.success(resultado.message); await qc.invalidateQueries({ queryKey: ["cuotas"] }); }, onError: (error) => toast.error(error instanceof Error ? error.message : "No se pudo ampliar el plazo") });
  const filtradas = (q.data ?? []).filter((cuota) => { const usuario = cuota.preregistroId.usuarioId; return `${cuota.preregistroId.numeroPreRegistro} ${usuario?.nombres ?? ""} ${usuario?.apellidoPaterno ?? ""} ${usuario?.ci ?? ""} ${cuota.estado} ${cuota.tipoOrigenTarifa ?? ""}`.toLowerCase().includes(buscar.toLowerCase()); });
  const paginas = Math.max(1, Math.ceil(filtradas.length / limite)); const paginaSegura = Math.min(pagina, paginas); const visibles = filtradas.slice((paginaSegura - 1) * limite, paginaSegura * limite);
  return <div className="space-y-6">
    <header><p className="text-xs font-bold uppercase tracking-widest text-[#8F5F2A]">Administración de pagos</p><h1 className="text-3xl font-black text-[#74122A]">Cuotas</h1><p className="text-sm text-[#735f55]">Habilitación masiva, pagos parciales, saldo y revisión de bauchers.</p></header>
    <ConfiguracionQrPago />
    <section className="rounded-2xl border border-amber-300 bg-amber-50 p-5"><h2 className="text-xl font-black text-[#74122A]">Habilitar todas las cuotas vencidas</h2><p className="mt-1 text-sm text-amber-900">Otorga un nuevo plazo a quienes no pudieron registrar su siguiente pago. Los fraternos conservan siempre su cupo; quienes vencieron antes de la primera cuota continúan en lista de espera.</p><div className="mt-4 grid gap-3 sm:grid-cols-[180px_1fr_auto]"><input type="number" min="1" max="8760" value={prorrogaGeneral.horas} onChange={(e) => setProrrogaGeneral({ ...prorrogaGeneral, horas: Number(e.target.value) })} className="input-preregistro" aria-label="Horas de ampliación"/><input value={prorrogaGeneral.motivo} onChange={(e) => setProrrogaGeneral({ ...prorrogaGeneral, motivo: e.target.value })} className="input-preregistro" aria-label="Motivo de ampliación"/><button type="button" disabled={ampliarVencidas.isPending || prorrogaGeneral.motivo.trim().length < 3} onClick={() => confirm("¿Habilitar un nuevo plazo para todas las cuotas vencidas?") && ampliarVencidas.mutate(prorrogaGeneral)} className="rounded-xl bg-[#74122A] px-5 py-3 font-bold text-white disabled:opacity-50">{ampliarVencidas.isPending ? "Habilitando..." : "Habilitar vencidas"}</button></div></section>
    <section className="rounded-2xl border border-[#d3c9bb] bg-white p-5 shadow-sm"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-xl font-black text-[#74122A]">Habilitar cuotas para todos</h2><p className="mt-1 max-w-2xl text-sm text-slate-500">Se crearán únicamente las cuotas faltantes tomando el tipo de origen del perfil. Las cuotas existentes no se duplican ni se modifican.</p></div><span className="rounded-full bg-[#C59A3A]/15 px-3 py-1 text-xs font-bold text-[#74122A]">Proceso seguro e idempotente</span></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><label><span className="mb-1 block text-xs font-bold uppercase text-[#735f55]">Tarifa internos FCJyT</span><input type="number" min="0.01" step="0.01" value={config.tarifaInterno} onChange={(e) => setConfig({ ...config, tarifaInterno: Number(e.target.value) })} className="input-preregistro" /></label><label><span className="mb-1 block text-xs font-bold uppercase text-[#735f55]">Tarifa externos</span><input type="number" min="0.01" step="0.01" value={config.tarifaExterno} onChange={(e) => setConfig({ ...config, tarifaExterno: Number(e.target.value) })} className="input-preregistro" /></label><label><span className="mb-1 block text-xs font-bold uppercase text-[#735f55]">Fecha de vencimiento</span><input type="date" value={config.fechaVencimiento} onChange={(e) => setConfig({ ...config, fechaVencimiento: e.target.value })} className="input-preregistro" /></label></div><button disabled={habilitar.isPending} onClick={() => { if (confirm(`¿Crear las cuotas faltantes?\nInternos: Bs ${config.tarifaInterno}\nExternos: Bs ${config.tarifaExterno}`)) habilitar.mutate({ ...config, fechaVencimiento: config.fechaVencimiento || undefined }); }} className="mt-4 w-full rounded-xl bg-[#74122A] px-5 py-3 font-bold text-white disabled:opacity-60">{habilitar.isPending ? "Generando cuotas..." : "Habilitar cuotas para todos los preregistros"}</button></section>
    <section className="grid gap-3 rounded-2xl bg-white p-4 sm:grid-cols-[1fr_auto]"><input type="search" value={buscar} onChange={(e) => { setBuscar(e.target.value); setPagina(1); }} className="input-preregistro" placeholder="Buscar nombre, CI, preregistro, origen o estado..." /><select value={limite} onChange={(e) => { setLimite(Number(e.target.value)); setPagina(1); }} className="input-preregistro">{[5, 10, 20, 50, 100].map((cantidad) => <option key={cantidad} value={cantidad}>{cantidad} filas</option>)}</select></section>
    <div className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-[#74122A] text-white"><tr>{["Preregistro", "Postulante", "Origen", "Total", "Pagado", "Saldo", "Estado", "Acción"].map((titulo) => <th key={titulo} className="p-4">{titulo}</th>)}</tr></thead><tbody>{visibles.map((cuota) => { const usuario = cuota.preregistroId.usuarioId; return <tr key={cuota._id} className="border-b"><td className="p-4 font-bold text-[#74122A]">{cuota.preregistroId.numeroPreRegistro}</td><td className="p-4"><strong>{usuario?.nombres} {usuario?.apellidoPaterno}</strong><p className="text-xs text-slate-500">{usuario?.ci}</p></td><td className="p-4"><span className="rounded-full bg-[#C59A3A]/15 px-3 py-1 text-xs font-bold text-[#74122A]">{cuota.tipoOrigenTarifa ?? "SIN DATO"}</span></td><td className="p-4">Bs {cuota.montoTotal.toFixed(2)}</td><td className="p-4 text-emerald-700">Bs {cuota.montoPagado.toFixed(2)}</td><td className="p-4 font-bold">Bs {cuota.saldo.toFixed(2)}</td><td className="p-4">{cuota.estado.replace("_", " ")}</td><td className="p-4"><button onClick={() => nav(`/cuotas/${cuota._id}`)} className="rounded-lg bg-blue-100 px-3 py-2 font-bold text-blue-700">Pagos y bauchers</button></td></tr>; })}</tbody></table></div><footer className="flex items-center justify-between border-t p-4 text-sm"><span>Página {paginaSegura} de {paginas} · {filtradas.length} cuotas</span><div className="flex gap-2"><button disabled={paginaSegura === 1} onClick={() => setPagina(paginaSegura - 1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Anterior</button><button disabled={paginaSegura === paginas} onClick={() => setPagina(paginaSegura + 1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Siguiente</button></div></footer></div>
  </div>;
}
