import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate, useParams } from "react-router-dom";
import { toast } from "react-toastify";
import { eliminarPago, obtenerCuota, registrarPago, revisarPago } from "@/api/CuotaApi";
import type { DetalleCuota, EstadoRevisionPago, MetodoPago } from "@/types/CuotaType";
const API = String(import.meta.env.VITE_API_URL || "").replace(/\/api\/?$/, "");

export default function DetalleCuotaView() {
  const { id = "" } = useParams(); const nav = useNavigate(); const qc = useQueryClient(); const [buscar, setBuscar] = useState(""); const [estado, setEstado] = useState<EstadoRevisionPago | "">("");
  const [form, setForm] = useState<{ monto: number; metodoPago: MetodoPago; montoEfectivo: number; montoQr: number; nombrePagador: string; fechaPago: string; baucher: File | null }>({ monto: 0, metodoPago: "EFECTIVO", montoEfectivo: 0, montoQr: 0, nombrePagador: "", fechaPago: new Date().toISOString().slice(0, 10), baucher: null });
  const q = useQuery({ queryKey: ["cuota", id], queryFn: () => obtenerCuota(id) }); const refrescar = () => qc.invalidateQueries({ queryKey: ["cuota", id] });
  const registrar = useMutation({ mutationFn: () => registrarPago(id, form), onSuccess: async () => { toast.success("Pago enviado para revisión"); setForm({ ...form, monto: 0, montoEfectivo: 0, montoQr: 0, baucher: null }); await refrescar(); }, onError: (e) => toast.error(e instanceof Error ? e.message : "Error") });
  const borrar = useMutation({ mutationFn: (pagoId: string) => eliminarPago(id, pagoId), onSuccess: refrescar });
  if (!q.data) return <p>{q.isLoading ? "Cargando cuota..." : "No se encontró la cuota"}</p>;
  const { cuota } = q.data; const u = cuota.preregistroId.usuarioId; const pagos = q.data.pagos.filter((p) => (!estado || p.estadoRevision === estado) && `${p.nombrePagador} ${p.fechaPago} ${p.monto} ${p.metodoPago}`.toLowerCase().includes(buscar.toLowerCase()));
  const cambiarMetodo = (metodoPago: MetodoPago) => setForm({ ...form, metodoPago, montoEfectivo: metodoPago === "EFECTIVO" ? form.monto : 0, montoQr: metodoPago === "QR" ? form.monto : 0, baucher: metodoPago === "EFECTIVO" ? null : form.baucher });
  return <div className="space-y-6"><button onClick={() => nav(-1)} className="font-bold text-[#74122A]">← Volver</button><header className="grid gap-4 rounded-2xl bg-[#74122A] p-6 text-white sm:grid-cols-4"><div className="sm:col-span-2"><p className="text-xs uppercase tracking-widest text-[#e9cf91]">{cuota.preregistroId.numeroPreRegistro}</p><h1 className="text-2xl font-black">{u?.nombres} {u?.apellidoPaterno}</h1></div><Resumen t="Pagado" v={`Bs ${cuota.montoPagado.toFixed(2)}`} /><Resumen t="Saldo" v={`Bs ${cuota.saldo.toFixed(2)}`} /></header>
    <form onSubmit={(e) => { e.preventDefault(); registrar.mutate(); }} className="grid gap-4 rounded-2xl bg-white p-6 sm:grid-cols-2"><h2 className="text-xl font-black text-[#74122A] sm:col-span-2">Registrar pago parcial</h2><input required type="number" min="0.01" max={cuota.saldo} step="0.01" value={form.monto || ""} onChange={(e) => { const monto = Number(e.target.value); setForm({ ...form, monto, montoEfectivo: form.metodoPago === "EFECTIVO" ? monto : form.montoEfectivo, montoQr: form.metodoPago === "QR" ? monto : form.montoQr }); }} className="input-preregistro" placeholder="Monto total" /><select value={form.metodoPago} onChange={(e) => cambiarMetodo(e.target.value as MetodoPago)} className="input-preregistro"><option>EFECTIVO</option><option>QR</option><option>MIXTO</option></select>{form.metodoPago === "MIXTO" && <><input required type="number" min="0" step="0.01" value={form.montoEfectivo || ""} onChange={(e) => setForm({ ...form, montoEfectivo: Number(e.target.value) })} className="input-preregistro" placeholder="Monto efectivo" /><input required type="number" min="0" step="0.01" value={form.montoQr || ""} onChange={(e) => setForm({ ...form, montoQr: Number(e.target.value) })} className="input-preregistro" placeholder="Monto QR" /></>}<input required value={form.nombrePagador} onChange={(e) => setForm({ ...form, nombrePagador: e.target.value })} className="input-preregistro" placeholder="Nombre de quien pagó" /><input required type="date" value={form.fechaPago} onChange={(e) => setForm({ ...form, fechaPago: e.target.value })} className="input-preregistro" />{form.metodoPago !== "EFECTIVO" && <input required type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => setForm({ ...form, baucher: e.target.files?.[0] ?? null })} className="input-preregistro sm:col-span-2" />}<button disabled={registrar.isPending} className="rounded-xl bg-[#74122A] px-5 py-3 font-bold text-white sm:col-span-2">{registrar.isPending ? "Subiendo..." : "Registrar para revisión"}</button></form>
    <section className="grid gap-3 rounded-2xl bg-white p-4 sm:grid-cols-[1fr_auto]"><input type="search" value={buscar} onChange={(e) => setBuscar(e.target.value)} className="input-preregistro" placeholder="Buscar pagador, medio, monto o fecha..." /><select value={estado} onChange={(e) => setEstado(e.target.value as EstadoRevisionPago | "")} className="input-preregistro"><option value="">Todas las revisiones</option>{["PENDIENTE", "VERIFICADO", "OBSERVADO", "RECHAZADO"].map((x) => <option key={x}>{x}</option>)}</select></section>
    <div className="grid gap-4 md:grid-cols-2">{pagos.map((pago) => <PagoCard key={pago._id} pago={pago} telefono={u?.telefono} nombreUsuario={`${u?.nombres ?? ""} ${u?.apellidoPaterno ?? ""}`.trim()} cuotaId={id} refrescar={refrescar} eliminar={() => borrar.mutate(pago._id)} />)}</div>
  </div>;
}

function PagoCard({ pago, telefono, nombreUsuario, cuotaId, refrescar, eliminar }: { pago: DetalleCuota; telefono?: string; nombreUsuario: string; cuotaId: string; refrescar: () => Promise<unknown>; eliminar: () => void }) {
  const [observacion, setObservacion] = useState(pago.observacionRevision ?? ""); const [respaldo, setRespaldo] = useState<File | null>(null);
  const revisar = useMutation({ mutationFn: (estadoRevision: EstadoRevisionPago) => revisarPago(cuotaId, pago._id, { estadoRevision, observacionRevision: observacion || undefined, respaldoAdmin: respaldo }), onSuccess: async () => { toast.success("Revisión guardada"); await refrescar(); }, onError: (e) => toast.error(e instanceof Error ? e.message : "No se pudo revisar") });
  const numeroLocal = String(telefono ?? "").replace(/\D/g, "");
  const numeroWhatsapp = numeroLocal ? (numeroLocal.startsWith("591") ? numeroLocal : `591${numeroLocal}`) : "";
  const mensajeWhatsapp = `Hola ${nombreUsuario || "fraterno/a"}, administración de Tinkus Puros revisó tu pago N.º ${pago.numeroPago} de Bs ${pago.monto.toFixed(2)}. ${observacion.trim() ? `Observación: ${observacion.trim()}` : "Por favor comunícate con administración para revisar tu comprobante."}`;
  const enlaceWhatsapp = numeroWhatsapp ? `https://wa.me/${numeroWhatsapp}?text=${encodeURIComponent(mensajeWhatsapp)}` : "";
  const motivosRapidos = ["La foto está borrosa", "Los datos no coinciden", "El monto es incorrecto", "El comprobante está incompleto"];
  return <article className="overflow-hidden rounded-2xl border bg-white">{pago.baucherImagen ? <a href={`${API}${pago.baucherImagen}`} target="_blank" rel="noreferrer"><img src={`${API}${pago.baucherImagen}`} alt={`Baucher pago ${pago.numeroPago}`} className="h-52 w-full bg-slate-100 object-contain" /></a> : <div className="grid h-32 place-items-center bg-[#f5efe4] font-bold text-[#74122A]">💵 Pago en efectivo</div>}<div className="space-y-3 p-5"><div className="flex justify-between"><div><p className="text-xs text-slate-500">Pago N.º {pago.numeroPago} · {pago.metodoPago}</p><strong>Bs {pago.monto.toFixed(2)}</strong></div><span className="text-xs font-bold text-[#74122A]">{pago.estadoRevision}</span></div>{pago.metodoPago === "MIXTO" && <p className="text-sm">Efectivo Bs {pago.montoEfectivo.toFixed(2)} · QR Bs {pago.montoQr.toFixed(2)}</p>}<p className="text-sm"><strong>Pagador:</strong> {pago.nombrePagador}</p><p className="text-sm"><strong>Fecha:</strong> {new Date(pago.fechaPago).toLocaleDateString("es-BO")}</p>{pago.montoEfectivo > 0 && <label><span className="text-xs font-bold">Respaldo administrativo del efectivo</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => setRespaldo(e.target.files?.[0] ?? null)} className="input-preregistro mt-1" /></label>}<textarea value={observacion} onChange={(e) => setObservacion(e.target.value)} className="input-preregistro" placeholder="Motivo obligatorio al observar o rechazar" /><div className="flex flex-wrap gap-2">{motivosRapidos.map((motivo) => <button type="button" key={motivo} onClick={() => setObservacion(motivo)} className="rounded-full bg-amber-50 px-3 py-1 text-xs text-amber-800">{motivo}</button>)}</div><div className="flex flex-wrap gap-2">{(["VERIFICADO", "OBSERVADO", "RECHAZADO"] as EstadoRevisionPago[]).map((estado) => <button type="button" key={estado} disabled={revisar.isPending} onClick={() => revisar.mutate(estado)} className="rounded-lg border px-2 py-1 text-xs font-bold disabled:opacity-50">{estado}</button>)}<button type="button" onClick={() => confirm("¿Eliminar pago?") && eliminar()} className="rounded-lg bg-red-50 px-2 py-1 text-xs text-red-700">Eliminar</button></div>{enlaceWhatsapp ? <a href={enlaceWhatsapp} target="_blank" rel="noreferrer" className="inline-flex rounded-lg bg-[#25D366] px-4 py-2 text-sm font-bold text-white">Enviar mensaje por WhatsApp</a> : <p className="text-xs text-amber-700">El usuario no tiene un celular registrado.</p>}</div></article>;
}
function Resumen({ t, v }: { t: string; v: string }) { return <div className="rounded-xl bg-white/10 p-3"><p className="text-xs text-white/70">{t}</p><strong className="text-xl">{v}</strong></div>; }
