import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { toast } from "react-toastify";
import { eliminarPago, obtenerCuota, prorrogarPrimeraCuota, registrarPago, revisarPago } from "@/api/CuotaApi";
import type { DetalleCuota, EstadoRevisionPago, MetodoPago } from "@/types/CuotaType";
import { fechaActualBoliviaParaInput, formatearFechaCivilCorta } from "@/utils/fechaCivil";
const API = String(import.meta.env.VITE_API_URL || "").replace(/\/api\/?$/, "");

export default function DetalleCuotaView() {
  const { id = "" } = useParams(); const nav = useNavigate(); const location = useLocation(); const qc = useQueryClient(); const [buscar, setBuscar] = useState(""); const [estado, setEstado] = useState<EstadoRevisionPago | "">("");
  const retorno = location.state as { returnTo?: string; reopenCuotaId?: string; viewState?: unknown } | null;
  const volver = () => retorno?.returnTo ? nav(retorno.returnTo, { state: { reopenCuotaId: retorno.reopenCuotaId, viewState: retorno.viewState } }) : nav(-1);
  const [form, setForm] = useState<{ monto: number; metodoPago: MetodoPago; montoEfectivo: number; montoQr: number; nombrePagador: string; fechaPago: string; baucher: File | null }>({ monto: 0, metodoPago: "QR", montoEfectivo: 0, montoQr: 0, nombrePagador: "", fechaPago: fechaActualBoliviaParaInput(), baucher: null });
  const [prorroga, setProrroga] = useState({ horas: 24, motivo: "" });
  const q = useQuery({ queryKey: ["cuota", id], queryFn: () => obtenerCuota(id) }); const refrescar = () => qc.invalidateQueries({ queryKey: ["cuota", id] });
  const registrar = useMutation({ mutationFn: () => registrarPago(id, form), onSuccess: async () => { toast.success("Pago enviado para revisión"); setForm({ ...form, monto: 0, montoEfectivo: 0, montoQr: 0, baucher: null }); await refrescar(); }, onError: (e) => toast.error(e instanceof Error ? e.message : "Error") });
  const ampliar = useMutation({ mutationFn: () => prorrogarPrimeraCuota(id, prorroga), onSuccess: async (respuesta) => { toast.success(respuesta.message); setProrroga((previa) => ({ ...previa, motivo: "" })); await refrescar(); }, onError: (e) => toast.error(e instanceof Error ? e.message : "No se pudo ampliar el plazo") });
  const borrar = useMutation({ mutationFn: (pagoId: string) => eliminarPago(id, pagoId), onSuccess: refrescar });
  if (!q.data) return <p>{q.isLoading ? "Cargando cuota..." : "No se encontró la cuota"}</p>;
  const { cuota } = q.data; const u = cuota.preregistroId.usuarioId; const pagos = q.data.pagos.filter((p) => (!estado || p.estadoRevision === estado) && `${p.nombrePagador} ${p.fechaPago} ${p.monto} ${p.metodoPago}`.toLowerCase().includes(buscar.toLowerCase()));
  return <div className="space-y-6"><button onClick={volver} className="font-bold text-[#74122A]">← Volver a pagos de {u?.nombres ?? "usuario"}</button><header className="grid gap-4 rounded-2xl bg-[#74122A] p-6 text-white sm:grid-cols-4"><div className="sm:col-span-2"><p className="text-xs uppercase tracking-widest text-[#e9cf91]">{cuota.preregistroId.numeroPreRegistro}</p><h1 className="text-2xl font-black">{u?.nombres} {u?.apellidoPaterno}</h1></div><Resumen t="Pagado" v={`Bs ${cuota.montoPagado.toFixed(2)}`} /><Resumen t="Saldo" v={`Bs ${cuota.saldo.toFixed(2)}`} /></header>
    {cuota.saldo > 0 ? <form onSubmit={(evento) => { evento.preventDefault(); ampliar.mutate(); }} className="rounded-2xl border border-amber-300 bg-amber-50 p-6"><h2 className="text-xl font-black text-[#74122A]">Habilitar un nuevo plazo de pago</h2><p className="mt-1 text-sm text-amber-900">Si ya aprobó la primera cuota, su cupo de fraterno permanece protegido. Si aún no pagó la primera, continúa en lista de espera sin recuperar el cupo automáticamente.</p>{cuota.cupoLiberado ? <p className="mt-3 rounded-lg bg-red-100 p-3 font-bold text-red-800">Primera cuota vencida · usuario en lista de espera</p> : null}<div className="mt-4 grid gap-3 sm:grid-cols-[180px_1fr_auto]"><label><span className="mb-1 block text-xs font-bold uppercase">Horas</span><input required type="number" min="1" max="8760" value={prorroga.horas} onChange={(evento) => setProrroga((previa) => ({ ...previa, horas: Number(evento.target.value) }))} className="input-preregistro" /></label><label><span className="mb-1 block text-xs font-bold uppercase">Motivo</span><input required minLength={3} maxLength={500} value={prorroga.motivo} onChange={(evento) => setProrroga((previa) => ({ ...previa, motivo: evento.target.value }))} className="input-preregistro" placeholder="Ej.: solicitó una prórroga por WhatsApp" /></label><button disabled={ampliar.isPending} className="self-end rounded-xl bg-[#74122A] px-5 py-3 font-bold text-white disabled:opacity-50">{ampliar.isPending ? "Guardando..." : "Dar nuevo plazo"}</button></div>{cuota.fechaVencimiento ? <p className="mt-3 text-sm">Vencimiento actual: {new Date(cuota.fechaVencimiento).toLocaleString("es-BO")}</p> : null}</form> : null}
    <form onSubmit={(e) => { e.preventDefault(); registrar.mutate(); }} className="grid gap-4 rounded-2xl bg-white p-6 sm:grid-cols-2"><div className="sm:col-span-2"><h2 className="text-xl font-black text-[#74122A]">Registrar comprobante QR o depósito</h2><p className="text-sm text-slate-500">Se aceptan imágenes y PDF de hasta 30 MB; el sistema los optimiza automáticamente.</p></div><input required type="number" min="0.01" max={cuota.saldo} step="0.01" value={form.monto || ""} onChange={(e) => { const monto = Number(e.target.value); setForm({ ...form, monto, montoEfectivo: 0, montoQr: monto }); }} className="input-preregistro" placeholder="Monto pagado"/><input required value={form.nombrePagador} onChange={(e) => setForm({ ...form, nombrePagador: e.target.value })} className="input-preregistro" placeholder="Nombre del titular del comprobante"/><input required type="date" value={form.fechaPago} onChange={(e) => setForm({ ...form, fechaPago: e.target.value })} className="input-preregistro"/><input required type="file" accept="image/*,application/pdf,.pdf" onChange={(e) => setForm({ ...form, baucher: e.target.files?.[0] ?? null })} className="input-preregistro"/><button disabled={registrar.isPending || !form.baucher} className="rounded-xl bg-[#74122A] px-5 py-3 font-bold text-white disabled:opacity-50 sm:col-span-2">{registrar.isPending ? "Subiendo..." : "Registrar comprobante para revisión"}</button></form>
    <section className="grid gap-3 rounded-2xl bg-white p-4 sm:grid-cols-[1fr_auto]"><input type="search" value={buscar} onChange={(e) => setBuscar(e.target.value)} className="input-preregistro" placeholder="Buscar pagador, medio, monto o fecha..." /><select value={estado} onChange={(e) => setEstado(e.target.value as EstadoRevisionPago | "")} className="input-preregistro"><option value="">Todas las revisiones</option>{["PENDIENTE", "VERIFICADO", "OBSERVADO", "RECHAZADO"].map((x) => <option key={x}>{x}</option>)}</select></section>
    <div className="grid gap-4 md:grid-cols-2">{pagos.map((pago) => <PagoCard key={pago._id} pago={pago} telefono={u?.telefono} nombreUsuario={`${u?.nombres ?? ""} ${u?.apellidoPaterno ?? ""}`.trim()} cuotaId={id} refrescar={refrescar} eliminar={() => borrar.mutate(pago._id)} />)}</div>
  </div>;
}

function PagoCard({ pago, telefono, nombreUsuario, cuotaId, refrescar, eliminar }: { pago: DetalleCuota; telefono?: string; nombreUsuario: string; cuotaId: string; refrescar: () => Promise<unknown>; eliminar: () => void }) {
  const [observacion, setObservacion] = useState(pago.observacionRevision ?? ""); const respaldo: File | null = null;
  const revisar = useMutation({ mutationFn: (estadoRevision: EstadoRevisionPago) => revisarPago(cuotaId, pago._id, { estadoRevision, observacionRevision: observacion || undefined, respaldoAdmin: respaldo }), onSuccess: async () => { toast.success("Revisión guardada"); await refrescar(); }, onError: (e) => toast.error(e instanceof Error ? e.message : "No se pudo revisar") });
  const numeroLocal = String(telefono ?? "").replace(/\D/g, "");
  const numeroWhatsapp = numeroLocal ? (numeroLocal.startsWith("591") ? numeroLocal : `591${numeroLocal}`) : "";
  const mensajeWhatsapp = `Hola ${nombreUsuario || "fraterno/a"}, administración de Tinkus Puros revisó tu pago N.º ${pago.numeroPago} de Bs ${pago.monto.toFixed(2)}. ${observacion.trim() ? `Observación: ${observacion.trim()}` : "Por favor comunícate con administración para revisar tu comprobante."}`;
  const enlaceWhatsapp = numeroWhatsapp ? `https://wa.me/${numeroWhatsapp}?text=${encodeURIComponent(mensajeWhatsapp)}` : "";
  const motivosRapidos = ["La foto está borrosa", "Los datos no coinciden", "El monto es incorrecto", "El comprobante está incompleto"];
  const comprobantePdf = pago.baucherImagen?.toLowerCase().endsWith(".pdf");
  return <article className="overflow-hidden rounded-2xl border bg-white">{pago.baucherImagen ? (comprobantePdf ? <iframe src={`${API}${pago.baucherImagen}`} title={`Comprobante del pago ${pago.numeroPago}`} className="h-72 w-full bg-slate-100"/> : <a href={`${API}${pago.baucherImagen}`} target="_blank" rel="noreferrer"><img src={`${API}${pago.baucherImagen}`} alt={`Comprobante del pago ${pago.numeroPago}`} className="h-52 w-full bg-slate-100 object-contain" /></a>) : <div className="grid h-32 place-items-center bg-[#f5efe4] font-bold text-[#74122A]">Sin comprobante</div>}<div className="space-y-3 p-5"><div className="flex justify-between"><div><p className="text-xs text-slate-500">Pago N.º {pago.numeroPago} · QR o depósito</p><strong>Bs {pago.monto.toFixed(2)}</strong></div><span className="text-xs font-bold text-[#74122A]">{pago.estadoRevision}</span></div><p className="text-sm"><strong>Titular:</strong> {pago.nombrePagador}</p><p className="text-sm"><strong>Fecha:</strong> {formatearFechaCivilCorta(pago.fechaPago)}</p><textarea value={observacion} onChange={(e) => setObservacion(e.target.value)} className="input-preregistro" placeholder="Motivo obligatorio al observar o rechazar" /><div className="flex flex-wrap gap-2">{motivosRapidos.map((motivo) => <button type="button" key={motivo} onClick={() => setObservacion(motivo)} className="rounded-full bg-amber-50 px-3 py-1 text-xs text-amber-800">{motivo}</button>)}</div><div className="flex flex-wrap gap-2">{(["VERIFICADO", "OBSERVADO", "RECHAZADO"] as EstadoRevisionPago[]).map((estado) => <button type="button" key={estado} disabled={revisar.isPending} onClick={() => revisar.mutate(estado)} className="rounded-lg border px-2 py-1 text-xs font-bold disabled:opacity-50">{estado}</button>)}<button type="button" onClick={() => confirm("¿Eliminar pago?") && eliminar()} className="rounded-lg bg-red-50 px-2 py-1 text-xs text-red-700">Eliminar</button></div>{enlaceWhatsapp ? <a href={enlaceWhatsapp} target="_blank" rel="noreferrer" className="inline-flex rounded-lg bg-[#25D366] px-4 py-2 text-sm font-bold text-white">Enviar mensaje por WhatsApp</a> : <p className="text-xs text-amber-700">El usuario no tiene un celular registrado.</p>}</div></article>;
}
function Resumen({ t, v }: { t: string; v: string }) { return <div className="rounded-xl bg-white/10 p-3"><p className="text-xs text-white/70">{t}</p><strong className="text-xl">{v}</strong></div>; }
