import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "react-toastify";
import api from "@/lib/axios";

const nombre=(r:any)=>{const u=r?.usuarioId??r;return [u?.nombres,u?.apellidoPaterno,u?.apellidoMaterno].filter(Boolean).join(" ")||r?.numeroFraterno||"Sin nombre"};
const genero=(v:any)=>["HOMBRE","MASCULINO","M","VARON","VARÓN"].includes(String(v??"").toUpperCase())?"HOMBRE":["MUJER","FEMENINO","F"].includes(String(v??"").toUpperCase())?"MUJER":"";
const ordenar=(items:any[])=>[...items].sort((a,b)=>nombre(a).localeCompare(nombre(b),"es",{sensitivity:"base"}));
const pago=(f:any)=>!f.cuota||f.cuota.montoPagado<=0?"SIN PAGOS":f.cuota.saldo<=0?"PAGO COMPLETO":"PAGO PARCIAL";

export default function GuiaBloqueView(){
 const qc=useQueryClient(),[nombreBloque,setNombreBloque]=useState(""),[buscar,setBuscar]=useState("");
 const q=useQuery({queryKey:["guias-bloques"],queryFn:async()=>(await api.get("/guias")).data});
 const accion=useMutation({mutationFn:(fn:()=>Promise<any>)=>fn(),onSuccess:async r=>{toast.success(r.data?.message??r.message);setNombreBloque("");await qc.invalidateQueries({queryKey:["guias-bloques"]})},onError:(e:any)=>toast.error(e.response?.data?.error??"No se pudo completar la acción")});
 const asignacionGuia=new Map((q.data?.bloques??[]).flatMap((b:any)=>(b.guiasIds??[]).map((g:any)=>[String(g._id??g),b])));
 const crear=(e:React.FormEvent)=>{e.preventDefault();if(nombreBloque.trim())accion.mutate(()=>api.post("/guias/bloques",{nombre:nombreBloque}))};
 if(q.isLoading)return <p className="p-8">Cargando bloques...</p>;
 return <main className="space-y-5"><header><p className="text-xs font-black uppercase tracking-widest text-[#8F5F2A]">Administración</p><h1 className="text-3xl font-black text-[#841534]">Supervisión de bloques</h1><p className="text-slate-500">Crea bloques administrativos, asigna guías e integrantes sin posiciones físicas.</p></header>
  <section className="rounded-2xl border bg-white p-5"><form onSubmit={crear} className="flex flex-col gap-3 sm:flex-row"><input required value={nombreBloque} onChange={e=>setNombreBloque(e.target.value.toUpperCase())} placeholder="Nombre del nuevo bloque o bloque de prueba" className="flex-1 rounded-xl border p-3"/><button className="rounded-xl bg-[#841534] px-5 py-3 font-black text-white">Crear bloque</button></form><p className="mt-2 text-xs text-slate-500">Puede crearse sin guías reales para realizar pruebas.</p></section>
  <input value={buscar} onChange={e=>setBuscar(e.target.value)} placeholder="Buscar bloque, guía, fraterno o CI..." className="w-full rounded-xl border bg-white p-3"/>
  <section className="grid gap-5">{(q.data?.bloques??[]).filter((b:any)=>`${b.nombre} ${(b.guiasIds??[]).map(nombre).join(" ")}`.toLowerCase().includes(buscar.toLowerCase())||!buscar).map((b:any)=><Bloque key={b._id} bloque={b} datos={q.data} asignacionGuia={asignacionGuia} accion={accion}/>)}</section>
 </main>;
}

function Bloque({bloque,datos,asignacionGuia,accion}:{bloque:any;datos:any;asignacionGuia:Map<string,any>;accion:any}){
 const [abierto,setAbierto]=useState(false),[buscar,setBuscar]=useState(""),[nombreNuevo,setNombreNuevo]=useState("");
 const detalles=(datos.detalles??[]).filter((d:any)=>String(d.bloqueId?._id??d.bloqueId)===String(bloque._id)),mapa=new Map((datos.fraternos??[]).map((f:any)=>[String(f._id),f]));
 const integrantes=detalles.map((d:any)=>mapa.get(String(d.fraternoId?._id??d.fraternoId))??d.fraternoId),hombres=ordenar(integrantes.filter((f:any)=>genero(f.usuarioId?.sexo)==="HOMBRE")),mujeres=ordenar(integrantes.filter((f:any)=>genero(f.usuarioId?.sexo)==="MUJER"));
 const guias=bloque.guiasIds??[],gh=guias.filter((g:any)=>genero(g.usuarioId?.sexo)==="HOMBRE"),gm=guias.filter((g:any)=>genero(g.usuarioId?.sexo)==="MUJER");
 const texto=buscar.toLowerCase(),disponibles=ordenar((datos.fraternos??[]).filter((f:any)=>!datos.detalles.some((d:any)=>String(d.fraternoId?._id??d.fraternoId)===String(f._id))&&(!texto||`${nombre(f)} ${f.usuarioId?.ci??""} ${f.numeroFraterno??""}`.toLowerCase().includes(texto))));
 const moverGuia=(id:string,bloqueId:string|null)=>accion.mutate(()=>api.patch(`/guias/bloques/guias/${id}`,{bloqueId}));
 const exportar=async(e:React.MouseEvent)=>{e.stopPropagation();const{default:ExcelJS}=await import("exceljs");const libro=new ExcelJS.Workbook(),hoja=libro.addWorksheet("Integrantes");hoja.columns=[{header:"N.º",key:"n",width:8},{header:"Nombre",key:"nombre",width:38},{header:"CI",key:"ci",width:16},{header:"Celular",key:"telefono",width:20,style:{numFmt:"@"}},{header:"Correo",key:"correo",width:30},{header:"Sexo",key:"sexo",width:12},{header:"Código",key:"codigo",width:18},{header:"Pago",key:"pago",width:18},{header:"Polera",key:"polera",width:12},{header:"Chamarra",key:"chamarra",width:12}];ordenar(integrantes).forEach((f:any,i)=>hoja.addRow({n:i+1,nombre:nombre(f),ci:String(f.usuarioId?.ci??""),telefono:String(f.usuarioId?.telefono??""),correo:f.usuarioId?.email??"",sexo:genero(f.usuarioId?.sexo),codigo:f.numeroFraterno??"",pago:pago(f),polera:f.talla?.tallaPolera??"",chamarra:f.talla?.tallaChamarra??""}));hoja.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};hoja.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF74122A"}};const data=await libro.xlsx.writeBuffer(),url=URL.createObjectURL(new Blob([data],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"})),a=document.createElement("a");a.href=url;a.download=`bloque-${bloque.nombre.toLowerCase().replace(/[^a-z0-9]+/g,"-")}.xlsx`;a.click();URL.revokeObjectURL(url)};
 return <article className="overflow-hidden rounded-2xl border bg-white shadow-sm"><button onClick={()=>setAbierto(!abierto)} className="w-full p-5 text-left"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-black text-[#841534]">{bloque.nombre}</h2><p className="text-sm text-slate-500">{guias.length}/4 guías · {integrantes.length}/120 integrantes</p></div><div className="flex items-center gap-3"><span onClick={exportar} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-black text-white">Excel</span><span className="font-black text-[#841534]">{abierto?"Contraer −":"Supervisar +"}</span></div></div><div className="mt-4 grid grid-cols-2 gap-2 lg:grid-cols-5"><M t="Hombres" v={`${hombres.length}/40`}/><M t="Libres H" v={40-hombres.length}/><M t="Mujeres" v={`${mujeres.length}/80`}/><M t="Libres M" v={80-mujeres.length}/><M t="Total" v={`${integrantes.length}/120`}/></div></button>
 {abierto&&<div className="space-y-5 border-t p-5"><form className="flex gap-2" onSubmit={e=>{e.preventDefault();accion.mutate(()=>api.patch(`/guias/bloques/${bloque._id}/nombre`,{nombre:nombreNuevo}))}}><input required value={nombreNuevo} onChange={e=>setNombreNuevo(e.target.value.toUpperCase())} placeholder="Modificar nombre" className="flex-1 rounded-xl border p-3"/><button className="rounded-xl border border-[#841534] px-4 font-bold text-[#841534]">Guardar</button></form>
  <div className="grid gap-4 lg:grid-cols-2"><Guias titulo="Guías hombres" actuales={gh} candidatos={(datos.guias??[]).filter((g:any)=>genero(g.usuarioId?.sexo)==="HOMBRE")} asignacion={asignacionGuia} bloque={bloque} mover={moverGuia}/><Guias titulo="Guías mujeres" actuales={gm} candidatos={(datos.guias??[]).filter((g:any)=>genero(g.usuarioId?.sexo)==="MUJER")} asignacion={asignacionGuia} bloque={bloque} mover={moverGuia}/></div>
  <section><h3 className="font-black text-[#841534]">Buscar y agregar fraterno</h3><input value={buscar} onChange={e=>setBuscar(e.target.value)} placeholder="CI, nombre o código..." className="mt-2 w-full rounded-xl border p-3"/>{buscar&&<div className="mt-3 max-h-80 space-y-2 overflow-y-auto">{disponibles.map((f:any)=><article key={f._id} className="flex flex-col justify-between gap-3 rounded-xl border p-3 sm:flex-row"><div><b>{nombre(f)}</b><p className="text-xs text-slate-500">CI {f.usuarioId?.ci??"—"} · {f.usuarioId?.email??"Sin correo"} · {f.usuarioId?.telefono??"Sin celular"} · {genero(f.usuarioId?.sexo)}</p><p className="text-xs font-bold">{f.numeroFraterno} · {pago(f)} · Polera {f.talla?.tallaPolera??"—"} · Chamarra {f.talla?.tallaChamarra??"—"}</p></div><button onClick={()=>accion.mutate(()=>api.post("/guias/bloques/integrantes",{bloqueId:bloque._id,fraternoId:f._id}))} className="rounded-xl bg-emerald-700 px-4 py-2 font-bold text-white">Agregar al bloque</button></article>)}</div>}</section>
  <div className="grid gap-5 xl:grid-cols-2"><Integrantes titulo="Integrantes hombres" items={hombres} detalles={detalles} accion={accion}/><Integrantes titulo="Integrantes mujeres" items={mujeres} detalles={detalles} accion={accion}/></div>
 </div>}</article>;
}
function M({t,v}:{t:string;v:string|number}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase text-slate-500">{t}</p><b className="text-xl text-[#841534]">{v}</b></div>}
function Guias({titulo,actuales,candidatos,asignacion,bloque,mover}:{titulo:string;actuales:any[];candidatos:any[];asignacion:Map<string,any>;bloque:any;mover:(id:string,b:string|null)=>void}){return <div className="rounded-xl bg-slate-50 p-4"><h3 className="font-black">{titulo} ({actuales.length}/2)</h3>{actuales.map(g=><div key={g._id} className="mt-2 flex justify-between rounded-lg bg-white p-3"><b>{nombre(g)}</b><button onClick={()=>confirm("¿Retirar este guía del bloque?")&&mover(g._id,null)} className="text-xs font-bold text-red-700">Retirar</button></div>)}{actuales.length<2&&<select defaultValue="" onChange={e=>{if(e.target.value)mover(e.target.value,bloque._id)}} className="mt-3 w-full rounded-xl border p-3"><option value="">Asignar guía...</option>{candidatos.filter(g=>!asignacion.has(String(g._id))).map(g=><option key={g._id} value={g._id}>{nombre(g)}</option>)}</select>}</div>}
function Integrantes({titulo,items,detalles,accion}:{titulo:string;items:any[];detalles:any[];accion:any}){return <section><h3 className="font-black">{titulo} ({items.length})</h3><div className="mt-2 space-y-2">{items.map((f:any,i)=>{const d=detalles.find(x=>String(x.fraternoId?._id??x.fraternoId)===String(f._id));return <article key={f._id} className="flex justify-between gap-3 rounded-xl border p-3"><div><b>{i+1}. {nombre(f)}</b><p className="text-xs text-slate-500">CI {f.usuarioId?.ci??"—"} · {f.usuarioId?.telefono??"Sin celular"} · {pago(f)}</p></div><button onClick={()=>confirm("¿Retirar este integrante del bloque?")&&accion.mutate(()=>api.delete(`/guias/bloques/integrantes/${d._id}`))} className="text-xs font-bold text-red-700">Retirar</button></article>})}</div></section>}
