import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "react-toastify";
import { buscarCandidatoGuia, crearBloque, obtenerSupervisionBloques, quitarRolGuia } from "@/api/BloqueGuiaApi";
import api from "@/lib/axios";

const nombre=(r:any)=>{const u=r?.usuarioId??r;return [u?.nombres,u?.apellidoPaterno,u?.apellidoMaterno].filter(Boolean).join(" ")||r?.numeroFraterno||"Sin nombre"};
const genero=(v:any)=>["HOMBRE","MASCULINO","M","VARON","VARÓN"].includes(String(v??"").toUpperCase())?"HOMBRE":["MUJER","FEMENINO","F"].includes(String(v??"").toUpperCase())?"MUJER":"";
const ordenar=(items:any[])=>[...items].sort((a,b)=>nombre(a).localeCompare(nombre(b),"es",{sensitivity:"base"}));
const pago=(f:any)=>!f.cuota||f.cuota.montoPagado<=0?"SIN PAGOS":f.cuota.saldo<=0?"PAGO COMPLETO":"PAGO PARCIAL";

export default function GuiaBloqueView(){
 const qc=useQueryClient(),[nombreBloque,setNombreBloque]=useState(""),[buscar,setBuscar]=useState(""),[ciGuia,setCiGuia]=useState(""),[bloqueEliminar,setBloqueEliminar]=useState<any>(null);
 const q=useQuery({queryKey:["guias-bloques"],queryFn:obtenerSupervisionBloques});
 const ciNormalizado=ciGuia.trim();
 const candidatoQ=useQuery({queryKey:["candidato-guia",ciNormalizado],queryFn:()=>buscarCandidatoGuia(ciNormalizado),enabled:ciNormalizado.length>=4,retry:false});
 const accion=useMutation({mutationFn:(fn:()=>Promise<any>)=>fn(),onSuccess:async r=>{toast.success(r.data?.message??r.message);setNombreBloque("");await Promise.all([qc.invalidateQueries({queryKey:["guias-bloques"]}),qc.invalidateQueries({queryKey:["candidato-guia"]})])},onError:(e:any)=>toast.error(e.response?.data?.error??"No se pudo completar la acción")});
 const asignacionGuia=new Map((q.data?.bloques??[]).flatMap((b:any)=>[b.guiaId,...(b.guiasIds??[])].filter(Boolean).map((g:any)=>[String(g._id??g),b])));
 const guiasPorUsuario=new Set((q.data?.guias??[]).map((g:any)=>String(g.usuarioId?._id??g.usuarioId)));
 const candidato=candidatoQ.data?.candidato,usuarioCandidato=candidato?.usuario;
 const crear=(e:React.FormEvent)=>{e.preventDefault();if(nombreBloque.trim())accion.mutate(()=>crearBloque(nombreBloque))};
 if(q.isLoading)return <p className="p-8">Cargando bloques...</p>;
 return <main className="space-y-5"><header><p className="text-xs font-black uppercase tracking-widest text-[#8F5F2A]">Administración</p><h1 className="text-3xl font-black text-[#841534]">Supervisión de bloques</h1><p className="text-slate-500">Crea bloques administrativos, asigna guías e integrantes sin posiciones físicas.</p></header>
  <section className="rounded-2xl border bg-white p-5"><form onSubmit={crear} className="flex flex-col gap-3 sm:flex-row"><input required value={nombreBloque} onChange={e=>setNombreBloque(e.target.value.toUpperCase())} placeholder="Nombre del nuevo bloque o bloque de prueba" className="flex-1 rounded-xl border p-3"/><button className="rounded-xl bg-[#841534] px-5 py-3 font-black text-white">Crear bloque</button></form><p className="mt-2 text-xs text-slate-500">Puede crearse sin guías reales para realizar pruebas.</p></section>
  <section className="grid gap-5 lg:grid-cols-2">
   <article className="rounded-2xl border bg-white p-5"><h2 className="font-black text-[#841534]">Convertir usuario en guía</h2><p className="text-sm text-slate-500">Busca por CI entre los usuarios de Gestión integral. Se conserva su perfil y preregistro.</p><input value={ciGuia} onChange={e=>setCiGuia(e.target.value)} placeholder="Carnet de identidad" className="mt-3 w-full rounded-xl border p-3"/>{ciNormalizado&&<div className="mt-3">{ciNormalizado.length<4?<p className="text-sm text-slate-500">Escribe al menos 4 caracteres del CI.</p>:candidatoQ.isFetching?<p className="text-sm text-slate-500">Buscando usuario...</p>:candidato?<article className="rounded-xl bg-slate-50 p-4"><b>{nombre(usuarioCandidato)}</b><p className="text-sm text-slate-500">CI {usuarioCandidato?.ci} · {genero(usuarioCandidato?.sexo)||"Sexo no registrado"}</p><p className="text-xs text-slate-500">{candidato.preregistro?`Preregistro ${candidato.preregistro.numeroPreRegistro} · ${candidato.preregistro.estado}`:"Sin preregistro"}{candidato.fraterno?` · Fraterno ${candidato.fraterno.numeroFraterno}`:""}</p>{guiasPorUsuario.has(String(usuarioCandidato?._id))||candidato.guia?<p className="mt-2 font-bold text-emerald-700">Ya tiene rol de guía y está disponible en la lista.</p>:!candidato.puedeConvertirse?<p className="mt-2 font-bold text-amber-700">El usuario existe, pero necesita un preregistro antes de ser guía.</p>:<button disabled={accion.isPending} onClick={()=>accion.mutate(()=>api.post("/guias/convertir-fraterno",{ci:usuarioCandidato.ci}))} className="mt-3 rounded-xl bg-[#841534] px-4 py-2 font-bold text-white disabled:cursor-wait disabled:opacity-50">{accion.isPending?"Registrando...":"Convertir en guía"}</button>}</article>:<p className="mt-2 text-sm text-slate-500">{(candidatoQ.error as any)?.response?.data?.error??"No se encontró un usuario registrado con ese CI."}</p>}</div>}</article>
   <article className="rounded-2xl border bg-white p-5"><h2 className="font-black text-[#841534]">Guías disponibles y asignados</h2><div className="mt-3 max-h-64 space-y-2 overflow-y-auto">{ordenar(q.data?.guias??[]).map((g:any)=>{const b=asignacionGuia.get(String(g._id));return <div key={g._id} className="rounded-xl bg-slate-50 p-3"><b>{nombre(g)}</b><p className={`text-xs font-bold ${b?"text-amber-700":"text-emerald-700"}`}>{b?`Ya es guía del ${b.nombre}`:"Disponible para asignar"} · {genero(g.usuarioId?.sexo)||"Sin sexo"}</p></div>})}</div></article>
  </section>
  <input value={buscar} onChange={e=>setBuscar(e.target.value)} placeholder="Buscar bloque, guía, fraterno o CI..." className="w-full rounded-xl border bg-white p-3"/>
  <section className="grid gap-5">{(q.data?.bloques??[]).filter((b:any)=>`${b.nombre} ${(b.guiasIds??[]).map(nombre).join(" ")}`.toLowerCase().includes(buscar.toLowerCase())||!buscar).map((b:any)=><Bloque key={b._id} bloque={b} datos={q.data} asignacionGuia={asignacionGuia} accion={accion} pedirEliminar={setBloqueEliminar}/>)}</section>
  {bloqueEliminar?<ConfirmarEliminacion bloque={bloqueEliminar} cargando={accion.isPending} cancelar={()=>setBloqueEliminar(null)} confirmar={()=>accion.mutate(()=>api.delete(`/guias/bloques/${bloqueEliminar._id}`),{onSuccess:()=>setBloqueEliminar(null)})}/>:null}
 </main>;
}

function Bloque({bloque,datos,asignacionGuia,accion,pedirEliminar}:{bloque:any;datos:any;asignacionGuia:Map<string,any>;accion:any;pedirEliminar:(b:any)=>void}){
 const [abierto,setAbierto]=useState(false),[buscar,setBuscar]=useState(""),[nombreNuevo,setNombreNuevo]=useState("");
 const termino=buscar.trim();
 const busquedaQ=useQuery({queryKey:["buscar-usuarios-bloque-admin",bloque._id,termino],queryFn:async()=>(await api.get("/guias/bloques/buscar-usuarios",{params:{bloqueId:bloque._id,buscar:termino}})).data,enabled:abierto&&termino.length>=2,retry:false});
 const detalles=(datos.detalles??[]).filter((d:any)=>String(d.bloqueId?._id??d.bloqueId)===String(bloque._id)),mapa=new Map((datos.fraternos??[]).map((f:any)=>[String(f._id),f]));
 const integrantes=detalles.map((d:any)=>mapa.get(String(d.fraternoId?._id??d.fraternoId))??d.fraternoId),hombres=ordenar(integrantes.filter((f:any)=>genero(f.usuarioId?.sexo)==="HOMBRE")),mujeres=ordenar(integrantes.filter((f:any)=>genero(f.usuarioId?.sexo)==="MUJER"));
 const guias=bloque.guiasIds??[],gh=guias.filter((g:any)=>genero(g.usuarioId?.sexo)==="HOMBRE"),gm=guias.filter((g:any)=>genero(g.usuarioId?.sexo)==="MUJER");
 const resultados=ordenar(busquedaQ.data?.fraternos??[]);
 const moverGuia=(id:string,bloqueId:string|null)=>accion.mutate(()=>api.patch(`/guias/bloques/guias/${id}`,{bloqueId}));
 const quitarRol=(id:string)=>accion.mutate(()=>quitarRolGuia(id));
 const exportar=async(e:React.MouseEvent)=>{e.stopPropagation();const{default:ExcelJS}=await import("exceljs");const libro=new ExcelJS.Workbook(),hoja=libro.addWorksheet("Integrantes");hoja.columns=[{header:"N.º",key:"n",width:8},{header:"Nombre",key:"nombre",width:38},{header:"CI",key:"ci",width:16},{header:"Celular",key:"telefono",width:20,style:{numFmt:"@"}},{header:"Correo",key:"correo",width:30},{header:"Sexo",key:"sexo",width:12},{header:"Código",key:"codigo",width:18},{header:"Pago",key:"pago",width:18},{header:"Polera",key:"polera",width:12},{header:"Chamarra",key:"chamarra",width:12}];ordenar(integrantes).forEach((f:any,i)=>hoja.addRow({n:i+1,nombre:nombre(f),ci:String(f.usuarioId?.ci??""),telefono:String(f.usuarioId?.telefono??""),correo:f.usuarioId?.email??"",sexo:genero(f.usuarioId?.sexo),codigo:f.numeroFraterno??"",pago:pago(f),polera:f.talla?.tallaPolera??"",chamarra:f.talla?.tallaChamarra??""}));hoja.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};hoja.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF74122A"}};const data=await libro.xlsx.writeBuffer(),url=URL.createObjectURL(new Blob([data],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"})),a=document.createElement("a");a.href=url;a.download=`bloque-${bloque.nombre.toLowerCase().replace(/[^a-z0-9]+/g,"-")}.xlsx`;a.click();URL.revokeObjectURL(url)};
 return <article className="overflow-hidden rounded-2xl border bg-white shadow-sm"><button onClick={()=>setAbierto(!abierto)} className="w-full p-5 text-left"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-black text-[#841534]">{bloque.nombre}</h2><p className="text-sm text-slate-500">{guias.length}/4 guías · {integrantes.length}/120 integrantes · {gh.length===2&&gm.length===2?"Equipo completo":"Equipo incompleto"}</p></div><div className="flex items-center gap-3"><span onClick={exportar} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-black text-white">Excel</span><span className="font-black text-[#841534]">{abierto?"Contraer −":"Supervisar +"}</span></div></div><div className="mt-4 grid grid-cols-2 gap-2 lg:grid-cols-5"><M t="Hombres" v={`${hombres.length}/40`}/><M t="Libres H" v={40-hombres.length}/><M t="Mujeres" v={`${mujeres.length}/80`}/><M t="Libres M" v={80-mujeres.length}/><M t="Total" v={`${integrantes.length}/120`}/></div></button>
 {abierto&&<div className="space-y-5 border-t p-5"><form className="flex gap-2" onSubmit={e=>{e.preventDefault();accion.mutate(()=>api.patch(`/guias/bloques/${bloque._id}/nombre`,{nombre:nombreNuevo}))}}><input required value={nombreNuevo} onChange={e=>setNombreNuevo(e.target.value.toUpperCase())} placeholder="Modificar nombre" className="flex-1 rounded-xl border p-3"/><button className="rounded-xl border border-[#841534] px-4 font-bold text-[#841534]">Guardar</button></form>
  <div className="grid gap-4 lg:grid-cols-2"><Guias titulo="Guías hombres" actuales={gh} candidatos={(datos.guias??[]).filter((g:any)=>genero(g.usuarioId?.sexo)==="HOMBRE")} asignacion={asignacionGuia} bloque={bloque} mover={moverGuia} quitarRol={quitarRol}/><Guias titulo="Guías mujeres" actuales={gm} candidatos={(datos.guias??[]).filter((g:any)=>genero(g.usuarioId?.sexo)==="MUJER")} asignacion={asignacionGuia} bloque={bloque} mover={moverGuia} quitarRol={quitarRol}/></div>
  <section><h3 className="font-black text-[#841534]">Buscar y agregar persona registrada</h3><p className="text-xs text-slate-500">Busca entre todos los usuarios de Gestión integral por CI, nombre, apellido o código.</p><input value={buscar} onChange={e=>setBuscar(e.target.value)} placeholder="CI, nombre, apellido o código..." className="mt-2 w-full rounded-xl border p-3"/><div className="mt-3 max-h-80 space-y-2 overflow-y-auto">{termino.length>0&&termino.length<2?<p className="text-sm text-slate-500">Escribe al menos 2 caracteres.</p>:busquedaQ.isFetching?<p className="text-sm text-slate-500">Buscando en Gestión integral...</p>:resultados.map((f:any)=>{const registrado=f.estadoFraterno!=="NO_REGISTRADO",activo=f.estadoFraterno==="ACTIVO",asignado=Boolean(f.asignacion),sexo=genero(f.usuarioId?.sexo),sinSexo=!sexo;const ejecutar=()=>registrado&&activo?api.post("/guias/bloques/integrantes",{bloqueId:bloque._id,fraternoId:f._id}):api.post("/guias/bloques/registrar-fraterno",{bloqueId:bloque._id,usuarioId:f.usuarioId?._id});return <article key={f._id} className="flex flex-col justify-between gap-3 rounded-xl border p-3 sm:flex-row"><div><b>{nombre(f)}</b><p className="text-xs text-slate-500">CI {f.usuarioId?.ci??"—"} · {f.usuarioId?.email??"Sin correo"} · {f.usuarioId?.telefono??"Sin celular"} · {sexo||"Sexo no registrado"}</p><p className="text-xs font-bold">{f.numeroFraterno??f.preregistroId?.numeroPreRegistro??"Sin código de fraterno"} · Estado: {f.estadoFraterno}</p><p className={`text-xs font-bold ${asignado||sinSexo?"text-amber-700":"text-emerald-700"}`}>{asignado?`Ya pertenece al bloque ${f.asignacion.bloqueNombre}`:sinSexo?"Debe registrar su sexo en Gestión integral antes de asignarlo":registrado&&activo?"Disponible para agregar":"Se creará o reactivará su perfil fraterno al agregarlo"}</p></div><button disabled={asignado||sinSexo||accion.isPending} onClick={()=>accion.mutate(ejecutar)} className="rounded-xl bg-emerald-700 px-4 py-2 font-bold text-white disabled:bg-slate-300">{asignado?f.asignacion.esMiBloque?"Ya está en este bloque":`Pertenece a ${f.asignacion.bloqueNombre}`:registrado&&activo?"Agregar al bloque":"Registrar y agregar"}</button></article>})}{termino.length>=2&&!busquedaQ.isFetching&&!resultados.length?<p className="text-sm text-slate-500">{(busquedaQ.error as any)?.response?.data?.error??"No se encontraron usuarios registrados."}</p>:null}</div></section>
  <div className="grid gap-5 xl:grid-cols-2"><Integrantes titulo="Integrantes hombres" items={hombres} detalles={detalles} accion={accion}/><Integrantes titulo="Integrantes mujeres" items={mujeres} detalles={detalles} accion={accion}/></div><div className="border-t pt-5"><button onClick={()=>pedirEliminar(bloque)} className="rounded-xl border border-red-700 px-4 py-2 font-bold text-red-700">Eliminar bloque</button></div>
 </div>}</article>;
}
function M({t,v}:{t:string;v:string|number}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase text-slate-500">{t}</p><b className="text-xl text-[#841534]">{v}</b></div>}
function Guias({titulo,actuales,candidatos,asignacion,bloque,mover,quitarRol}:{titulo:string;actuales:any[];candidatos:any[];asignacion:Map<string,any>;bloque:any;mover:(id:string,b:string|null)=>void;quitarRol:(id:string)=>void}){
 return <div className="rounded-xl bg-slate-50 p-4"><h3 className="font-black">{titulo} ({actuales.length}/2)</h3>
  {actuales.map(g=><div key={g._id} className="mt-2 flex flex-wrap items-center justify-between gap-2 rounded-lg bg-white p-3"><b>{nombre(g)}</b><div className="flex gap-3"><button onClick={()=>confirm("¿Retirar este guía del bloque? Mantendrá su rol de guía.")&&mover(g._id,null)} className="text-xs font-bold text-amber-700">Retirar del bloque</button><button onClick={()=>confirm("¿Quitar completamente el rol de guía? Su perfil, pagos, tallas y datos de fraterno se conservarán.")&&quitarRol(g._id)} className="text-xs font-bold text-red-700">Quitar rol</button></div></div>)}
  {actuales.length<2&&<select defaultValue="" onChange={e=>{if(e.target.value)mover(e.target.value,bloque._id)}} className="mt-3 w-full rounded-xl border p-3"><option value="">Asignar guía...</option>{candidatos.map(g=>{const asignado=asignacion.get(String(g._id));return <option key={g._id} value={g._id} disabled={Boolean(asignado)}>{nombre(g)}{asignado?` (Ya es guía del ${asignado.nombre})`:""}</option>})}</select>}
 </div>
}
function Integrantes({titulo,items,detalles,accion}:{titulo:string;items:any[];detalles:any[];accion:any}){return <section><h3 className="font-black">{titulo} ({items.length})</h3><div className="mt-2 space-y-2">{items.map((f:any,i)=>{const d=detalles.find(x=>String(x.fraternoId?._id??x.fraternoId)===String(f._id));return <article key={f._id} className="flex justify-between gap-3 rounded-xl border p-3"><div><b>{i+1}. {nombre(f)}</b><p className="text-xs text-slate-500">CI {f.usuarioId?.ci??"—"} · {f.usuarioId?.telefono??"Sin celular"} · {pago(f)}</p></div><button onClick={()=>confirm("¿Retirar este integrante del bloque?")&&accion.mutate(()=>api.delete(`/guias/bloques/integrantes/${d._id}`))} className="text-xs font-bold text-red-700">Retirar</button></article>})}</div></section>}
function ConfirmarEliminacion({bloque,cargando,cancelar,confirmar}:{bloque:any;cargando:boolean;cancelar:()=>void;confirmar:()=>void}){return <div role="dialog" aria-modal="true" aria-labelledby="eliminar-bloque-titulo" className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><h2 id="eliminar-bloque-titulo" className="text-xl font-black text-[#841534]">¿Estás seguro de eliminar este bloque?</h2><p className="mt-3 text-slate-600">Se eliminará <b>{bloque.nombre}</b>. Sus guías y fraternos quedarán disponibles y ninguna persona será eliminada.</p><div className="mt-6 flex justify-end gap-3"><button disabled={cargando} onClick={cancelar} className="rounded-xl border px-4 py-2 font-bold">Cancelar</button><button disabled={cargando} onClick={confirmar} className="rounded-xl bg-red-700 px-4 py-2 font-bold text-white disabled:opacity-60">{cargando?"Eliminando...":"Sí, eliminar"}</button></div></div></div>}
