import { Link } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "react-toastify";
import { marcarMiEntradaGuia, marcarMiSalidaGuia, miAsistenciaPostulanteGuia } from "@/api/AsistenciaPostulanteGuiaApi";

const hora = (v?: string) => v ? new Date(v).toLocaleTimeString("es-BO", { hour: "2-digit", minute: "2-digit" }) : "—";
export default function MiAsistenciaPostulanteGuiaView() {
  const qc=useQueryClient(); const consulta=useQuery({queryKey:["mi-asistencia-postulante-guia"],queryFn:miAsistenciaPostulanteGuia,retry:false});
  const entrada=useMutation({mutationFn:marcarMiEntradaGuia,onSuccess:r=>{toast.success(r.message);qc.invalidateQueries({queryKey:["mi-asistencia-postulante-guia"]})},onError:(e:Error)=>toast.error(e.message)});
  const salida=useMutation({mutationFn:marcarMiSalidaGuia,onSuccess:r=>{toast.success(r.message);qc.invalidateQueries({queryKey:["mi-asistencia-postulante-guia"]})},onError:(e:Error)=>toast.error(e.message)});
  const hoy=consulta.data?.hoy;
  return <main className="min-h-screen bg-[#eee8dc] p-4 sm:p-8"><div className="mx-auto max-w-4xl space-y-5"><header className="rounded-3xl bg-[#841534] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#e9cf91]">Proceso de evaluación</p><h1 className="mt-2 text-3xl font-black">Mi asistencia de postulante a guía</h1><Link to="/comunicados" className="mt-4 inline-block rounded-xl border border-white/30 px-4 py-2 text-sm font-bold">← Volver</Link></header>
  {!consulta.data?.habilitado ? <section className="rounded-2xl bg-white p-8 text-center shadow"><div className="text-4xl">🔒</div><h2 className="mt-3 text-xl font-black text-[#74122A]">Asistencia no habilitada</h2><p className="mt-2 text-slate-600">{consulta.data?.motivoNoHabilitado ?? "Comprobando tu postulación..."}</p></section> : <><section className="rounded-2xl bg-white p-6 shadow"><h2 className="text-xl font-black text-[#74122A]">Registro de hoy</h2><div className="mt-4 flex flex-wrap gap-3">{!hoy ? <button onClick={()=>entrada.mutate()} disabled={entrada.isPending} className="rounded-xl bg-[#841534] px-6 py-3 font-bold text-white">Marcar mi entrada</button> : !hoy.horaSalida ? <button onClick={()=>salida.mutate()} disabled={salida.isPending} className="rounded-xl bg-emerald-600 px-6 py-3 font-bold text-white">Marcar mi salida</button> : <span className="rounded-xl bg-emerald-100 px-5 py-3 font-bold text-emerald-800">Asistencia completa</span>}<span className="rounded-xl bg-slate-100 px-5 py-3">Entrada: <b>{hora(hoy?.horaEntrada)}</b> · Salida: <b>{hora(hoy?.horaSalida)}</b></span></div></section><section className="overflow-hidden rounded-2xl bg-white shadow"><h2 className="p-5 text-xl font-black text-[#74122A]">Mi historial</h2><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-sm"><thead className="bg-[#841534] text-white"><tr><th className="p-3 text-left">Fecha</th><th className="p-3 text-left">Entrada</th><th className="p-3 text-left">Salida</th><th className="p-3 text-left">Estado</th></tr></thead><tbody>{consulta.data.asistencias.map(a=><tr key={a._id} className="border-b"><td className="p-3">{a.fechaClave}</td><td className="p-3">{hora(a.horaEntrada)}</td><td className="p-3">{hora(a.horaSalida)}</td><td className="p-3 font-bold">{a.estado}</td></tr>)}</tbody></table></div></section></>}
  </div></main>;
}
