import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "react-toastify";
import api from "@/lib/axios";

const nombre=(r:any)=>{const u=r?.usuarioId??r;return [u?.nombres,u?.apellidoPaterno,u?.apellidoMaterno].filter(Boolean).join(" ")||r?.numeroFraterno||"Sin nombre"};
const genero=(v:any)=>["HOMBRE","MASCULINO","M","VARON","VARÓN"].includes(String(v??"").toUpperCase())?"HOMBRE":["MUJER","FEMENINO","F"].includes(String(v??"").toUpperCase())?"MUJER":"";
const ordenar=<T,>(items:T[])=>[...items].sort((a:any,b:any)=>{const clave=(r:any)=>{const u=r?.usuarioId??r;return [u?.apellidoPaterno,u?.apellidoMaterno,u?.nombres].filter(Boolean).join(" ")};return clave(a).localeCompare(clave(b),"es",{sensitivity:"base"})});
const estadoPago=(f:any)=>!f?.pago?"SIN PAGOS":f.pago.saldo<=0||f.pago.estado==="PAGADA"?"PAGO COMPLETO":f.pago.montoPagado>0?"PAGO PARCIAL":"SIN PAGOS";

export default function MiBloqueGuiaView(){
 const qc=useQueryClient(),[buscar,setBuscar]=useState(""),[modal,setModal]=useState(false),[nombreNuevo,setNombreNuevo]=useState("");
 const q=useQuery({queryKey:["mi-bloque-guia"],queryFn:async()=>(await api.get("/guias/mi-bloque")).data});
 const termino=buscar.trim();
 const busquedaQ=useQuery({queryKey:["buscar-fraternos-mi-bloque",termino],queryFn:async()=>(await api.get("/guias/mi-bloque/buscar-fraternos",{params:{buscar:termino}})).data,enabled:modal&&termino.length>=2,retry:false});
 const accion=useMutation({mutationFn:(fn:()=>Promise<any>)=>fn(),onSuccess:async r=>{toast.success(r.data.message);setModal(false);setBuscar("");await Promise.all([qc.invalidateQueries({queryKey:["mi-bloque-guia"]}),qc.invalidateQueries({queryKey:["buscar-fraternos-mi-bloque"]})])},onError:(e:any)=>toast.error(e.response?.data?.error??"No se pudo actualizar el bloque")});
 const bloque=q.data?.bloque,porId=new Map((q.data?.fraternos??[]).map((f:any)=>[String(f._id),f]));
 const integrantes=(q.data?.detalles??[]).map((d:any)=>porId.get(String(d.fraternoId?._id??d.fraternoId))??d.fraternoId);
 const hombres=ordenar(integrantes.filter((f:any)=>genero(f.usuarioId?.sexo)==="HOMBRE")),mujeres=ordenar(integrantes.filter((f:any)=>genero(f.usuarioId?.sexo)==="MUJER"));
 const resultados=ordenar(busquedaQ.data?.fraternos??[]);
 const exportar=async()=>{const{default:ExcelJS}=await import("exceljs");const libro=new ExcelJS.Workbook(),hoja=libro.addWorksheet("Integrantes");hoja.columns=[{header:"N.º",key:"n",width:8},{header:"Apellidos y nombres",key:"nombre",width:38},{header:"CI",key:"ci",width:16},{header:"Celular",key:"tel",width:20,style:{numFmt:"@"}},{header:"Correo",key:"email",width:32},{header:"Sexo",key:"sexo",width:13},{header:"Código",key:"codigo",width:18},{header:"Estado pago",key:"pago",width:20},{header:"Talla polera",key:"polera",width:15},{header:"Talla chamarra",key:"chamarra",width:17}];ordenar(integrantes).forEach((f:any,i)=>hoja.addRow({n:i+1,nombre:nombre(f),ci:String(f.usuarioId?.ci??""),tel:String(f.usuarioId?.telefono??""),email:f.usuarioId?.email??"",sexo:genero(f.usuarioId?.sexo),codigo:f.numeroFraterno??f.preregistroId?.numeroPreRegistro??"",pago:estadoPago(f),polera:f.talla?.tallaPolera??"",chamarra:f.talla?.tallaChamarra??""}));hoja.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};hoja.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF74122A"}};hoja.autoFilter="A1:J1";const data=await libro.xlsx.writeBuffer(),url=URL.createObjectURL(new Blob([data],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"})),a=document.createElement("a");a.href=url;a.download=`bloque-${bloque.nombre.toLowerCase().replace(/[^a-z0-9]+/g,"-")}.xlsx`;a.click();URL.revokeObjectURL(url)};
 if(q.isLoading)return <p className="p-8">Cargando tu bloque...</p>;if(q.isError)return <p className="rounded-2xl bg-red-50 p-6 text-red-700">{(q.error as any)?.response?.data?.error??"No se pudo cargar tu bloque."}</p>;
 if(!bloque)return <main className="rounded-3xl border border-amber-300 bg-amber-50 p-8 text-center"><h1 className="text-2xl font-black text-amber-900">Aún no tienes un bloque asignado</h1><p className="mt-2 text-amber-800">Administración debe crear el bloque y asignarte como guía.</p></main>;
 const guias=bloque.guiasIds?.length?bloque.guiasIds:[bloque.guiaId].filter(Boolean),gh=guias.filter((g:any)=>genero(g.usuarioId?.sexo)==="HOMBRE"),gm=guias.filter((g:any)=>genero(g.usuarioId?.sexo)==="MUJER");
 return <main className="space-y-5"><header><p className="text-xs font-black uppercase tracking-widest text-[#8F5F2A]">Panel de guía</p><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-black text-[#841534]">Mi bloque</h1><p className="text-slate-500">Agrupación administrativa, sin filas ni posiciones.</p></div><button onClick={()=>void exportar()} className="rounded-xl bg-emerald-700 px-5 py-3 font-black text-white">Exportar Excel</button></div></header>
  <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase text-slate-500">Bloque</p><h2 className="text-2xl font-black text-[#841534]">{bloque.nombre}</h2></div><form className="flex gap-2" onSubmit={e=>{e.preventDefault();if(nombreNuevo.trim())accion.mutate(()=>api.patch("/guias/mi-bloque/nombre",{nombre:nombreNuevo}))}}><input value={nombreNuevo} onChange={e=>setNombreNuevo(e.target.value.toUpperCase())} placeholder="Nuevo nombre" className="rounded-xl border px-3 py-2"/><button className="rounded-xl border border-[#841534] px-4 py-2 font-bold text-[#841534]">Cambiar nombre</button></form></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metrica t="Hombres" v={`${hombres.length} / 40`}/><Metrica t="Disponibles hombres" v={40-hombres.length}/><Metrica t="Mujeres" v={`${mujeres.length} / 80`}/><Metrica t="Disponibles mujeres" v={80-mujeres.length}/><Metrica t="Total" v={`${integrantes.length} / 120`}/></div></section>
  <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-black text-[#841534]">Guías responsables</h2><div className="mt-4 grid gap-4 lg:grid-cols-2"><GrupoGuias titulo="Guías hombres" guias={gh}/><GrupoGuias titulo="Guías mujeres" guias={gm}/></div></section>
  <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black text-[#841534]">Integrantes</h2><p className="text-sm text-slate-500">Solo Administración puede retirar personas.</p></div><button disabled={integrantes.length>=120} onClick={()=>setModal(true)} className="rounded-xl bg-[#841534] px-5 py-3 font-black text-white disabled:opacity-40">Agregar al bloque</button></div><div className="mt-4 grid gap-5 xl:grid-cols-2"><Lista titulo="Integrantes hombres" items={hombres} max={40}/><Lista titulo="Integrantes mujeres" items={mujeres} max={80}/></div></section>
  {modal&&<div className="fixed inset-0 z-[150] grid place-items-center bg-black/60 p-3"><section className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-5"><div className="flex justify-between"><h2 className="text-xl font-black text-[#841534]">Buscar fraterno</h2><button onClick={()=>setModal(false)}>✕</button></div><input autoFocus value={buscar} onChange={e=>setBuscar(e.target.value)} placeholder="Buscar por CI, nombre o código..." className="mt-4 w-full rounded-xl border p-3"/><div className="mt-4 space-y-3">{termino.length<2?<p className="py-8 text-center text-slate-500">Escribe al menos 2 caracteres para buscar.</p>:busquedaQ.isFetching?<p className="py-8 text-center text-slate-500">Buscando fraternos...</p>:resultados.map((f:any)=>{const asignacion=f.asignacion,registrado=f.estadoFraterno!=="NO_REGISTRADO",activo=f.estadoFraterno==="ACTIVO",roles=(f.usuarioId?.roles??[]).map((r:any)=>r.nombre??r.codigo).filter(Boolean).join(", ")||"Usuario";const ejecutar=()=>registrado&&activo?api.post("/guias/mi-bloque/integrantes",{bloqueId:bloque._id,fraternoId:f._id}):api.post("/guias/mi-bloque/registrar-fraterno",{usuarioId:f.usuarioId?._id});return <article key={f._id} className="rounded-xl border p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="font-black">{nombre(f)}</p><p className="text-sm text-slate-600">CI {f.usuarioId?.ci??"—"} · {f.numeroFraterno??f.preregistroId?.numeroPreRegistro??"Sin código"} · {genero(f.usuarioId?.sexo)}</p><p className="text-xs text-slate-500">{f.usuarioId?.email??"Sin correo"} · {f.usuarioId?.telefono??"Sin celular"}</p><p className="text-xs text-slate-500">Rol: {roles} · Estado fraterno: {f.estadoFraterno}</p><p className={`mt-1 text-xs font-bold ${asignacion?"text-amber-700":"text-emerald-700"}`}>{asignacion?`Este fraterno ya pertenece al bloque ${asignacion.bloqueNombre}`:registrado?"Fraterno disponible para agregar":"Usuario encontrado. Regístralo como fraterno para continuar."}</p>{!registrado&&!f.preregistroId?<p className="mt-1 text-xs text-slate-500">Al registrar se creará su preregistro en la gestión actual sin duplicar la cuenta.</p>:null}</div><button disabled={Boolean(asignacion)||accion.isPending} onClick={()=>accion.mutate(ejecutar)} className="rounded-xl bg-emerald-700 px-4 py-2 font-black text-white disabled:bg-slate-300">{asignacion?.esMiBloque?"Este fraterno ya está en tu bloque":asignacion?`Pertenece a ${asignacion.bloqueNombre}`:registrado&&activo?"Agregar a mi bloque":"Registrar como fraterno"}</button></div></article>})}{termino.length>=2&&!busquedaQ.isFetching&&!resultados.length?<p className="py-8 text-center text-slate-500">{(busquedaQ.error as any)?.response?.data?.error??"No hay resultados."}</p>:null}</div></section></div>}
 </main>;
}
function Metrica({t,v}:{t:string;v:string|number}){return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-500">{t}</p><strong className="text-2xl text-[#841534]">{v}</strong></div>}
function GrupoGuias({titulo,guias}:{titulo:string;guias:any[]}){const base=String(import.meta.env.VITE_API_URL||"").replace(/\/api\/?$/,"");return <div className="rounded-xl bg-slate-50 p-4"><div className="flex justify-between"><h3 className="font-black">{titulo}</h3><b>{guias.length}/2</b></div>{guias.map(g=>{const u=g.usuarioId,foto=u?.fotoPerfil?(u.fotoPerfil.startsWith("http")?u.fotoPerfil:`${base}${u.fotoPerfil}`):"";return <article key={g._id} className="mt-2 flex items-center gap-3 rounded-lg bg-white p-3">{foto?<img src={foto} alt={`Foto de ${nombre(g)}`} className="h-12 w-12 rounded-full object-cover"/>:<span className="grid h-12 w-12 place-items-center rounded-full bg-slate-200 font-black text-[#841534]">{nombre(g).charAt(0)}</span>}<div><p className="font-bold">{nombre(g)}</p><p className="text-xs text-slate-500">{u?.telefono||"Celular no registrado"}</p></div></article>})}{!guias.length&&<p className="mt-2 text-sm text-slate-500">Sin guías asignados.</p>}</div>}
function Lista({titulo,items,max}:{titulo:string;items:any[];max:number}){return <div><h3 className="font-black">{titulo} ({items.length}/{max})</h3><div className="mt-3 space-y-2">{items.map((f:any,i)=><article key={f._id} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><div><p className="font-black">{i+1}. {nombre(f)}</p><p className="text-xs text-slate-500">CI {f.usuarioId?.ci??"—"} · {f.usuarioId?.telefono??"Sin celular"}</p></div><span className="h-fit rounded-full bg-amber-50 px-2 py-1 text-[10px] font-black text-amber-900">{estadoPago(f)}</span></div></article>)}{!items.length&&<p className="rounded-xl bg-slate-50 p-5 text-center text-sm text-slate-500">Sin integrantes.</p>}</div></div>}
