import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { toast } from "react-toastify";
import api from "@/lib/axios";

const nombrePersona = (registro: any) => {
  const usuario = registro?.usuarioId;
  return [usuario?.nombres, usuario?.apellidoPaterno, usuario?.apellidoMaterno].filter(Boolean).join(" ") || registro?.numeroFraterno || "Sin nombre";
};
const normalizarGenero = (valor: unknown) => {
  const genero = String(valor ?? "").trim().toUpperCase();
  if (["HOMBRE", "MASCULINO", "VARON", "VARÓN"].includes(genero)) return "HOMBRE";
  if (["MUJER", "FEMENINO"].includes(genero)) return "MUJER";
  return "";
};
const telefonoWhatsApp = (valor: unknown) => {
  const digitos = String(valor ?? "").replace(/\D/g, "").replace(/^0+/, "");
  if (digitos.length === 8) return `591${digitos}`;
  if (digitos.startsWith("591") && digitos.length === 11) return digitos;
  return null;
};
const ordenarPorApellido = (a: any, b: any) => {
  const clave = (detalle: any) => { const u = detalle.fraternoId?.usuarioId; return [u?.apellidoPaterno, u?.apellidoMaterno, u?.nombres].filter(Boolean).join(" "); };
  return clave(a).localeCompare(clave(b), "es", { sensitivity: "base" });
};
export default function MiBloqueGuiaView() {
  const qc = useQueryClient();
  const [nombreBloque, setNombreBloque] = useState("");
  const [fraternoId, setFraternoId] = useState("");
  const [guiaId, setGuiaId] = useState("");
  const [genero, setGenero] = useState<"HOMBRE" | "MUJER">("HOMBRE");
  const [previsualizar, setPrevisualizar] = useState(false);
  const [modalGuia, setModalGuia] = useState(false);
  const [modalFraterno, setModalFraterno] = useState(false);
  const [filtroIntegrantes, setFiltroIntegrantes] = useState<"TODOS" | "HOMBRE" | "MUJER">("TODOS");
  const [detalleMover, setDetalleMover] = useState<any | null>(null);
  const consulta = useQuery({ queryKey: ["mi-bloque-guia"], queryFn: async () => (await api.get("/guias/mi-bloque")).data });
  const ejecutar = useMutation({ mutationFn: (accion: () => Promise<any>) => accion(), onSuccess: async (respuesta) => { toast.success(respuesta.data.message); setFraternoId(""); setGuiaId(""); await qc.invalidateQueries({ queryKey: ["mi-bloque-guia"] }); }, onError: (error: any) => toast.error(error.response?.data?.error ?? "No se pudo actualizar el bloque") });
  const detalleEn = (fila: number, columna: number) => consulta.data?.detalles.find((detalle: any) => detalle.genero === genero && detalle.fila === fila && detalle.columna === columna);
  if (consulta.isLoading) return <p className="p-8">Cargando tu bloque...</p>;
  if (consulta.isError) return <p className="rounded-2xl bg-red-50 p-6 text-red-700">No se pudo cargar el panel. Verifica que administración ya te haya aprobado como guía.</p>;
  const bloque = consulta.data.bloque;
  const guiasBloque = bloque?.guiasIds?.length ? bloque.guiasIds : [consulta.data.guia];
  const esResponsable = String(bloque?.guiaId?._id ?? bloque?.guiaId) === String(consulta.data.guia?._id);
  const capacidad = {
    filasHombres: bloque?.filasHombres ?? 20,
    columnasHombres: bloque?.columnasHombres ?? 2,
    filasMujeres: bloque?.filasMujeres ?? 20,
    columnasMujeres: bloque?.columnasMujeres ?? 4,
  };
  const filas = genero === "HOMBRE" ? capacidad.filasHombres : capacidad.filasMujeres;
  const columnas = genero === "HOMBRE" ? capacidad.columnasHombres : capacidad.columnasMujeres;
  const limiteHombres = consulta.data?.limites?.HOMBRE ?? 40;
  const limiteMujeres = consulta.data?.limites?.MUJER ?? 80;
  const detalles = consulta.data?.detalles ?? [];
  const cantidadHombres = detalles.filter((detalle: any) => detalle.genero === "HOMBRE").length;
  const cantidadMujeres = detalles.filter((detalle: any) => detalle.genero === "MUJER").length;
  const cantidadGenero = genero === "HOMBRE" ? cantidadHombres : cantidadMujeres;
  const limiteGenero = genero === "HOMBRE" ? limiteHombres : limiteMujeres;
  const seccionLlena = cantidadGenero >= Math.min(filas * columnas, limiteGenero);
  const totalCapacidad = limiteHombres + limiteMujeres;
  const bloqueLleno = cantidadHombres >= limiteHombres && cantidadMujeres >= limiteMujeres;
  const fraternoPorId = new Map((consulta.data?.fraternos ?? []).map((fraterno: any) => [String(fraterno._id), fraterno]));
  const obtenerFraterno = (detalle: any) => fraternoPorId.get(String(detalle.fraternoId?._id ?? detalle.fraternoId)) ?? detalle.fraternoId;
  const integrantesFiltrados = [...detalles].filter((detalle: any) => filtroIntegrantes === "TODOS" || detalle.genero === filtroIntegrantes).sort(ordenarPorApellido);
  const exportarExcel = async () => {
    const { default: ExcelJS } = await import("exceljs");
    const libro = new ExcelJS.Workbook();
    const hoja = libro.addWorksheet("Integrantes");
    hoja.columns = [
      { header: "N.º", key: "numero", width: 8 }, { header: "Nombre completo", key: "nombre", width: 36 }, { header: "CI", key: "ci", width: 16 },
      { header: "Sexo", key: "sexo", width: 12 }, { header: "Número de celular", key: "telefono", width: 20, style: { numFmt: "@" } }, { header: "Teléfono WhatsApp", key: "whatsapp", width: 20, style: { numFmt: "@" } },
      { header: "Estado", key: "estado", width: 16 }, { header: "Bloque", key: "bloque", width: 22 }, { header: "Estado de pago", key: "pago", width: 18 }, { header: "Saldo", key: "saldo", width: 14 },
    ];
    [...detalles].sort(ordenarPorApellido).forEach((detalle: any, indice: number) => { const f: any = obtenerFraterno(detalle); const u = f?.usuarioId; const whatsapp = telefonoWhatsApp(u?.telefono); hoja.addRow({ numero: indice + 1, nombre: nombrePersona(f), ci: String(u?.ci ?? ""), sexo: detalle.genero, telefono: String(u?.telefono ?? ""), whatsapp: whatsapp ? `+${whatsapp}` : "", estado: f?.estado ?? "", bloque: bloque.nombre, pago: f?.pago?.estado ?? "SIN CUOTA", saldo: f?.pago?.saldo ?? "" }); });
    hoja.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } }; hoja.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF74122A" } }; hoja.views = [{ state: "frozen", ySplit: 1 }]; hoja.autoFilter = "A1:J1";
    const contenido = await libro.xlsx.writeBuffer(); const url = URL.createObjectURL(new Blob([contenido], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" })); const enlace = document.createElement("a"); enlace.href = url; enlace.download = `bloque-${String(bloque.nombre).toLowerCase().replace(/[^a-z0-9]+/g, "-")}.xlsx`; enlace.click(); URL.revokeObjectURL(url);
  };
  return <div className="space-y-6">
    <header><p className="text-xs font-bold uppercase tracking-widest text-[#8F5F2A]">Panel exclusivo de guías</p><h1 className="text-3xl font-black text-[#841534]">Mi bloque</h1><p className="text-slate-500">Crea un equipo de 3 o 4 guías y organiza a los fraternos por fila y columna.</p></header>
    {!bloque ? <form onSubmit={(evento) => { evento.preventDefault(); ejecutar.mutate(() => api.post("/guias/mi-bloque", { nombre: nombreBloque })); }} className="max-w-2xl rounded-2xl bg-white p-6 shadow"><h2 className="text-xl font-black text-[#841534]">Crear un nuevo bloque</h2><p className="mt-1 text-sm text-slate-500">Serás el guía responsable y después podrás agregar otros 2 o 3 guías.</p><div className="mt-4 flex gap-3"><input required value={nombreBloque} onChange={(evento) => setNombreBloque(evento.target.value.toUpperCase())} placeholder="NOMBRE DEL BLOQUE" className="flex-1 rounded-xl border px-4 py-3"/><button className="rounded-xl bg-[#841534] px-5 font-bold text-white">Crear bloque</button></div></form> : <>
      <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase text-slate-500">Bloque</p><h2 className="text-2xl font-black text-[#841534]">{bloque.nombre}</h2><p className="text-sm text-slate-500">{detalles.length} fraternos posicionados</p></div><span className={`rounded-full px-4 py-2 text-xs font-black ${guiasBloque.length === 4 ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-900"}`}>{guiasBloque.length}/4 GUÍAS</span></div>
        <div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><ResumenCupo titulo="Hombres" valor={`${cantidadHombres} / ${limiteHombres}`}/><ResumenCupo titulo="Mujeres" valor={`${cantidadMujeres} / ${limiteMujeres}`}/><ResumenCupo titulo="Total" valor={`${detalles.length} / ${totalCapacidad}`}/><ResumenCupo titulo="Cupos disponibles" valor={Math.max(0, totalCapacidad - detalles.length)}/></div>
        <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{guiasBloque.map((guia: any) => { const responsable = String(guia._id) === String(bloque.guiaId?._id ?? bloque.guiaId); return <article key={guia._id} className="rounded-xl border bg-slate-50 p-4"><p className="font-black text-slate-800">{nombrePersona(guia)}</p><p className="text-xs text-slate-500">{responsable ? "Guía responsable" : "Guía integrante · solo administración puede moverlo"}</p></article>; })}</div>
        {esResponsable && guiasBloque.length < 4 && <form onSubmit={(evento) => { evento.preventDefault(); if (!guiaId) return toast.info("Selecciona un guía"); ejecutar.mutate(() => api.post("/guias/mi-bloque/guias", { guiaId })); }} className="mt-4 flex flex-col gap-3 sm:flex-row"><button type="button" onClick={() => setModalGuia(true)} className="flex-1 rounded-xl border px-4 py-2.5 text-left font-bold text-slate-700">{guiaId ? nombrePersona(consulta.data.guiasGestion.find((item:any)=>item._id===guiaId)) : "🔎 Buscar y seleccionar otro guía"}</button><button className="rounded-xl bg-[#841534] px-5 py-2.5 font-bold text-white">Agregar guía al bloque</button></form>}
      </section>
      <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h3 className="font-black text-[#841534]">Organización de fraternos</h3><p className="text-sm text-slate-500">Los Guías pueden agregar y organizar; solo Administración puede retirar integrantes.</p></div><div className="flex flex-col gap-2 sm:flex-row"><button type="button" onClick={() => void exportarExcel()} className="rounded-xl bg-emerald-700 px-5 py-2.5 text-sm font-black text-white">Exportar a Excel</button><button type="button" onClick={() => setPrevisualizar(true)} className="rounded-xl border border-[#841534] px-5 py-2.5 text-sm font-black text-[#841534]">👁 Previsualizar e imprimir</button></div></div>
        {bloqueLleno && <div className="mt-4 rounded-xl border border-emerald-300 bg-emerald-100 p-4 text-center font-black text-emerald-900">✅ MI BLOQUE YA ESTÁ LLENO · NO SE PUEDEN AGREGAR MÁS FRATERNOS</div>}
        <div className="mt-4 flex flex-col gap-3 sm:flex-row"><div className="flex rounded-xl bg-slate-100 p-1">{(["HOMBRE", "MUJER"] as const).map((valor) => <button type="button" key={valor} onClick={() => { setGenero(valor); setFraternoId(""); setDetalleMover(null); }} className={`rounded-lg px-4 py-2 text-xs font-black ${genero === valor ? "bg-[#841534] text-white" : "text-slate-600"}`}>{valor === "HOMBRE" ? "Hombres" : "Mujeres"}</button>)}</div><button type="button" disabled={seccionLlena || Boolean(detalleMover)} onClick={() => setModalFraterno(true)} className="min-w-0 flex-1 rounded-xl border px-4 py-2 text-left font-bold text-slate-700 disabled:bg-slate-100">{detalleMover ? `Moviendo: ${nombrePersona(detalleMover.fraternoId)}` : seccionLlena ? `Cupo de ${genero === "HOMBRE" ? "hombres" : "mujeres"} completo: ${limiteGenero}/${limiteGenero}` : fraternoId ? nombrePersona(consulta.data.fraternos.find((item:any)=>item._id===fraternoId)) : "🔎 Buscar principalmente por CI, nombre o registro"}</button></div>
        {detalleMover ? <div className="mt-4 rounded-xl border border-blue-300 bg-blue-50 p-3 text-sm text-blue-900"><strong>Moviendo a {nombrePersona(detalleMover.fraternoId)}</strong><p className="text-xs">Presiona una posición libre o cancela. Un Guía no puede retirar integrantes.</p><button type="button" onClick={()=>setDetalleMover(null)} className="mt-2 rounded-lg border bg-white px-3 py-1.5 text-xs font-bold">Cancelar</button></div> : <p className={`mt-4 rounded-xl p-3 text-xs ${seccionLlena ? "bg-emerald-100 font-bold text-emerald-900" : "bg-amber-50 text-amber-900"}`}>{seccionLlena ? `Cupo de ${genero === "HOMBRE" ? "hombres" : "mujeres"} completo: ${limiteGenero}/${limiteGenero}.` : `Selecciona un fraterno y luego una posición libre. Ocupación: ${cantidadGenero}/${limiteGenero}.`}</p>}</section>
      <ListaIntegrantes detalles={integrantesFiltrados} filtro={filtroIntegrantes} cambiarFiltro={setFiltroIntegrantes} obtenerFraterno={obtenerFraterno}/>
      <section className="overflow-x-auto rounded-2xl border bg-[#292329] p-5 shadow-xl"><div className="mx-auto mb-8 h-3 max-w-3xl rounded-full bg-amber-300 shadow-[0_0_25px_#fcd34d]"/><p className="mb-5 text-center text-xs font-bold uppercase tracking-[.35em] text-amber-200">Frente del bloque</p><div className="mx-auto grid min-w-[620px] max-w-5xl gap-3" style={{ gridTemplateColumns: `repeat(${columnas}, minmax(145px, 1fr))` }}>{Array.from({ length: filas }, (_, indice) => indice + 1).flatMap((fila) => Array.from({ length: columnas }, (_, indice) => indice + 1).map((columna) => { const detalle = detalleEn(fila, columna); const seleccionado = detalleMover?._id===detalle?._id; return <button key={`${fila}-${columna}`} type="button" disabled={!detalle && (!fraternoId && !detalleMover)} onClick={() => { if(detalle){setDetalleMover(detalle);setFraternoId("");return;} if(detalleMover){ejecutar.mutate(()=>api.patch(`/guias/mi-bloque/posiciones/${detalleMover._id}`,{fila,columna}),{onSuccess:()=>setDetalleMover(null)});return;} ejecutar.mutate(() => api.post("/guias/mi-bloque/posiciones", { bloqueId: bloque._id, fraternoId, fila, columna })); }} className={`min-h-20 rounded-xl border p-2 text-left transition disabled:opacity-35 ${seleccionado?"border-blue-300 bg-blue-700 text-white ring-2 ring-blue-300":detalle ? "border-emerald-300 bg-emerald-700 text-white hover:bg-blue-700" : "border-slate-600 bg-slate-800 text-slate-300 hover:border-amber-300"}`}><span className="block text-[10px] font-bold opacity-70">FILA {fila} · COLUMNA {columna}</span><strong className="mt-1 block text-xs">{detalle ? nombrePersona(detalle.fraternoId) : detalleMover?"MOVER AQUÍ":"POSICIÓN LIBRE"}</strong></button>; }))}</div></section>
      {previsualizar && <VistaImpresion bloque={bloque} guias={guiasBloque} detalles={consulta.data.detalles} capacidad={capacidad} cerrar={() => setPrevisualizar(false)}/>} 
      {modalGuia && <ModalBuscar titulo="Buscar guía" placeholder="Nombre o CI del guía..." elementos={consulta.data.guiasGestion.filter((item:any)=>item._id!==consulta.data.guia._id)} nombre={nombrePersona} ci={(item:any)=>item.usuarioId?.ci} estado={(item:any)=>{const asignacion=consulta.data.asignacionesGuias.find((a:any)=>a.guiaId===item._id);return asignacion?{texto:asignacion.bloqueId===bloque._id?"Ya está en tu bloque":`Ya pertenece al bloque ${asignacion.bloqueNombre}`,bloqueado:true}:{texto:"Disponible",bloqueado:false}}} seleccionar={(item:any)=>{setGuiaId(item._id);setModalGuia(false)}} cerrar={()=>setModalGuia(false)}/>} 
      {modalFraterno && <ModalBuscar titulo={`Buscar fraterno · ${genero === "HOMBRE" ? "Hombres" : "Mujeres"}`} placeholder="CI, nombre o número de registro..." elementos={consulta.data.fraternos.filter((item:any)=>normalizarGenero(item.usuarioId?.sexo)===genero)} nombre={nombrePersona} ci={(item:any)=>`${item.usuarioId?.ci??""} ${item.numeroFraterno??""} ${item.preregistroId?.numeroPreRegistro??""}`} estado={(item:any)=>{const asignacion=consulta.data.asignacionesFraternos.find((a:any)=>(a.fraternoId?._id??a.fraternoId)===item._id);const bloqueAsignado=asignacion?.bloqueId;return asignacion?{texto:String(bloqueAsignado?._id??bloqueAsignado)===String(bloque._id)?"Este fraterno ya está en mi bloque.":"Este fraterno ya pertenece a otro bloque.",bloqueado:true}:{texto:"Disponible para este bloque",bloqueado:false}}} seleccionar={(item:any)=>{setFraternoId(item._id);setModalFraterno(false)}} cerrar={()=>setModalFraterno(false)}/>}
    </>}
  </div>;
}

function ResumenCupo({ titulo, valor }: { titulo: string; valor: string | number }) {
  return <div className="rounded-xl border bg-slate-50 p-3"><p className="text-[10px] font-black uppercase tracking-wide text-slate-500">{titulo}</p><p className="mt-1 text-xl font-black text-[#841534]">{valor}</p></div>;
}

function ListaIntegrantes({ detalles, filtro, cambiarFiltro, obtenerFraterno }: { detalles:any[]; filtro:"TODOS"|"HOMBRE"|"MUJER"; cambiarFiltro:(valor:"TODOS"|"HOMBRE"|"MUJER")=>void; obtenerFraterno:(detalle:any)=>any }) {
  return <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-black text-[#841534]">Lista organizada del bloque</h3><p className="text-sm text-slate-500">Orden alfabético por apellido, teléfono, WhatsApp y estado de pago.</p></div><div className="flex rounded-xl bg-slate-100 p-1">{(["TODOS","HOMBRE","MUJER"] as const).map(valor=><button type="button" key={valor} onClick={()=>cambiarFiltro(valor)} className={`rounded-lg px-3 py-2 text-[11px] font-black ${filtro===valor?"bg-[#841534] text-white":"text-slate-600"}`}>{valor==="TODOS"?"Todos":valor==="HOMBRE"?"Hombres":"Mujeres"}</button>)}</div></div>
    <div className="mt-4 grid gap-3 md:hidden">{detalles.map((detalle:any)=>{const f=obtenerFraterno(detalle);const u=f?.usuarioId;const wa=telefonoWhatsApp(u?.telefono);return <article key={detalle._id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><div><p className="font-black text-slate-800">{nombrePersona(f)}</p><p className="text-xs text-slate-500">CI {u?.ci??"—"} · {detalle.genero}</p></div><span className="text-xs font-bold text-[#841534]">F{detalle.fila} C{detalle.columna}</span></div><div className="mt-3 flex flex-wrap items-center gap-2 text-xs"><span className="rounded-full bg-slate-100 px-3 py-1">{u?.telefono||"Sin teléfono"}</span>{wa&&<a href={`https://wa.me/${wa}`} target="_blank" rel="noreferrer" className="rounded-full bg-emerald-100 px-3 py-1 font-bold text-emerald-800">WhatsApp</a>}<span className="rounded-full bg-amber-50 px-3 py-1 font-bold text-amber-900">{f?.pago?.estado??"SIN CUOTA"}</span></div></article>})}</div>
    <div className="mt-4 hidden overflow-x-auto md:block"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-100 text-xs uppercase text-slate-600"><tr><th className="p-3">Apellidos y nombres</th><th className="p-3">CI / registro</th><th className="p-3">Sexo</th><th className="p-3">Posición</th><th className="p-3">Celular</th><th className="p-3">Pago</th></tr></thead><tbody>{detalles.map((detalle:any)=>{const f=obtenerFraterno(detalle);const u=f?.usuarioId;const wa=telefonoWhatsApp(u?.telefono);return <tr key={detalle._id} className="border-b last:border-0"><td className="p-3 font-bold">{nombrePersona(f)}</td><td className="p-3">{u?.ci??"—"}<span className="block text-xs text-slate-500">{f?.numeroFraterno??f?.preregistroId?.numeroPreRegistro??""}</span></td><td className="p-3">{detalle.genero}</td><td className="p-3">Fila {detalle.fila} · Col. {detalle.columna}</td><td className="p-3">{wa?<a href={`https://wa.me/${wa}`} target="_blank" rel="noreferrer" className="font-bold text-emerald-700">{u?.telefono} ↗</a>:u?.telefono??"—"}</td><td className="p-3"><span className="rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-900">{f?.pago?.estado??"SIN CUOTA"}</span></td></tr>})}</tbody></table></div>
    {!detalles.length&&<p className="py-8 text-center text-sm text-slate-500">No hay integrantes para este filtro.</p>}
  </section>;
}

function ModalBuscar({ titulo, placeholder, elementos, nombre, ci, estado, seleccionar, cerrar }: { titulo:string; placeholder:string; elementos:any[]; nombre:(item:any)=>string; ci:(item:any)=>string; estado:(item:any)=>{texto:string;bloqueado:boolean}; seleccionar:(item:any)=>void; cerrar:()=>void }) {
  const [buscar,setBuscar]=useState(""); const texto=buscar.trim().toUpperCase(); const filtrados=elementos.filter(item=>`${nombre(item)} ${ci(item)}`.toUpperCase().includes(texto));
  return <div className="fixed inset-0 z-[110] flex items-center justify-center bg-black/60 p-4"><div className="max-h-[88vh] w-full max-w-2xl overflow-hidden rounded-3xl bg-white shadow-2xl"><header className="flex items-center justify-between bg-[#841534] p-5 text-white"><h2 className="text-xl font-black">{titulo}</h2><button onClick={cerrar} className="h-9 w-9 rounded-full bg-white/15">✕</button></header><div className="p-4"><input autoFocus value={buscar} onChange={e=>setBuscar(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border px-4 py-3 outline-none focus:border-[#841534]"/><div className="mt-4 max-h-[58vh] space-y-2 overflow-y-auto">{filtrados.map(item=>{const situacion=estado(item);return <button type="button" key={item._id} disabled={situacion.bloqueado} onClick={()=>seleccionar(item)} className={`w-full rounded-xl border p-4 text-left ${situacion.bloqueado?"cursor-not-allowed bg-slate-100 opacity-70":"bg-white hover:border-[#841534] hover:bg-[#841534]/5"}`}><div className="flex items-start justify-between gap-3"><div><p className="font-black text-slate-800">{nombre(item)}</p><p className="text-xs text-slate-500">{ci(item)||"Sin CI registrado"}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${situacion.bloqueado?"bg-red-100 text-red-800":"bg-emerald-100 text-emerald-800"}`}>{situacion.bloqueado?"NO DISPONIBLE":"SELECCIONAR"}</span></div><p className={`mt-2 text-xs font-semibold ${situacion.bloqueado?"text-red-700":"text-emerald-700"}`}>{situacion.texto}</p></button>})}{!filtrados.length&&<p className="p-8 text-center text-sm text-slate-500">No se encontraron resultados.</p>}</div></div></div></div>;
}

function VistaImpresion({ bloque, guias, detalles, capacidad, cerrar }: { bloque: any; guias: any[]; detalles: any[]; capacidad: any; cerrar: () => void }) {
  const plano = (genero: "HOMBRE" | "MUJER", filas: number, columnas: number) => <div><h3 className="mb-2 text-center text-sm font-black">{genero === "HOMBRE" ? "HOMBRES" : "MUJERES"} · {filas} FILAS × {columnas} COLUMNAS</h3><div className="grid gap-1" style={{ gridTemplateColumns: `repeat(${columnas}, minmax(0, 1fr))` }}>{Array.from({length:filas},(_,i)=>i+1).flatMap(fila=>Array.from({length:columnas},(_,i)=>i+1).map(columna=>{const detalle=detalles.find(d=>d.genero===genero&&d.fila===fila&&d.columna===columna);return <div key={`${genero}-${fila}-${columna}`} className="min-h-12 rounded border border-slate-400 p-1 text-[9px]"><b>F{fila} · C{columna}</b><br/>{detalle?nombrePersona(detalle.fraternoId):"LIBRE"}</div>}))}</div></div>;
  return <div className="fixed inset-0 z-[100] overflow-auto bg-black/70 p-3 sm:p-8"><div id="vista-impresion-bloque" className="mx-auto max-w-6xl bg-white p-5 text-black sm:p-8"><div className="no-print mb-5 flex justify-end gap-2"><button onClick={cerrar} className="rounded-xl border px-4 py-2 font-bold">Cerrar</button><button onClick={() => window.print()} className="rounded-xl bg-[#841534] px-4 py-2 font-bold text-white">🖨 Imprimir</button></div><header className="border-b-2 border-[#841534] pb-4 text-center"><p className="text-xs font-bold uppercase tracking-widest">Tinkus Puros y Naturales</p><h2 className="text-2xl font-black text-[#841534]">BLOQUE {bloque.nombre}</h2><p className="text-sm">Guías: {guias.map(nombrePersona).join(" · ")}</p></header><div className="mt-6 grid gap-8 lg:grid-cols-2">{plano("HOMBRE",capacidad.filasHombres,capacidad.columnasHombres)}{plano("MUJER",capacidad.filasMujeres,capacidad.columnasMujeres)}</div><p className="mt-6 border-t pt-3 text-xs">Total asignados: {detalles.length} · Capacidad: {capacidad.filasHombres*capacidad.columnasHombres+capacidad.filasMujeres*capacidad.columnasMujeres}</p></div></div>;
}
