export const GRUPOS_PERMISOS = [
  { grupo: "1. Vistas (solo lectura)", items: [["VISTA_DASHBOARD", "Ver dashboard"], ["VISTA_COMUNICADOS", "Ver comunicados"], ["VISTA_PASOS", "Ver biblioteca de pasos"], ["VISTA_CANCIONERO", "Ver cancionero"], ["VISTA_TOKENS", "Ver tokens generados"], ["VISTA_GESTIONES", "Ver gestiones"], ["VISTA_USUARIOS", "Ver usuarios"], ["VISTA_FACULTADES", "Ver integrantes por facultad"], ["VISTA_ROLES", "Ver roles y permisos"], ["VISTA_PREREGISTROS", "Ver preregistros"], ["VISTA_POSTULANTES_GUIA", "Ver postulantes a guía"], ["VISTA_ASISTENCIA_GUIA", "Ver asistencia de postulantes a guía"], ["VISTA_GUIAS_BLOQUES", "Ver guías y bloques"], ["VISTA_MI_BLOQUE_GUIA", "Ver mi bloque como guía"], ["VISTA_DIRECTORIO_BLOQUES", "Ver directorio informativo de bloques"], ["VISTA_INDUMENTARIA", "Ver tallas e indumentaria"], ["VISTA_ANUNCIOS", "Ver anuncios"], ["VISTA_AUDITORIA", "Ver auditoría"], ["VISTA_PAGOS", "Ver pagos"], ["VISTA_ASISTENCIAS", "Ver asistencias"], ["VISTA_FRATERNOS", "Ver fraternos"], ["VISTA_TRASPASOS", "Ver traspasos"], ["VISTA_REPORTES", "Ver reportes"]] },
  { grupo: "2. Usuarios: acciones", items: [["USUARIOS_CREAR", "Crear usuarios"], ["USUARIOS_VER", "Ver datos y documentos privados"], ["USUARIOS_EDITAR", "Editar usuarios"], ["USUARIOS_ELIMINAR", "Eliminar usuarios"], ["USUARIOS_CAMBIAR_ESTADO", "Activar, bloquear o cambiar estado"], ["USUARIOS_RESTABLECER_PASSWORD", "Restablecer contraseña"]] },
  { grupo: "3. Módulos: gestionar y editar", items: [["TOKENS_GESTIONAR", "Generar, anular y eliminar tokens propios no usados"], ["BLOQUES_PROPIOS_CREAR", "Crear su bloque como guía"], ["BLOQUES_PROPIOS_GESTIONAR", "Agregar y organizar fraternos en su bloque"], ["BLOQUES_PROPIOS_EXPORTAR", "Exportar integrantes de su bloque"], ["TALLAS_REGISTRAR", "Escanear QR y registrar únicamente tallas"], ["ROLES_CREAR", "Crear roles"], ["ROLES_VER", "Ver detalle de roles"], ["ROLES_EDITAR", "Editar roles"], ["ROLES_ELIMINAR", "Eliminar roles"], ["GESTIONES_CREAR", "Crear gestiones"], ["GESTIONES_VER", "Ver detalle de gestiones"], ["GESTIONES_EDITAR", "Editar gestiones"], ["GESTIONES_ELIMINAR", "Eliminar gestiones"], ["PREREGISTROS_VER", "Ver detalle de preregistros"], ["PREREGISTROS_EDITAR", "Editar y decidir preregistros"], ["PREREGISTROS_ELIMINAR", "Eliminar preregistros"], ["PAGOS_VER", "Ver detalle de pagos"], ["PAGOS_REVISAR", "Aprobar, observar o rechazar comprobantes"], ["PAGOS_GESTIONAR", "Crear cuotas, dar prórrogas y eliminar pagos"], ["PAGOS_CONFIGURAR", "Editar QR y métodos de pago"], ["GUIAS_GESTIONAR", "Editar postulantes y designar guías"], ["BLOQUES_SUPERVISAR", "Editar bloques y posiciones"], ["ASISTENCIA_GUIA_GESTIONAR", "Registrar asistencia de postulantes a guía"], ["ASISTENCIAS_GESTIONAR", "Registrar asistencias"], ["INDUMENTARIA_GESTIONAR", "Editar tallas, prendas y entregas"], ["FRATERNOS_GESTIONAR", "Editar situación de fraternos"], ["TRASPASOS_GESTIONAR", "Crear y resolver traspasos"], ["ANUNCIOS_GESTIONAR", "Crear, editar y eliminar anuncios"], ["AUDITORIA_VER", "Ver detalle de auditoría"], ["FORMACION_PUBLICAR", "Publicar y retirar pasos o canciones"]] },
  { grupo: "4. Eventos especiales", items: [["VISTA_EVENTOS", "Ver eventos especiales"], ["EVENTOS_GESTIONAR", "Crear, cerrar y registrar asistencia de eventos"]] },
] as const;

export const VISTAS_REQUERIDAS_POR_ACCION: Record<string, string[]> = {
  TOKENS_GESTIONAR: ["VISTA_TOKENS"],
  EVENTOS_GESTIONAR: ["VISTA_EVENTOS"],
  TALLAS_REGISTRAR: [],
  USUARIOS_CREAR: ["VISTA_USUARIOS"], USUARIOS_VER: ["VISTA_USUARIOS"], USUARIOS_EDITAR: ["VISTA_USUARIOS"], USUARIOS_ELIMINAR: ["VISTA_USUARIOS"], USUARIOS_CAMBIAR_ESTADO: ["VISTA_USUARIOS"], USUARIOS_RESTABLECER_PASSWORD: ["VISTA_USUARIOS"],
  ROLES_CREAR: ["VISTA_ROLES"], ROLES_VER: ["VISTA_ROLES"], ROLES_EDITAR: ["VISTA_ROLES"], ROLES_ELIMINAR: ["VISTA_ROLES"],
  GESTIONES_CREAR: ["VISTA_GESTIONES"], GESTIONES_VER: ["VISTA_GESTIONES"], GESTIONES_EDITAR: ["VISTA_GESTIONES"], GESTIONES_ELIMINAR: ["VISTA_GESTIONES"],
  PREREGISTROS_VER: ["VISTA_PREREGISTROS"], PREREGISTROS_EDITAR: ["VISTA_PREREGISTROS"], PREREGISTROS_ELIMINAR: ["VISTA_PREREGISTROS"],
  PAGOS_VER: ["VISTA_PAGOS"], PAGOS_REVISAR: ["VISTA_PAGOS"], PAGOS_GESTIONAR: ["VISTA_PAGOS"], PAGOS_CONFIGURAR: ["VISTA_PAGOS"],
  GUIAS_GESTIONAR: ["VISTA_POSTULANTES_GUIA"], BLOQUES_SUPERVISAR: ["VISTA_GUIAS_BLOQUES"], ASISTENCIA_GUIA_GESTIONAR: ["VISTA_ASISTENCIA_GUIA"], ASISTENCIAS_GESTIONAR: ["VISTA_ASISTENCIAS"],
  INDUMENTARIA_GESTIONAR: ["VISTA_INDUMENTARIA"], FRATERNOS_GESTIONAR: ["VISTA_FRATERNOS"], TRASPASOS_GESTIONAR: ["VISTA_TRASPASOS"], ANUNCIOS_GESTIONAR: ["VISTA_ANUNCIOS"], AUDITORIA_VER: ["VISTA_AUDITORIA"],
  FORMACION_PUBLICAR: ["VISTA_PASOS", "VISTA_CANCIONERO"],
};
