export const PERMISOS_CATALOGO = [
  "VISTA_TOKENS",
  "TOKENS_GESTIONAR", "VISTA_DASHBOARD", "VISTA_COMUNICADOS", "VISTA_GESTIONES", "VISTA_USUARIOS", "VISTA_FACULTADES", "VISTA_ROLES", "VISTA_PREREGISTROS", "VISTA_POSTULANTES_GUIA", "VISTA_ASISTENCIA_GUIA", "VISTA_GUIAS_BLOQUES", "VISTA_INDUMENTARIA", "VISTA_ANUNCIOS", "VISTA_AUDITORIA", "VISTA_PAGOS", "VISTA_ASISTENCIAS", "VISTA_FRATERNOS", "VISTA_TRASPASOS", "VISTA_PASOS", "VISTA_CANCIONERO", "VISTA_REPORTES",
  "USUARIOS_CREAR", "USUARIOS_VER", "USUARIOS_EDITAR", "USUARIOS_ELIMINAR", "USUARIOS_CAMBIAR_ESTADO", "USUARIOS_RESTABLECER_PASSWORD",
  "ROLES_CREAR", "ROLES_VER", "ROLES_EDITAR", "ROLES_ELIMINAR", "GESTIONES_CREAR", "GESTIONES_VER", "GESTIONES_EDITAR", "GESTIONES_ELIMINAR", "PREREGISTROS_VER", "PREREGISTROS_EDITAR", "PREREGISTROS_ELIMINAR",
  "PAGOS_VER", "PAGOS_REVISAR", "PAGOS_GESTIONAR", "PAGOS_CONFIGURAR", "GUIAS_GESTIONAR", "BLOQUES_SUPERVISAR", "ASISTENCIA_GUIA_GESTIONAR", "ASISTENCIAS_GESTIONAR", "INDUMENTARIA_GESTIONAR", "FRATERNOS_GESTIONAR", "TRASPASOS_GESTIONAR", "ANUNCIOS_GESTIONAR", "AUDITORIA_VER", "FORMACION_PUBLICAR",
] as const;

export const PERMISOS_VALIDOS = new Set<string>(PERMISOS_CATALOGO);

const VISTAS_POR_ACCION: Record<string, string[]> = {
  TOKENS_GESTIONAR: ["VISTA_TOKENS"],
  USUARIOS_CREAR: ["VISTA_USUARIOS"], USUARIOS_VER: ["VISTA_USUARIOS"], USUARIOS_EDITAR: ["VISTA_USUARIOS"], USUARIOS_ELIMINAR: ["VISTA_USUARIOS"], USUARIOS_CAMBIAR_ESTADO: ["VISTA_USUARIOS"], USUARIOS_RESTABLECER_PASSWORD: ["VISTA_USUARIOS"],
  ROLES_CREAR: ["VISTA_ROLES"], ROLES_VER: ["VISTA_ROLES"], ROLES_EDITAR: ["VISTA_ROLES"], ROLES_ELIMINAR: ["VISTA_ROLES"],
  GESTIONES_CREAR: ["VISTA_GESTIONES"], GESTIONES_VER: ["VISTA_GESTIONES"], GESTIONES_EDITAR: ["VISTA_GESTIONES"], GESTIONES_ELIMINAR: ["VISTA_GESTIONES"],
  PREREGISTROS_VER: ["VISTA_PREREGISTROS"], PREREGISTROS_EDITAR: ["VISTA_PREREGISTROS"], PREREGISTROS_ELIMINAR: ["VISTA_PREREGISTROS"],
  PAGOS_VER: ["VISTA_PAGOS"], PAGOS_REVISAR: ["VISTA_PAGOS"], PAGOS_GESTIONAR: ["VISTA_PAGOS"], PAGOS_CONFIGURAR: ["VISTA_PAGOS"],
  GUIAS_GESTIONAR: ["VISTA_POSTULANTES_GUIA"], BLOQUES_SUPERVISAR: ["VISTA_GUIAS_BLOQUES"], ASISTENCIA_GUIA_GESTIONAR: ["VISTA_ASISTENCIA_GUIA"], ASISTENCIAS_GESTIONAR: ["VISTA_ASISTENCIAS"],
  INDUMENTARIA_GESTIONAR: ["VISTA_INDUMENTARIA"], FRATERNOS_GESTIONAR: ["VISTA_FRATERNOS"], TRASPASOS_GESTIONAR: ["VISTA_TRASPASOS"], ANUNCIOS_GESTIONAR: ["VISTA_ANUNCIOS"], AUDITORIA_VER: ["VISTA_AUDITORIA"], FORMACION_PUBLICAR: ["VISTA_PASOS", "VISTA_CANCIONERO"],
};

export function normalizarPermisosRol(entrada: unknown): string[] {
  const permisos = new Set(Array.isArray(entrada) ? entrada.map((permiso) => String(permiso).trim().toUpperCase()) : []);
  for (const permiso of Array.from(permisos)) for (const vista of VISTAS_POR_ACCION[permiso] ?? []) permisos.add(vista);
  return Array.from(permisos);
}
