import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "react-toastify";
import { Link, useSearchParams } from "react-router-dom";
import { enviarFraternoAListaEspera, listarFraternos } from "@/api/FraternoApi";
import UsuarioMiniatura from "@/components/UsuarioMiniatura";
import type { Fraterno, EstadoTerminosFraterno } from "@/types/FraternoType";

const API=String(import.meta.env.VITE_API_URL||"").replace(/\/api\/?$/,"");
const etiquetaTerminos:Record<EstadoTerminosFraterno,string>={ACEPTADOS:"✅ ACEPTADOS",PENDIENTE:"⚠️ PENDIENTE",NO_ACEPTADOS:"❌ NO ACEPTADOS",REQUIERE_NUEVA_ACEPTACION:"🔄 REQUIERE NUEVA ACEPTACIÓN"};
const estiloPago:Record<string,string>={SALDADO:"bg-emerald-100 text-emerald-800",PAGO_PARCIAL:"bg-orange-100 text-orange-800",EN_VERIFICACION:"bg-blue-100 text-blue-800",OBSERVADO:"bg-amber-100 text-amber-900",RECHAZADO:"bg-red-100 text-red-800",VENCIDO:"bg-red-100 text-red-800",PRORROGA:"bg-purple-100 text-purple-800",SIN_PAGO:"bg-slate-100 text-slate-700"};
const fecha=(valor?:string|null)=>valor?new Date(valor).toLocaleString("es-BO"):"—";

export default function FraternoView(){
 const [parametros]=useSearchParams();
 const [buscar,setBuscar]=useState(()=>parametros.get("buscar")??""),[terminos,setTerminos]=useState("TODOS"),[pago,setPago]=useState("TODOS"),[situacion,setSituacion]=useState("TODOS"),[limite,setLimite]=useState(()=>innerWidth<640?5:20),[pagina,setPagina]=useState(1),[seleccionado,setSeleccionado]=useState<Fraterno|null>(null);
 const consulta=useQuery({queryKey:["fraternos"],queryFn:listarFraternos});
 const datos=useMemo(()=>(consulta.data?.fraternos??[]).filter(f=>{const u=typeof f.usuarioId==="object"?f.usuarioId:null;const coincide=`${f.numeroFraterno} ${u?.nombres} ${u?.apellidoPaterno} ${u?.ci}`.toLowerCase().includes(buscar.toLowerCase());return coincide&&(terminos==="TODOS"||f.terminos?.estado===terminos)&&(pago==="TODOS"||f.estadoPago===pago)&&(situacion==="TODOS"||(f.situacion??f.estado)===situacion)}),[consulta.data,buscar,terminos,pago,situacion]);
 const paginas=Math.max(1,Math.ceil(datos.length/limite)),filas=datos.slice((pagina-1)*limite,pagina*limite);
 return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[.2em] text-[#8F5F2A]">Membresía institucional</p><h1 className="text-3xl font-black text-[#74122A]">Fraternos</h1><p className="text-sm text-[#735f55]">Control financiero, cupos y evidencia de aceptación.</p></header>
 <div className="grid gap-3 rounded-2xl bg-white p-4 lg:grid-cols-[1fr_190px_210px_190px_120px]"><input className="input-preregistro" type="search" placeholder="Buscar nombre, CI o número..." value={buscar} onChange={e=>{setBuscar(e.target.value);setPagina(1)}}/><select className="input-preregistro" value={pago} onChange={e=>{setPago(e.target.value);setPagina(1)}}><option value="TODOS">Todos los pagos</option>{["SIN_PAGO","EN_VERIFICACION","OBSERVADO","RECHAZADO","PAGO_PARCIAL","PRORROGA","VENCIDO","SALDADO"].map(x=><option key={x}>{x}</option>)}</select><select className="input-preregistro" value={terminos} onChange={e=>{setTerminos(e.target.value);setPagina(1)}}><option value="TODOS">Todos los términos</option><option value="ACEPTADOS">Aceptados</option><option value="PENDIENTE">Pendientes</option><option value="REQUIERE_NUEVA_ACEPTACION">Requieren nueva aceptación</option></select><select className="input-preregistro" value={situacion} onChange={e=>{setSituacion(e.target.value);setPagina(1)}}><option value="TODOS">Todas las situaciones</option><option value="ACTIVO">Activos</option><option value="LISTA_ESPERA">Lista de espera</option><option value="INACTIVO">Inactivos</option><option value="RETIRADO">Retirados</option></select><select className="input-preregistro" value={limite} onChange={e=>setLimite(+e.target.value)}>{[5,10,20,50].map(n=><option key={n} value={n}>{n} filas</option>)}</select></div>
 <div className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-left text-sm"><thead className="bg-[#74122A] text-white"><tr>{["N.º fraterno","Nombre","CI","Gestión","Ingreso","Pago","Términos","Situación","Cupo","Acciones"].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{filas.map(f=>{const u=typeof f.usuarioId==="object"?f.usuarioId:null,g=typeof f.gestionId==="object"?f.gestionId:null;return <tr className="border-b" key={f._id}><td className="p-4 font-bold text-[#74122A]">{f.numeroFraterno}</td><td className="p-4">{u?<div className="flex items-center gap-3"><UsuarioMiniatura usuario={u}/><b>{u.nombres} {u.apellidoPaterno}</b></div>:"—"}</td><td className="p-4">{u?.ci}</td><td className="p-4">{g?.nombre}</td><td className="p-4">{new Date(f.fechaIngreso).toLocaleDateString("es-BO")}</td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${estiloPago[f.estadoPago??""]??"bg-slate-100"}`}>{f.estadoPago?.replaceAll("_"," ")}</span></td><td className="p-4 text-xs font-bold">{etiquetaTerminos[f.terminos?.estado??"PENDIENTE"]}</td><td className="p-4 font-bold">{f.situacion}</td><td className="p-4">{f.ocupaCupo?"🟢 OCUPA":"⚪ LIBRE"}</td><td className="p-4"><button onClick={()=>setSeleccionado(f)} className="rounded-lg bg-[#74122A] px-4 py-2 font-bold text-white">Gestionar</button></td></tr>})}</tbody></table></div><div className="flex justify-between p-4 text-sm"><span>Página {pagina} de {paginas} · {datos.length} registros</span><div className="flex gap-2"><button disabled={pagina===1} onClick={()=>setPagina(p=>p-1)}>Anterior</button><button disabled={pagina===paginas} onClick={()=>setPagina(p=>p+1)}>Siguiente</button></div></div></div>{seleccionado&&<Modal fraterno={seleccionado} cerrar={()=>setSeleccionado(null)}/>}</div>;
}

function Modal({fraterno,cerrar}:{fraterno:Fraterno;cerrar:()=>void}){const [verTerminos,setVerTerminos]=useState(false),u=typeof fraterno.usuarioId==="object"?fraterno.usuarioId:null,g=typeof fraterno.gestionId==="object"?fraterno.gestionId:null,t=fraterno.terminos;return <div className="fixed inset-0 z-[130] overflow-y-auto bg-black/65 p-3"><section className="mx-auto my-4 w-full max-w-3xl overflow-hidden rounded-3xl bg-white shadow-2xl"><header className="bg-[#74122A] p-5 text-white"><button onClick={cerrar} className="float-right rounded-full bg-white/15 px-3 py-2">✕</button><h2 className="text-2xl font-black">Gestionar fraterno</h2><p>{fraterno.numeroFraterno} · {u?.nombres} {u?.apellidoPaterno}</p><p className="text-sm text-white/80">CI: {u?.ci}</p></header><div className="max-h-[80dvh] space-y-5 overflow-y-auto p-5">
 <section className="grid gap-3 sm:grid-cols-3"><Dato titulo="Situación" valor={fraterno.situacion??fraterno.estado}/><Dato titulo="Estado financiero" valor={fraterno.estadoPago?.replaceAll("_"," ")??"SIN PAGO"}/><Dato titulo="Cupo" valor={fraterno.ocupaCupo?"OCUPANDO CUPO":"NO OCUPA CUPO"}/><Dato titulo="Pagado" valor={`Bs ${fraterno.cuota?.montoPagado??0}`}/><Dato titulo="Saldo" valor={`Bs ${fraterno.cuota?.saldo??0}`}/><Dato titulo="Tiempo restante" valor={fraterno.plazo?.horasRestantes==null?"Inicia al aceptar términos":`${fraterno.plazo.horasRestantes} horas`}/></section>
 <section><h3 className="font-black text-[#74122A]">CUOTAS Y COMPROBANTES</h3><div className="mt-3 space-y-3">{fraterno.pagos?.map(p=><article key={p._id} className="rounded-xl border p-4"><div className="flex justify-between"><b>Pago {p.numeroPago} · Bs {p.monto}</b><span className="font-bold">{p.estadoRevision}</span></div><p className="text-sm">Fecha: {fecha(p.fechaPago)} · Método: {p.metodoPago}</p>{p.observacionRevision&&<p className="mt-2 text-sm text-amber-800">Observación: {p.observacionRevision}</p>}{p.baucherImagen&&<a className="mt-2 inline-block font-bold text-blue-700" href={`${API}${p.baucherImagen}`} target="_blank" rel="noreferrer">Ver comprobante</a>}</article>)}{!fraterno.pagos?.length&&<p className="rounded-xl bg-slate-50 p-4">Todavía no existen pagos.</p>}</div>{fraterno.cuota?.saldo?<Link to={`/cuotas/${fraterno.cuota._id}`} className="mt-3 inline-block rounded-xl bg-amber-600 px-4 py-2 font-bold text-white">Dar prórroga / gestionar cuota</Link>:null}</section>
 <section className="rounded-2xl border border-emerald-200 p-4"><h3 className="font-black text-[#74122A]">TÉRMINOS Y CONDICIONES</h3><p className="mt-2 font-bold">{etiquetaTerminos[t?.estado??"PENDIENTE"]}</p>{t?.estado==="PENDIENTE"?<p className="mt-2 text-amber-800">El fraterno todavía no aceptó los términos y condiciones.</p>:<div className="mt-2 grid gap-2 sm:grid-cols-2"><Dato titulo="Versión aceptada" valor={t?.versionAceptada?`${g?.anio??"Gestión"}.${t.versionAceptada}`:"—"}/><Dato titulo="Versión vigente" valor={t?.versionVigente?`${g?.anio??"Gestión"}.${t.versionVigente}`:"—"}/><Dato titulo="Fecha de aceptación" valor={fecha(t?.fechaAceptacion)}/><Dato titulo="Gestión" valor={String(g?.anio??g?.nombre??"—")}/></div>}{t?.contenidoAceptado&&<button onClick={()=>setVerTerminos(true)} className="mt-3 rounded-xl border border-[#74122A] px-4 py-2 font-bold text-[#74122A]">Ver términos aceptados</button>}</section>
 <AccionesAdministrativas fraterno={fraterno} cerrar={cerrar}/>
 <section><h3 className="font-black text-[#74122A]">HISTORIAL</h3>{t?.historial.map(h=><p key={`${h.version}-${h.fechaAceptacion}`} className="mt-2 rounded-lg bg-slate-50 p-3 text-sm">{fecha(h.fechaAceptacion)} · Términos aceptados · Versión {g?.anio}.{h.version}</p>)}</section></div></section>{verTerminos&&<div className="fixed inset-0 z-[140] grid place-items-center bg-black/70 p-4"><section className="max-h-[90dvh] w-full max-w-xl overflow-y-auto rounded-3xl bg-white p-6"><button onClick={()=>setVerTerminos(false)} className="float-right">✕</button><h3 className="text-xl font-black text-[#74122A]">Términos aceptados</h3><p className="mt-1 text-sm">Versión {g?.anio}.{t?.versionAceptada} · Solo lectura</p><div className="mt-4 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm leading-6">{t?.contenidoAceptado}</div><button onClick={()=>setVerTerminos(false)} className="mt-4 w-full rounded-xl bg-[#74122A] p-3 font-bold text-white">Cerrar</button></section></div>}</div>}
export function GestionarFraternoModal({fraterno,cerrar}:{fraterno:Fraterno;cerrar:()=>void}){return <Modal fraterno={fraterno} cerrar={cerrar}/>}
function Dato({titulo,valor}:{titulo:string;valor:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-500">{titulo}</p><p className="mt-1 font-black text-slate-800">{valor}</p></div>}
function AccionesAdministrativas({fraterno,cerrar}:{fraterno:Fraterno;cerrar:()=>void}){const qc=useQueryClient();const mover=useMutation({mutationFn:(motivo:string)=>enviarFraternoAListaEspera(fraterno._id,motivo),onSuccess:async r=>{toast.success(r.message);await qc.invalidateQueries({queryKey:["fraternos"]});cerrar()},onError:(e:Error)=>toast.error(e.message)});const enviar=()=>{const motivo=prompt("Motivo para enviar a lista de espera y liberar su cupo:","El postulante informó que ya no participará");if(motivo?.trim())mover.mutate(motivo)};return <section className="rounded-2xl border border-red-200 bg-red-50 p-4"><h3 className="font-black text-[#74122A]">ACCIONES ADMINISTRATIVAS</h3><p className="mt-1 text-sm text-red-800">Enviar a lista de espera libera el cupo para otro postulante y queda registrado en auditoría.</p><div className="mt-3 flex flex-wrap gap-3">{(fraterno.situacion??fraterno.estado)!=="LISTA_ESPERA"&&<button disabled={mover.isPending} onClick={enviar} className="rounded-xl bg-red-700 px-4 py-3 font-bold text-white disabled:opacity-50">{mover.isPending?"Liberando cupo...":"Enviar a lista de espera"}</button>}<Link to="/traspasos" className="rounded-xl border border-[#74122A] bg-white px-4 py-3 font-bold text-[#74122A]">Ceder cupo a otra persona</Link></div></section>}
