import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { listarFraternos } from "@/api/FraternoApi";
import UsuarioMiniatura from "@/components/UsuarioMiniatura";
export default function FraternoView() {
  const [buscar,setBuscar]=useState(""); const [limite,setLimite]=useState(()=>innerWidth<640?5:innerWidth<1280?10:20); const [pagina,setPagina]=useState(1); const consulta=useQuery({queryKey:["fraternos"],queryFn:listarFraternos});
  const datos=useMemo(()=>(consulta.data?.fraternos??[]).filter(f=>{const u=typeof f.usuarioId==="object"?f.usuarioId:null;return `${f.numeroFraterno} ${u?.nombres} ${u?.apellidoPaterno} ${u?.ci}`.toLowerCase().includes(buscar.toLowerCase())}),[consulta.data,buscar]); const paginas=Math.max(1,Math.ceil(datos.length/limite)); const filas=datos.slice((pagina-1)*limite,pagina*limite);
  return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[.2em] text-[#8F5F2A]">Membresía institucional</p><h1 className="text-3xl font-black text-[#74122A]">Fraternos</h1><p className="text-sm text-[#735f55]">Se generan automáticamente al completar y verificar la cuota.</p></header><div className="grid gap-3 rounded-2xl bg-white p-4 sm:grid-cols-[1fr_auto]"><input className="input-preregistro" type="search" placeholder="Buscar nombre, CI o número..." value={buscar} onChange={e=>{setBuscar(e.target.value);setPagina(1)}}/><select className="input-preregistro" value={limite} onChange={e=>{setLimite(+e.target.value);setPagina(1)}}>{[5,10,20,50].map(n=><option key={n} value={n}>{n} filas</option>)}</select></div><div className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#74122A] text-white"><tr>{["N.º fraterno","Nombre","CI","Gestión","Ingreso","Estado"].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{filas.map(f=>{const u=typeof f.usuarioId==="object"?f.usuarioId:null;const g=typeof f.gestionId==="object"?f.gestionId:null;return <tr className="border-b" key={f._id}><td className="p-4 font-bold text-[#74122A]">{f.numeroFraterno}</td><td className="p-4">{u?<div className="flex items-center gap-3"><UsuarioMiniatura usuario={u}/><span className="font-semibold">{u.nombres} {u.apellidoPaterno}</span></div>:"—"}</td><td className="p-4">{u?.ci}</td><td className="p-4">{g?.nombre}</td><td className="p-4">{new Date(f.fechaIngreso).toLocaleDateString("es-BO")}</td><td className="p-4">{f.estado}</td></tr>})}</tbody></table></div><div className="flex items-center justify-between p-4 text-sm"><span>Página {pagina} de {paginas} · {datos.length} registros</span><div className="flex gap-2"><button className="rounded-lg border px-3 py-2" disabled={pagina===1} onClick={()=>setPagina(p=>p-1)}>Anterior</button><button className="rounded-lg border px-3 py-2" disabled={pagina===paginas} onClick={()=>setPagina(p=>p+1)}>Siguiente</button></div></div></div></div>;
}
