import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useSearchParams } from "react-router-dom";
import { toast } from "react-toastify";
import { crearTraspaso, listarTraspasos } from "@/api/FraternoApi";

export default function TraspasoView() {
  const [params] = useSearchParams(); const qc=useQueryClient(); const [form,setForm]=useState({ preregistroId: params.get("preregistroId")??"", usuarioDestinoId:"", motivo:"", observacion:"" }); const [buscar,setBuscar]=useState(""); const [limite,setLimite]=useState(innerWidth<640?5:10); const [pagina,setPagina]=useState(1);
  const consulta=useQuery({queryKey:["traspasos"],queryFn:listarTraspasos}); const mutacion=useMutation({mutationFn:crearTraspaso,onSuccess:async(d)=>{toast.success(d.message);setForm({preregistroId:"",usuarioDestinoId:"",motivo:"",observacion:""});await qc.invalidateQueries({queryKey:["traspasos"]});},onError:(e)=>toast.error(e.message)});
  const datos=useMemo(()=>(consulta.data?.traspasos??[]).filter(t=>{const o=typeof t.usuarioOrigenId==="object"?t.usuarioOrigenId:null;const d=typeof t.usuarioDestinoId==="object"?t.usuarioDestinoId:null;return `${o?.nombres} ${o?.ci} ${d?.nombres} ${d?.ci} ${t.motivo}`.toLowerCase().includes(buscar.toLowerCase())}),[consulta.data,buscar]); const paginas=Math.max(1,Math.ceil(datos.length/limite));
  return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[.2em] text-[#8F5F2A]">Administración de cupos</p><h1 className="text-3xl font-black text-[#74122A]">Traspasos</h1><p className="text-sm text-[#735f55]">Cambia el titular y conserva cuota, pagos y avance; no copia identidad ni documentos.</p></header><form onSubmit={(e)=>{e.preventDefault();mutacion.mutate(form)}} className="grid gap-3 rounded-2xl bg-white p-4 lg:grid-cols-2"><input required className="input-preregistro" placeholder="ID del preregistro" value={form.preregistroId} onChange={e=>setForm({...form,preregistroId:e.target.value})}/><input required className="input-preregistro" placeholder="ID del nuevo perfil de usuario" value={form.usuarioDestinoId} onChange={e=>setForm({...form,usuarioDestinoId:e.target.value})}/><input required className="input-preregistro" placeholder="Motivo del traspaso" value={form.motivo} onChange={e=>setForm({...form,motivo:e.target.value})}/><input className="input-preregistro" placeholder="Observación" value={form.observacion} onChange={e=>setForm({...form,observacion:e.target.value})}/><button disabled={mutacion.isPending} className="rounded-xl bg-[#74122A] p-3 font-bold text-white lg:col-span-2">{mutacion.isPending?"Traspasando...":"Confirmar traspaso"}</button></form><div className="grid gap-3 rounded-2xl bg-white p-4 sm:grid-cols-[1fr_auto]"><input className="input-preregistro" type="search" placeholder="Buscar titular, CI o motivo..." value={buscar} onChange={e=>{setBuscar(e.target.value);setPagina(1)}}/><select className="input-preregistro" value={limite} onChange={e=>{setLimite(+e.target.value);setPagina(1)}}>{[5,10,20,50].map(n=><option key={n}>{n}</option>)}</select></div><div className="overflow-x-auto rounded-2xl bg-white"><table className="w-full min-w-[900px] text-sm"><thead className="bg-[#74122A] text-white"><tr>{["Origen","Destino","Pagado","Saldo","Motivo","Fecha"].map(x=><th className="p-4 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{datos.slice((pagina-1)*limite,pagina*limite).map(t=>{const o=typeof t.usuarioOrigenId==="object"?t.usuarioOrigenId:null;const d=typeof t.usuarioDestinoId==="object"?t.usuarioDestinoId:null;return <tr className="border-b" key={t._id}><td className="p-4">{o?.nombres} {o?.apellidoPaterno}<small className="block">{o?.ci}</small></td><td className="p-4">{d?.nombres} {d?.apellidoPaterno}<small className="block">{d?.ci}</small></td><td className="p-4">Bs {t.montoPagadoAlTraspaso}</td><td className="p-4">Bs {t.saldoAlTraspaso}</td><td className="p-4">{t.motivo}</td><td className="p-4">{new Date(t.fechaSolicitud).toLocaleDateString("es-BO")}</td></tr>})}</tbody></table><div className="flex justify-between p-4"><span>Página {pagina} de {paginas}</span><div className="flex gap-2"><button disabled={pagina===1} onClick={()=>setPagina(p=>p-1)}>Anterior</button><button disabled={pagina===paginas} onClick={()=>setPagina(p=>p+1)}>Siguiente</button></div></div></div></div>;
}
