import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import type { Worksheet } from "exceljs";
import { obtenerReporteTallasPrimeraCuota, type PersonaTallaCuota, type ResumenTallaCuota } from "@/api/ReporteApi";

type Filtros = { sexo: string; talla: string; prenda: string; tallaValor: string; pago: string; verificacion: string; estado: string; rol: string; bloque: string; buscar: string };
const inicial: Filtros = { sexo: "TODOS", talla: "TODOS", prenda: "TODAS", tallaValor: "TODAS", pago: "TODOS", verificacion: "TODOS", estado: "TODOS", rol: "TODOS", bloque: "TODOS", buscar: "" };
const columnas = ["N.º", "Nombre completo", "CI", "Código", "Sexo", "Teléfono", "WhatsApp", "Correo", "Roles", "Tipo de registro", "Estado usuario", "Estado inscripción", "Bloque", "Asignación", "Plan pagos", "Número cuotas", "Cuotas pagadas", "Cuotas pendientes", "Cuotas por verificar", "Monto registrado", "Monto verificado", "Total pagado", "Saldo pendiente", "Estado de pago", "Estado de verificación", "Talla polera", "Talla chamarra", "Estado de talla", "Fecha último pago", "Fecha registro", "Prioridad", "Motivo seguimiento", "Estado general"];
const fila = (p: PersonaTallaCuota, indice: number) => [indice + 1, p.nombre, p.ci, p.codigoFraterno || "SIN REGISTRO", p.sexo, p.telefono, p.whatsapp ?? "", p.correo, p.roles.join(" / ") || "SIN ROL", p.tipoRegistro, p.estadoUsuario, p.estadoInscripcion, p.bloque, p.asignacion, p.planPagos, p.numeroCuotas, p.cuotasPagadas, p.cuotasPendientes, p.cuotasPorVerificar, p.montoRegistradoTotal, p.montoVerificadoTotal, p.totalPagado, p.saldoTotal, p.estadoPagoReporte, p.estadoVerificacionPago, p.tallaPolera ?? (p.participante ? "SIN REGISTRAR" : "NO APLICA"), p.tallaChamarra ?? (p.participante ? "SIN REGISTRAR" : "NO APLICA"), p.estadoMedicion, p.fechaUltimoPago ? new Date(p.fechaUltimoPago).toLocaleDateString("es-BO") : "", p.fechaRegistro ? new Date(p.fechaRegistro).toLocaleDateString("es-BO") : "", p.prioridadSeguimiento, p.motivoSeguimiento, p.estadoGeneral];
const columnasTallasPagos = ["N.º", "Nombre completo", "CI", "Sexo", "Teléfono", "WhatsApp", "Correo", "Roles", "Bloque", "Asignación", "Talla polera", "Talla chamarra", "Estado de talla", "Estado de pago", "Estado de verificación", "Cuotas pagadas", "Cuotas pendientes", "Monto registrado", "Monto verificado", "Total pagado", "Saldo pendiente"];
const filaTallasPagos = (p: PersonaTallaCuota, indice: number) => [indice + 1, p.nombre, p.ci, p.sexo, p.telefono, p.whatsapp ?? "", p.correo, p.roles.join(" / ") || "SIN ROL", p.bloque, p.asignacion, p.tallaPolera ?? "SIN REGISTRAR", p.tallaChamarra ?? "SIN REGISTRAR", p.estadoMedicion, p.estadoPagoReporte, p.estadoVerificacionPago, p.cuotasPagadas, p.cuotasPendientes, p.montoRegistradoTotal, p.montoVerificadoTotal, p.totalPagado, p.saldoTotal];
const columnaExcel = (numero: number) => { let resultado = ""; for (let n = numero; n > 0; n = Math.floor((n - 1) / 26)) resultado = String.fromCharCode(65 + ((n - 1) % 26)) + resultado; return resultado; };
const faltaTalla = (p: PersonaTallaCuota) => p.pendienteTalla === "AMBAS" ? "POLERA Y CHAMARRA" : p.pendienteTalla ?? "NINGUNA";
const estadoAdministrativoSinTalla = (p: PersonaTallaCuota) => {
  if (p.pendienteTalla === "POLERA") return "SOLO FALTA POLERA";
  if (p.pendienteTalla === "CHAMARRA") return "SOLO FALTA CHAMARRA";
  if (p.verificacionPrimeraCuota === "VERIFICADO") return "PRIMERA CUOTA VERIFICADA + SIN TALLA";
  if (p.estadoPagoReporte === "PENDIENTE DE VERIFICACIÓN") return "PRIMERA CUOTA PENDIENTE + SIN TALLA";
  if (p.estadoPagoReporte === "PAGO PARCIAL") return "PAGO PARCIAL + SIN TALLA";
  return "SIN PAGO + SIN TALLA";
};
const columnasSinTalla = ["N.º", "Nombre completo", "CI", "Sexo", "Teléfono", "WhatsApp", "Correo", "Roles", "Bloque", "Asignación", "Talla polera", "Talla chamarra", "Qué talla falta", "Estado medición", "Estado primera cuota", "Estado verificación", "Monto primera cuota", "Monto registrado", "Monto verificado", "Cuotas pagadas", "Saldo pendiente", "Estado general"];
const filaSinTalla = (p: PersonaTallaCuota, i: number) => [i + 1, p.nombre, p.ci, p.sexo, p.telefono, p.whatsapp ?? "", p.correo, p.roles.join(" / ") || "SIN ROL", p.bloque, p.asignacion, p.tallaPolera ?? "SIN REGISTRAR", p.tallaChamarra ?? "SIN REGISTRAR", faltaTalla(p), p.pendienteTalla === "AMBAS" ? "SIN NINGUNA TALLA" : "MEDICIÓN INCOMPLETA", p.primeraCuota, p.verificacionPrimeraCuota, p.montoPrimeraCuota, p.montoRegistradoPrimeraCuota, p.montoVerificadoPrimeraCuota, p.cuotasPagadas, p.saldoTotal, estadoAdministrativoSinTalla(p)];

function aplicarFiltros(personas: PersonaTallaCuota[], filtros: Filtros) {
  const texto = filtros.buscar.trim().toLocaleLowerCase("es");
  return personas.filter((p) => {
    const coincideTexto = !texto || `${p.nombre} ${p.ci} ${p.codigoFraterno} ${p.telefono}`.toLocaleLowerCase("es").includes(texto);
    const coincideSexo = filtros.sexo === "TODOS" || p.sexo === filtros.sexo;
    const coincideTalla = filtros.talla === "TODOS" || p.estadoMedicion === filtros.talla;
    const coincidePrenda = filtros.prenda === "TODAS" || (filtros.prenda === "POLERA" ? p.tienePolera : p.tieneChamarra);
    const coincideTallaValor = filtros.tallaValor === "TODAS" || (filtros.prenda === "POLERA" ? p.tallaPolera === filtros.tallaValor : filtros.prenda === "CHAMARRA" ? p.tallaChamarra === filtros.tallaValor : p.tallaPolera === filtros.tallaValor || p.tallaChamarra === filtros.tallaValor);
    const coincidePago = filtros.pago === "TODOS" || p.estadoPagoReporte === filtros.pago || (filtros.pago === "PAGO VERIFICADO" && p.montoVerificadoTotal > 0);
    const coincideVerificacion = filtros.verificacion === "TODOS" || p.estadoVerificacionPago === filtros.verificacion || (filtros.verificacion === "PENDIENTE" && p.estadoVerificacionPago === "PENDIENTE DE VERIFICACIÓN");
    const coincideEstado = filtros.estado === "TODOS" || (p.perfilFraterno && ((filtros.estado === "SIN_TALLA" && !p.conTalla) || (filtros.estado === "SIN_PRIMERA" && p.primeraCuota === "PENDIENTE") || (filtros.estado === "AMBOS" && !p.conTalla && p.primeraCuota === "PENDIENTE")));
    const coincideRol = filtros.rol === "TODOS" || p.roles.includes(filtros.rol);
    const coincideBloque = filtros.bloque === "TODOS" || p.bloque === filtros.bloque;
    return coincideTexto && coincideSexo && coincideTalla && coincidePrenda && coincideTallaValor && coincidePago && coincideVerificacion && coincideEstado && coincideRol && coincideBloque;
  });
}

async function exportar(reporte: NonNullable<ReturnType<typeof useReporte>["data"]>, personas: PersonaTallaCuota[], completo: boolean) {
  const { default: ExcelJS } = await import("exceljs");
  const libro = new ExcelJS.Workbook(); libro.creator = "Fraternidad Tinkus Puros"; libro.created = new Date();
  const agregar = (nombre: string, datos: PersonaTallaCuota[], extraPendiente = false) => {
    const encabezados = extraPendiente ? [...columnas, "Pendiente"] : columnas;
    const hoja = libro.addWorksheet(nombre); hoja.addRow(encabezados);
    datos.forEach((p, i) => hoja.addRow(extraPendiente ? [...fila(p, i), p.pendienteTalla ?? ""] : fila(p, i)));
    hoja.views = [{ state: "frozen", ySplit: 1 }]; hoja.autoFilter = { from: "A1", to: `${columnaExcel(encabezados.length)}1` };
    const cabecera = hoja.getRow(1); cabecera.font = { bold: true, color: { argb: "FFFFFFFF" } }; cabecera.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF74122A" } };
    hoja.columns.forEach((columna, i) => { columna.width = Math.min(42, Math.max(12, encabezados[i].length + 2, ...datos.map((p, n) => String(fila(p, n)[i] ?? "").length + 2))); });
    [3, 6, 7].forEach((numero) => { hoja.getColumn(numero).numFmt = "@"; }); [20, 21, 22, 23].forEach((numero) => { hoja.getColumn(numero).numFmt = '"Bs "#,##0.00'; });
  };
  const base = completo ? reporte.personas : personas;
  const soloFraternos = base.filter((p) => p.perfilFraterno);
  const resumen = libro.addWorksheet("RESUMEN DE TALLAS");
  const hombres = base.filter((p) => p.sexo === "HOMBRE"), mujeres = base.filter((p) => p.sexo === "MUJER");
  resumen.addRows([["REPORTE GENERAL DE USUARIOS, TALLAS Y PAGOS"], [reporte.gestion.nombre], [], ["Indicador", "Total", "Hombres", "Mujeres"], ["TOTAL USUARIOS REGISTRADOS", base.length, hombres.length, mujeres.length], ["TOTAL CON PERFIL FRATERNO", soloFraternos.length], ["TOTAL SIN PERFIL FRATERNO", base.length - soloFraternos.length], ["TOTAL ADMINISTRADORES", base.filter((p) => p.roles.some((r) => r.includes("ADMINISTRADOR"))).length], ["TOTAL GUÍAS", base.filter((p) => p.roles.some((r) => r.includes("GUIA") || r.includes("GUÍA"))).length], ["TOTAL SIN BLOQUE", base.filter((p) => p.bloque === "SIN BLOQUE").length], [], ["USUARIOS CON TALLA Y SIN PAGO", base.filter((p) => p.conTalla && p.estadoPagoReporte === "SIN PAGO").length, hombres.filter((p) => p.conTalla && p.estadoPagoReporte === "SIN PAGO").length, mujeres.filter((p) => p.conTalla && p.estadoPagoReporte === "SIN PAGO").length], ["USUARIOS CON TALLA Y PAGO PENDIENTE DE VERIFICACIÓN", base.filter((p) => p.conTalla && p.estadoPagoReporte === "PENDIENTE DE VERIFICACIÓN").length, hombres.filter((p) => p.conTalla && p.estadoPagoReporte === "PENDIENTE DE VERIFICACIÓN").length, mujeres.filter((p) => p.conTalla && p.estadoPagoReporte === "PENDIENTE DE VERIFICACIÓN").length], ["USUARIOS CON TALLA Y PAGO VERIFICADO", base.filter((p) => p.conTalla && p.montoVerificadoTotal > 0).length, hombres.filter((p) => p.conTalla && p.montoVerificadoTotal > 0).length, mujeres.filter((p) => p.conTalla && p.montoVerificadoTotal > 0).length], ["USUARIOS CON TALLA Y PAGO PARCIAL", base.filter((p) => p.conTalla && p.estadoPagoReporte === "PAGO PARCIAL").length, hombres.filter((p) => p.conTalla && p.estadoPagoReporte === "PAGO PARCIAL").length, mujeres.filter((p) => p.conTalla && p.estadoPagoReporte === "PAGO PARCIAL").length], ["USUARIOS CON TALLA Y PAGO COMPLETO", base.filter((p) => p.conTalla && p.estadoPagoReporte === "PAGO COMPLETO").length, hombres.filter((p) => p.conTalla && p.estadoPagoReporte === "PAGO COMPLETO").length, mujeres.filter((p) => p.conTalla && p.estadoPagoReporte === "PAGO COMPLETO").length]]);
  resumen.getRow(1).font = { bold: true, size: 16, color: { argb: "FF74122A" } }; resumen.getRow(4).font = { bold: true }; resumen.columns = [{ width: 62 }, { width: 16 }, { width: 16 }, { width: 16 }];
  const guias = base.filter((p) => p.roles.some((r) => r.includes("GUIA") || r.includes("GUÍA"))), administradores = base.filter((p) => p.roles.some((r) => r.includes("ADMINISTRADOR"))), sinPago = base.filter((p) => p.participante && p.montoRegistradoTotal === 0), pagoPorVerificar = base.filter((p) => p.cuotasPorVerificar > 0), sinTalla = base.filter((p) => p.participante && !p.conTalla), pagaronSinTalla = base.filter((p) => p.montoVerificadoTotal > 0 && !p.conTalla), porVerificarSinTalla = base.filter((p) => p.cuotasPorVerificar > 0 && !p.conTalla), sinPagoSinTalla = base.filter((p) => p.participante && p.montoRegistradoTotal === 0 && !p.conTalla);
  agregar("Todos los usuarios", base); agregar("Pagaron sin talla", pagaronSinTalla, true); agregar("Verificar sin talla", porVerificarSinTalla, true); agregar("Sin pago y sin talla", sinPagoSinTalla, true); agregar("Sin pago", sinPago); agregar("Pendientes verificacion", pagoPorVerificar); agregar("Sin talla", sinTalla, true); agregar("Postulantes", base.filter((p) => p.roles.includes("POSTULANTE") || p.estadoInscripcion === "PENDIENTE")); agregar("Guias", guias); agregar("Administradores", administradores); agregar("Por bloque", [...base].sort((a,b) => a.bloque.localeCompare(b.bloque, "es") || a.nombre.localeCompare(b.nombre, "es")));
  const agregarTallas = (nombre: string, datos: PersonaTallaCuota[]) => { const hoja = libro.addWorksheet(nombre); hoja.addRow(columnasTallasPagos); datos.forEach((p, i) => hoja.addRow(filaTallasPagos(p, i))); hoja.views = [{ state: "frozen", ySplit: 1 }]; hoja.autoFilter = { from: "A1", to: "U1" }; hoja.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } }; hoja.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF74122A" } }; hoja.columns.forEach((columna) => { columna.width = 22; }); [3, 5, 6].forEach((n) => { hoja.getColumn(n).numFmt = "@"; }); [18, 19, 20, 21].forEach((n) => { hoja.getColumn(n).numFmt = '"Bs "#,##0.00'; }); };
  agregarTallas("POLERAS HOMBRES", base.filter((p) => p.sexo === "HOMBRE" && p.tienePolera)); agregarTallas("POLERAS MUJERES", base.filter((p) => p.sexo === "MUJER" && p.tienePolera)); agregarTallas("CHAMARRAS HOMBRES", base.filter((p) => p.sexo === "HOMBRE" && p.tieneChamarra)); agregarTallas("CHAMARRAS MUJERES", base.filter((p) => p.sexo === "MUJER" && p.tieneChamarra)); agregarTallas("TODOS CON TALLA", base.filter((p) => p.conTalla));
  agregar("Calidad de datos", base.filter((p) => p.problemasCalidad.length).map((p) => ({ ...p, estadoGeneral: p.problemasCalidad.join(" / ") })));
  agregar("Contactar", base.filter((p) => p.motivoSeguimiento).sort((a,b) => ({ALTA:0,MEDIA:1,BAJA:2}[a.prioridadSeguimiento] - {ALTA:0,MEDIA:1,BAJA:2}[b.prioridadSeguimiento])));
  const datos = await libro.xlsx.writeBuffer(); const url = URL.createObjectURL(new Blob([datos], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" })); const enlace = document.createElement("a"); enlace.href = url; enlace.download = completo ? "reporte-tallas-primera-cuota-completo.xlsx" : "reporte-tallas-primera-cuota-filtrado.xlsx"; enlace.click(); URL.revokeObjectURL(url);
}

async function exportarListado(nombre: string, personas: PersonaTallaCuota[], tipo: "CUOTA" | "MEDICION" | "POSTULANTE") {
  const { default: ExcelJS } = await import("exceljs");
  const libro = new ExcelJS.Workbook();
  const hoja = libro.addWorksheet(nombre);
  const encabezados = tipo === "CUOTA" ? ["Nombre completo", "CI", "Sexo", "Teléfono", "WhatsApp", "Correo", "Roles", "Asignación", "Bloque", "Monto primera cuota", "Monto registrado", "Monto verificado", "Saldo", "Estado", "Verificación"] : ["Nombre completo", "CI", "Sexo", "Teléfono", "WhatsApp", "Correo", "Roles", "Asignación", "Bloque", "Primera cuota", "Estado pago", "Verificación", "Talla polera", "Talla chamarra", "Estado medición"];
  hoja.addRow(encabezados);
  personas.forEach((p) => hoja.addRow(tipo === "CUOTA" ? [p.nombre, p.ci, p.sexo, p.telefono, p.whatsapp ?? "", p.correo, p.roles.join(" / "), p.asignacion, p.bloque, p.montoPrimeraCuota, p.montoRegistradoPrimeraCuota, p.montoVerificadoPrimeraCuota, p.saldoPrimeraCuota, p.estadoPago, p.verificacionPrimeraCuota] : [p.nombre, p.ci, p.sexo, p.telefono, p.whatsapp ?? "", p.correo, p.roles.join(" / "), p.asignacion, p.bloque, p.primeraCuota, p.estadoPago, p.verificacionPrimeraCuota, p.tallaPolera ?? "SIN REGISTRAR", p.tallaChamarra ?? "SIN REGISTRAR", p.pendienteTalla === "AMBAS" ? "SIN MEDICIÓN" : p.pendienteTalla ? "MEDICIÓN INCOMPLETA" : "COMPLETA"]));
  hoja.views = [{ state: "frozen", ySplit: 1 }]; hoja.autoFilter = { from: "A1", to: `${columnaExcel(encabezados.length)}1` };
  hoja.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } }; hoja.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF74122A" } };
  hoja.columns.forEach((columna) => { columna.width = 22; }); [2, 4, 5].forEach((numero) => { hoja.getColumn(numero).numFmt = "@"; });
  const datos = await libro.xlsx.writeBuffer(); const url = URL.createObjectURL(new Blob([datos], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" })); const enlace = document.createElement("a"); enlace.href = url; enlace.download = `${nombre.toLocaleLowerCase("es").replace(/\s+/g, "-")}.xlsx`; enlace.click(); URL.revokeObjectURL(url);
}

async function exportarPagosYTallasPendientes(personas: PersonaTallaCuota[]) {
  const { default: ExcelJS } = await import("exceljs");
  const libro = new ExcelJS.Workbook(); libro.creator = "Fraternidad Tinkus Puros"; libro.created = new Date();
  const sinCuotas = personas.filter((p) => p.participante && p.cuotasPagadas === 0 && p.cuotasPorVerificar === 0);
  const pagoSinTalla = personas.filter((p) => p.participante && !p.conTalla && (p.cuotasPagadas > 0 || p.cuotasPorVerificar > 0));
  const pagoVerificadoSinTalla = pagoSinTalla.filter((p) => p.cuotasPagadas > 0), pagoPendienteSinTalla = pagoSinTalla.filter((p) => p.cuotasPorVerificar > 0);
  const resumen = libro.addWorksheet("RESUMEN");
  const porSexo = (lista: PersonaTallaCuota[], sexo: string) => lista.filter((p) => p.sexo === sexo).length;
  resumen.addRows([["REPORTE DE PAGOS Y TALLAS PENDIENTES"], [], ["Indicador", "Total"], ["TOTAL USUARIOS SIN CUOTAS PAGADAS", sinCuotas.length], ["HOMBRES SIN CUOTAS PAGADAS", porSexo(sinCuotas, "HOMBRE")], ["MUJERES SIN CUOTAS PAGADAS", porSexo(sinCuotas, "MUJER")], ["TOTAL USUARIOS CON PAGO VERIFICADO PERO SIN TALLA", pagoVerificadoSinTalla.length], ["HOMBRES CON PAGO VERIFICADO PERO SIN TALLA", porSexo(pagoVerificadoSinTalla, "HOMBRE")], ["MUJERES CON PAGO VERIFICADO PERO SIN TALLA", porSexo(pagoVerificadoSinTalla, "MUJER")], ["TOTAL PAGO PENDIENTE DE REVISIÓN PERO SIN TALLA", pagoPendienteSinTalla.length], ["HOMBRES CON PAGO PENDIENTE PERO SIN TALLA", porSexo(pagoPendienteSinTalla, "HOMBRE")], ["MUJERES CON PAGO PENDIENTE PERO SIN TALLA", porSexo(pagoPendienteSinTalla, "MUJER")], ["TOTAL SIN PAGO Y SIN TALLA", sinCuotas.filter((p) => !p.conTalla).length]]);
  resumen.getRow(1).font = { bold: true, size: 16, color: { argb: "FF74122A" } }; resumen.getRow(3).font = { bold: true }; resumen.columns = [{ width: 58 }, { width: 16 }];
  const encabezados = ["N.º", "Nombre completo", "CI", "Sexo", "Teléfono", "WhatsApp", "Correo", "Roles", "Bloque", "Asignación", "Estado pago", "Verificación", "Monto registrado", "Monto verificado", "Saldo", "Talla polera", "Talla chamarra", "Estado talla", "Estado general"];
  const agregar = (nombre: string, lista: PersonaTallaCuota[], sinPago: boolean) => {
    const hoja = libro.addWorksheet(nombre); hoja.addRow(encabezados);
    lista.forEach((p, i) => hoja.addRow([i + 1, p.nombre, p.ci, p.sexo, p.telefono, p.whatsapp ?? "", p.correo, p.roles.join(" / "), p.bloque, p.asignacion, p.cuotasPorVerificar > 0 ? "PENDIENTE DE REVISIÓN" : p.cuotasPagadas > 0 ? "PAGO VERIFICADO" : "SIN PAGO", p.verificacionPrimeraCuota, p.montoRegistradoTotal, p.montoVerificadoTotal, p.saldoTotal, p.tallaPolera ?? "SIN REGISTRAR", p.tallaChamarra ?? "SIN REGISTRAR", p.estadoMedicion, sinPago && !p.conTalla ? "SIN PAGO + SIN TALLA" : sinPago ? "SIN PAGO" : p.estadoMedicion]));
    hoja.views = [{ state: "frozen", ySplit: 1 }]; hoja.autoFilter = { from: "A1", to: `${columnaExcel(encabezados.length)}1` }; hoja.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } }; hoja.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF74122A" } };
    hoja.columns.forEach((columna, i) => { columna.width = Math.min(42, Math.max(14, encabezados[i].length + 2)); }); [3, 5, 6].forEach((n) => { hoja.getColumn(n).numFmt = "@"; }); [13, 14, 15].forEach((n) => { hoja.getColumn(n).numFmt = '"Bs "#,##0.00'; });
  };
  agregar("SIN CUOTAS PAGADAS", sinCuotas, true); agregar("PAGO SIN TALLA", pagoSinTalla, false);
  const datos = await libro.xlsx.writeBuffer(); const url = URL.createObjectURL(new Blob([datos], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" })); const enlace = document.createElement("a"); enlace.href = url; enlace.download = "reporte-pagos-y-tallas-pendientes.xlsx"; enlace.click(); URL.revokeObjectURL(url);
}

async function exportarReporteGeneralTallas(reporte: NonNullable<ReturnType<typeof useReporte>["data"]>, personas: PersonaTallaCuota[]) {
  const { default: ExcelJS } = await import("exceljs");
  const libro = new ExcelJS.Workbook(); libro.creator = "Fraternidad Tinkus Puros"; libro.created = new Date();
  const encabezados = ["N.º", "Nombre completo", "CI", "Sexo", "Teléfono", "WhatsApp", "Correo", "Roles", "Bloque", "Asignación", "Talla polera", "Talla chamarra", "Estado talla", "Estado pago", "Verificación", "Cuotas pagadas", "Monto registrado", "Monto verificado", "Saldo pendiente"];
  const datosFila = (p: PersonaTallaCuota, i: number) => [i + 1, p.nombre, p.ci, p.sexo, p.telefono, p.whatsapp ?? "", p.correo, p.roles.join(" / ") || "SIN ROL", p.bloque, p.asignacion, p.tallaPolera ?? "SIN REGISTRAR", p.tallaChamarra ?? "SIN REGISTRAR", p.estadoTalla, p.estadoPagoReporte, p.estadoVerificacionPago, p.cuotasPagadas, p.montoRegistradoTotal, p.montoVerificadoTotal, p.saldoTotal];
  const estilizar = (hoja: Worksheet, cantidadColumnas: number) => { hoja.views = [{ state: "frozen", ySplit: 1 }]; hoja.autoFilter = { from: "A1", to: `${columnaExcel(cantidadColumnas)}1` }; hoja.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } }; hoja.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF74122A" } }; hoja.columns.forEach((columna) => { columna.width = 22; }); };
  const listado = (nombre: string, datos: PersonaTallaCuota[]) => { const hoja = libro.addWorksheet(nombre); hoja.addRow(encabezados); datos.forEach((p, i) => hoja.addRow(datosFila(p, i))); estilizar(hoja, encabezados.length); [3, 5, 6].forEach((n) => { hoja.getColumn(n).numFmt = "@"; }); [17, 18, 19].forEach((n) => { hoja.getColumn(n).numFmt = '"Bs "#,##0.00'; }); };
  const resumen = libro.addWorksheet("RESUMEN GENERAL"); const r = reporte.resumenGeneralTallas;
  const incompletos = personas.filter((p) => !p.conTalla), hombresSinTalla = incompletos.filter((p) => p.sexo === "HOMBRE"), mujeresSinTalla = incompletos.filter((p) => p.sexo === "MUJER");
  const resumenFaltante = (titulo: string, criterio: (p: PersonaTallaCuota) => boolean) => [titulo, incompletos.filter(criterio).length, hombresSinTalla.filter(criterio).length, mujeresSinTalla.filter(criterio).length];
  resumen.addRows([["REPORTE GENERAL DE TALLAS"], [reporte.gestion.nombre], [], ["Indicador", "Total", "Hombres", "Mujeres"], ["TOTAL USUARIOS", r.totalUsuarios, r.totalHombres, r.totalMujeres], ["TALLAS COMPLETAS", r.tallasCompletas], ["USUARIOS CON MEDICIÓN INCOMPLETA", incompletos.length, hombresSinTalla.length, mujeresSinTalla.length], resumenFaltante("USUARIOS SIN NINGUNA TALLA", (p) => p.pendienteTalla === "AMBAS"), resumenFaltante("SIN TALLA DE POLERA", (p) => !p.tienePolera), resumenFaltante("SIN TALLA DE CHAMARRA", (p) => !p.tieneChamarra), resumenFaltante("SIN TALLA + SIN PRIMERA CUOTA", (p) => p.estadoPagoReporte === "SIN PAGO"), resumenFaltante("PRIMERA CUOTA PENDIENTE + SIN TALLA", (p) => p.estadoPagoReporte === "PENDIENTE DE VERIFICACIÓN"), resumenFaltante("PRIMERA CUOTA VERIFICADA + SIN TALLA", (p) => p.verificacionPrimeraCuota === "VERIFICADO"), [], ["PAGO", "TOTAL"], ...["SIN PAGO", "PENDIENTE DE VERIFICACIÓN", "PAGO REGISTRADO", "PAGO PARCIAL", "PAGO COMPLETO"].map((estado) => [estado, personas.filter((p) => p.estadoPagoReporte === estado).length]), [], ["TALLA", "POLERA H", "POLERA M", "CHAMARRA H", "CHAMARRA M", "TOTAL"], ...reporte.distribucionTallas.map((d) => [d.talla, d.poleraHombres, d.poleraMujeres, d.chamarraHombres, d.chamarraMujeres, d.poleraHombres + d.poleraMujeres + d.chamarraHombres + d.chamarraMujeres])]); resumen.columns = [{ width: 58 }, { width: 18 }, { width: 18 }, { width: 18 }, { width: 18 }, { width: 18 }]; resumen.getRow(1).font = { bold: true, size: 16, color: { argb: "FF74122A" } };
  listado("TODOS LOS USUARIOS", personas); listado("USUARIOS CON TALLA", personas.filter((p) => p.tienePolera || p.tieneChamarra)); listado("USUARIOS SIN TALLA", personas.filter((p) => !p.tienePolera && !p.tieneChamarra)); listado("POLERAS HOMBRES", personas.filter((p) => p.sexo === "HOMBRE" && p.tienePolera)); listado("POLERAS MUJERES", personas.filter((p) => p.sexo === "MUJER" && p.tienePolera)); listado("CHAMARRAS HOMBRES", personas.filter((p) => p.sexo === "HOMBRE" && p.tieneChamarra)); listado("CHAMARRAS MUJERES", personas.filter((p) => p.sexo === "MUJER" && p.tieneChamarra));
  const listadoSinTalla = (nombre: string, datos: PersonaTallaCuota[]) => { const hoja = libro.addWorksheet(nombre); hoja.addRow(columnasSinTalla); datos.forEach((p, i) => hoja.addRow(filaSinTalla(p, i))); estilizar(hoja, columnasSinTalla.length); [3, 5, 6].forEach((n) => { hoja.getColumn(n).numFmt = "@"; }); [17, 18, 19, 21].forEach((n) => { hoja.getColumn(n).numFmt = '"Bs "#,##0.00'; }); };
  listadoSinTalla("SIN TALLA - DETALLE", incompletos); listadoSinTalla("SIN TALLA - SIN PAGO", incompletos.filter((p) => p.estadoPagoReporte === "SIN PAGO")); listadoSinTalla("SIN TALLA - PAGO PENDIENTE", incompletos.filter((p) => p.estadoPagoReporte === "PENDIENTE DE VERIFICACIÓN")); listadoSinTalla("PAGARON Y NO TIENEN TALLA", incompletos.filter((p) => p.verificacionPrimeraCuota === "VERIFICADO")); listadoSinTalla("ADMINISTRADORES SIN TALLA", incompletos.filter((p) => p.roles.some((rol) => rol.includes("ADMINISTRADOR")))); listadoSinTalla("CONTACTAR POR TALLAS", incompletos);
  const valoresNoReconocidos = libro.addWorksheet("VALORES SIN DEFINIR"); valoresNoReconocidos.addRow(["Nombre", "CI", "Sexo", "Roles", "Bloque", "Valor real polera", "Clasificación polera", "Valor real chamarra", "Clasificación chamarra"]); reporte.personasSinDefinir.forEach((p) => valoresNoReconocidos.addRow([p.nombre, p.ci, p.sexo, p.roles.join(" / "), p.bloque, p.tallaPolera ?? "<null>", p.estadoCampoPolera, p.tallaChamarra ?? "<null>", p.estadoCampoChamarra])); estilizar(valoresNoReconocidos, 9);
  const rolesSinTalla = [...new Set(incompletos.flatMap((persona) => persona.roles))].sort(); const resumenRoles = libro.addWorksheet("RESUMEN SIN TALLA POR ROL"); resumenRoles.addRow(["Rol", "Hombres sin talla", "Mujeres sin talla", "Sin pago", "Pendiente verificación", "Primera cuota verificada"]); rolesSinTalla.forEach((rol) => { const lista = incompletos.filter((persona) => persona.roles.includes(rol)); resumenRoles.addRow([rol, lista.filter((p) => p.sexo === "HOMBRE").length, lista.filter((p) => p.sexo === "MUJER").length, lista.filter((p) => p.estadoPagoReporte === "SIN PAGO").length, lista.filter((p) => p.estadoPagoReporte === "PENDIENTE DE VERIFICACIÓN").length, lista.filter((p) => p.verificacionPrimeraCuota === "VERIFICADO").length]); }); estilizar(resumenRoles, 6);
  const tallas = libro.addWorksheet("RESUMEN POR TALLA"); tallas.addRow(["Talla", "Polera hombres", "Polera mujeres", "Chamarra hombres", "Chamarra mujeres", "Total"]); reporte.distribucionTallas.forEach((d) => tallas.addRow([d.talla, d.poleraHombres, d.poleraMujeres, d.chamarraHombres, d.chamarraMujeres, d.poleraHombres + d.poleraMujeres + d.chamarraHombres + d.chamarraMujeres])); estilizar(tallas, 6);
  const buffer = await libro.xlsx.writeBuffer(); const url = URL.createObjectURL(new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" })); const enlace = document.createElement("a"); enlace.href = url; enlace.download = "reporte-general-completo-de-tallas.xlsx"; enlace.click(); URL.revokeObjectURL(url);
}

function useReporte(abierto: boolean) { return useQuery({ queryKey: ["reporte-tallas-primera-cuota"], queryFn: obtenerReporteTallasPrimeraCuota, enabled: abierto }); }

export default function ReporteTallasPrimeraCuota() {
  const [abierto, setAbierto] = useState(false), [sinTallaAbierto, setSinTallaAbierto] = useState(false), [sinDefinirAbierto, setSinDefinirAbierto] = useState(false), [cuotaAbierta, setCuotaAbierta] = useState(false), [medicionAbierta, setMedicionAbierta] = useState(false), [postulantesAbierto, setPostulantesAbierto] = useState(false), [filtros, setFiltros] = useState(inicial);
  const consulta = useReporte(true); const personas = useMemo(() => aplicarFiltros(consulta.data?.personas ?? [], filtros), [consulta.data, filtros]);
  const sinPrimeraCuota = (consulta.data?.personas ?? []).filter((p) => p.participante && p.primeraCuota === "PENDIENTE");
  const pagaronSinMedicion = (consulta.data?.personas ?? []).filter((p) => p.participante && p.primeraCuota === "PAGADA" && !p.conTalla);
  const postulantes = (consulta.data?.personas ?? []).filter((p) => p.roles.includes("POSTULANTE") || p.estadoInscripcion === "PENDIENTE");
  const rolesDisponibles = [...new Set((consulta.data?.personas ?? []).flatMap((p) => p.roles))].sort();
  const cambiar = (campo: keyof Filtros, valor: string) => setFiltros((actual) => ({ ...actual, [campo]: valor }));
  return <div className="space-y-4 print:hidden"><section className="rounded-2xl border-2 border-[#74122A]/30 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-xs font-black uppercase tracking-widest text-[#9b5d20]">Todos los usuarios del sistema</p><h2 className="text-2xl font-black text-[#74122A]">REPORTE GENERAL DE TALLAS</h2><p className="text-sm text-slate-600">Incluye usuarios con talla completa, parcial o sin talla, sus roles, bloques y estado real de pagos.</p></div><button disabled={consulta.isLoading || !consulta.data} onClick={() => consulta.data && void exportarReporteGeneralTallas(consulta.data, consulta.data.personas)} className="rounded-xl bg-emerald-700 px-5 py-3 font-black text-white disabled:opacity-50">EXPORTAR EXCEL</button></div>{consulta.data ? <><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-7"><Metrica titulo="Total usuarios" valor={consulta.data.resumenGeneralTallas.totalUsuarios}/><Metrica titulo="Hombres" valor={consulta.data.resumenGeneralTallas.totalHombres}/><Metrica titulo="Mujeres" valor={consulta.data.resumenGeneralTallas.totalMujeres}/><Metrica titulo="Tallas completas" valor={consulta.data.resumenGeneralTallas.tallasCompletas}/><Metrica titulo="Solo polera" valor={consulta.data.resumenGeneralTallas.soloPolera}/><Metrica titulo="Solo chamarra" valor={consulta.data.resumenGeneralTallas.soloChamarra}/><Metrica titulo="Sin talla" valor={consulta.data.resumenGeneralTallas.sinTalla}/></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr>{["Talla","Polera H","Polera M","Chamarra H","Chamarra M","Total"].map((c)=><th key={c} className="border bg-slate-100 p-2 text-left">{c}</th>)}</tr></thead><tbody>{consulta.data.distribucionTallas.map((d)=><tr key={d.talla} className={d.talla === "SIN TALLA" ? "bg-amber-50" : ""}><td className="border p-2 font-bold">{d.talla}{d.talla === "SIN TALLA" && <button type="button" onClick={() => setSinTallaAbierto((valor) => !valor)} className="ml-3 rounded-lg bg-[#74122A] px-3 py-1 text-xs text-white">{sinTallaAbierto ? "OCULTAR DETALLE" : "VER DETALLE"}</button>}</td><td className="border p-2">{d.poleraHombres}</td><td className="border p-2">{d.poleraMujeres}</td><td className="border p-2">{d.chamarraHombres}</td><td className="border p-2">{d.chamarraMujeres}</td><td className="border p-2 font-bold">{d.poleraHombres+d.poleraMujeres+d.chamarraHombres+d.chamarraMujeres}</td></tr>)}</tbody></table></div>{sinTallaAbierto && <DetalleSinTalla personas={consulta.data.personas.filter((persona) => !persona.conTalla)} bloques={consulta.data.bloques}/>}</> : null}</section><section className="rounded-2xl border border-[#74122A]/20 bg-white p-5 shadow-sm">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h2 className="text-xl font-black text-[#74122A]">Reporte general de usuarios, tallas y primera cuota</h2><p className="text-sm text-slate-600">Incluye todas las cuentas y separa claramente los indicadores que solo aplican a fraternos.</p></div><button onClick={() => setAbierto((v) => !v)} className="rounded-xl bg-[#74122A] px-5 py-3 font-black text-white">{abierto ? "OCULTAR REPORTE" : "VER REPORTE"}</button></div>
    {consulta.data && consulta.data.resumenSinDefinir.camposPrenda > 0 && <div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-red-950"><b>SIN DEFINIR:</b> {consulta.data.resumenSinDefinir.personasUnicas} persona(s) única(s), {consulta.data.resumenSinDefinir.camposPrenda} campo(s) de prenda afectados. No cuentan como tallas válidas de producción.</p><button type="button" onClick={() => setSinDefinirAbierto((valor) => !valor)} className="rounded-lg bg-red-700 px-4 py-2 text-xs font-black text-white">{sinDefinirAbierto ? "OCULTAR DETALLE" : "VER DETALLE"}</button></div>{sinDefinirAbierto && <DetalleSinDefinir personas={consulta.data.personasSinDefinir} resumen={consulta.data.resumenSinDefinir}/>}</div>}
    {abierto && <div className="mt-5 space-y-5">{consulta.isLoading ? <p>Cargando reporte…</p> : consulta.error ? <p className="text-red-700">{consulta.error.message}</p> : consulta.data && <>
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Metrica titulo="Usuarios registrados" valor={consulta.data.resumen.totalUsuarios}/><Metrica titulo="Con perfil fraterno" valor={consulta.data.resumen.conPerfilFraterno}/><Metrica titulo="Sin perfil fraterno" valor={consulta.data.resumen.sinPerfilFraterno}/><Metrica titulo="Administradores" valor={consulta.data.resumen.administradores}/><Metrica titulo="Guías" valor={consulta.data.resumen.guias}/><Metrica titulo="Hombres (usuarios)" valor={consulta.data.resumen.totalHombres}/><Metrica titulo="Mujeres (usuarios)" valor={consulta.data.resumen.totalMujeres}/><Metrica titulo="Sin bloque" valor={consulta.data.resumen.sinBloque}/><Metrica titulo="Fraternos con talla" valor={consulta.data.resumen.conTalla}/><Metrica titulo="Fraternos sin talla" valor={consulta.data.resumen.sinTalla}/><Metrica titulo="Primera cuota pagada" valor={consulta.data.resumen.primeraCuotaPagada}/><Metrica titulo="Primera cuota pendiente" valor={consulta.data.resumen.primeraCuotaPendiente}/><Metrica titulo="Sin talla y cuota" valor={consulta.data.resumen.sinTallaYSinPrimeraCuota}/></div>
      <div className="grid gap-3 md:grid-cols-2"><ResumenGenero titulo="Hombres fraternos" resumen={consulta.data.resumen.hombres}/><ResumenGenero titulo="Mujeres fraternas" resumen={consulta.data.resumen.mujeres}/></div>
      <div className="grid gap-2 md:grid-cols-3 xl:grid-cols-6"><input value={filtros.buscar} onChange={(e) => cambiar("buscar", e.target.value)} placeholder="Nombre, CI, código o teléfono" className="rounded-xl border p-3 md:col-span-3 xl:col-span-2"/><Select valor={filtros.sexo} cambiar={(v) => cambiar("sexo", v)} opciones={[["TODOS","Sexo: todos"],["HOMBRE","Hombres"],["MUJER","Mujeres"]]}/><Select valor={filtros.talla} cambiar={(v) => cambiar("talla", v)} opciones={[["TODOS","Estado talla: todos"],["TALLAS COMPLETAS","Tallas completas"],["SOLO POLERA","Solo polera"],["SOLO CHAMARRA","Solo chamarra"],["SIN TALLA","Sin talla"]]}/><Select valor={filtros.prenda} cambiar={(v) => cambiar("prenda", v)} opciones={[["TODAS","Prenda: todas"],["POLERA","Polera"],["CHAMARRA","Chamarra"]]}/><Select valor={filtros.tallaValor} cambiar={(v) => cambiar("tallaValor", v)} opciones={[["TODAS","Tamaño: todos"],...consulta.data.tallasDisponibles.map((t) => [t,t])]}/><Select valor={filtros.pago} cambiar={(v) => cambiar("pago", v)} opciones={[["TODOS","Pago: todos"],["SIN PAGO","Sin pago"],["PENDIENTE DE VERIFICACIÓN","Pendiente de verificación"],["PAGO REGISTRADO","Pago registrado"],["PAGO VERIFICADO","Pago verificado"],["PAGO PARCIAL","Pago parcial"],["PAGO COMPLETO","Pago completo"]]}/><Select valor={filtros.verificacion} cambiar={(v) => cambiar("verificacion", v)} opciones={[["TODOS","Verificación: todas"],["SIN REGISTRO","Sin registro"],["PENDIENTE","Pendiente"],["VERIFICADO","Verificado"],["OBSERVADO","Observado"],["RECHAZADO","Rechazado"]]}/><Select valor={filtros.rol} cambiar={(v) => cambiar("rol", v)} opciones={[["TODOS","Rol: todos"],...rolesDisponibles.map((r) => [r,r])]}/><Select valor={filtros.bloque} cambiar={(v) => cambiar("bloque", v)} opciones={[["TODOS","Bloque: todos"],...consulta.data.bloques.map((b) => [b,b])]}/></div>
      <div className="flex flex-wrap gap-3"><button onClick={() => void exportar(consulta.data!, personas, false)} className="rounded-xl bg-blue-700 px-4 py-2 font-bold text-white">Exportar filtrados</button><button onClick={() => void exportar(consulta.data!, consulta.data!.personas, true)} className="rounded-xl bg-emerald-700 px-4 py-2 font-bold text-white">Exportar reporte maestro</button><span className="self-center text-sm font-bold text-slate-600">{personas.length} resultado(s)</span></div>
      <div className="overflow-x-auto"><table className="min-w-[1900px] w-full text-xs"><thead><tr>{columnas.map((c) => <th key={c} className="border bg-slate-100 p-2 text-left">{c}</th>)}</tr></thead><tbody>{personas.map((p, i) => <tr key={p.usuarioId}>{fila(p,i).map((v,j) => <td key={columnas[j]} className="border p-2">{j === 6 && p.whatsapp ? <a className="text-emerald-700 underline" href={`https://wa.me/${p.whatsapp.replace("+","")}`} target="_blank" rel="noreferrer">{v}</a> : String(v)}</td>)}</tr>)}</tbody></table></div>
      <TablaTallasPagos titulo="Hombres con talla" personas={personas.filter((p) => p.sexo === "HOMBRE" && p.conTalla)}/><TablaTallasPagos titulo="Mujeres con talla" personas={personas.filter((p) => p.sexo === "MUJER" && p.conTalla)}/>
    </>}</div>}
  </section><section className="rounded-2xl border border-[#74122A]/20 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h2 className="text-xl font-black text-[#74122A]">Reporte de pagos y tallas pendientes</h2><p className="text-sm text-slate-600">Un Excel con resumen, usuarios sin cuotas pagadas y pagos registrados o verificados sin tallas completas.</p></div><button disabled={consulta.isLoading} onClick={() => consulta.data && void exportarPagosYTallasPendientes(consulta.data.personas)} className="rounded-xl bg-emerald-700 px-5 py-3 font-black text-white disabled:opacity-50">EXPORTAR EXCEL</button></div></section><TarjetaListado titulo="Sin primera cuota pagada" descripcion="Participantes y postulantes sin una primera cuota verificada." abierto={cuotaAbierta} alternar={() => setCuotaAbierta((v) => !v)} cargando={consulta.isLoading} error={consulta.error?.message} personas={sinPrimeraCuota} tipo="CUOTA"/><TarjetaListado titulo="Pagaron pero no tienen talla" descripcion="Participantes con primera cuota verificada que no tienen medición o tienen una medición incompleta." abierto={medicionAbierta} alternar={() => setMedicionAbierta((v) => !v)} cargando={consulta.isLoading} error={consulta.error?.message} personas={pagaronSinMedicion} tipo="MEDICION"/><TarjetaListado titulo="Postulantes" descripcion="Todos los usuarios con rol o estado de postulante, incluso sin pago, talla o bloque." abierto={postulantesAbierto} alternar={() => setPostulantesAbierto((v) => !v)} cargando={consulta.isLoading} error={consulta.error?.message} personas={postulantes} tipo="POSTULANTE"/></div>;
}

function Metrica({titulo,valor}:{titulo:string;valor:number}) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{titulo}</p><b className="text-2xl text-[#74122A]">{valor}</b></div>; }
function ResumenGenero({titulo,resumen}:{titulo:string;resumen:ResumenTallaCuota}) { return <div className="rounded-xl border p-4"><h3 className="font-black text-[#74122A]">{titulo}</h3><div className="mt-2 grid grid-cols-2 gap-2 text-sm"><span>Total: <b>{resumen.total}</b></span><span>Con talla: <b>{resumen.conTalla}</b></span><span>Sin talla: <b>{resumen.sinTalla}</b></span><span>Con talla sin pago: <b>{resumen.conTallaSinPago}</b></span><span>Pago por verificar: <b>{resumen.conTallaPagoPendiente}</b></span><span>Pago verificado: <b>{resumen.conTallaPagoVerificado}</b></span><span>Pago parcial: <b>{resumen.conTallaPagoParcial}</b></span><span>Pago completo: <b>{resumen.conTallaPagoCompleto}</b></span></div></div>; }
function TablaTallasPagos({ titulo, personas }: { titulo: string; personas: PersonaTallaCuota[] }) { return <section className="rounded-2xl border p-4"><h3 className="mb-3 text-lg font-black uppercase text-[#74122A]">{titulo} ({personas.length})</h3><div className="max-h-96 overflow-auto"><table className="min-w-[1800px] w-full text-xs"><thead className="sticky top-0"><tr>{columnasTallasPagos.map((columna) => <th key={columna} className="border bg-slate-100 p-2 text-left">{columna}</th>)}</tr></thead><tbody>{personas.map((persona, indice) => <tr key={persona.usuarioId}>{filaTallasPagos(persona, indice).map((valor, posicion) => <td key={columnasTallasPagos[posicion]} className="border p-2">{String(valor)}</td>)}</tr>)}</tbody></table></div></section>; }
function Select({valor,cambiar,opciones}:{valor:string;cambiar:(v:string)=>void;opciones:string[][]}) { return <select value={valor} onChange={(e) => cambiar(e.target.value)} className="rounded-xl border p-3">{opciones.map(([v,t]) => <option key={v} value={v}>{t}</option>)}</select>; }
function DetalleSinDefinir({ personas, resumen }: { personas: PersonaTallaCuota[]; resumen: { personasUnicas: number; camposPrenda: number } }) {
  return <section className="mt-4 space-y-3"><p className="text-sm text-slate-700">Se conserva y muestra el valor real almacenado. No se corrige automáticamente.</p><div className="grid grid-cols-2 gap-3"><Metrica titulo="Personas únicas" valor={resumen.personasUnicas}/><Metrica titulo="Campos afectados" valor={resumen.camposPrenda}/></div><div className="max-h-80 overflow-auto"><table className="w-full min-w-[1100px] text-xs"><thead className="sticky top-0"><tr>{["Nombre", "CI", "Sexo", "Rol", "Bloque", "Valor real tallaPolera", "Estado polera", "Valor real tallaChamarra", "Estado chamarra"].map((titulo) => <th key={titulo} className="border bg-red-800 p-2 text-left text-white">{titulo}</th>)}</tr></thead><tbody>{personas.map((persona) => <tr key={persona.usuarioId}><td className="border p-2 font-bold">{persona.nombre}</td><td className="border p-2">{persona.ci}</td><td className="border p-2">{persona.sexo}</td><td className="border p-2">{persona.roles.join(" / ") || "SIN ROL"}</td><td className="border p-2">{persona.bloque}</td><td className="border p-2 font-mono">{persona.tallaPolera === null ? "<null>" : JSON.stringify(persona.tallaPolera)}</td><td className="border p-2">{persona.estadoCampoPolera}</td><td className="border p-2 font-mono">{persona.tallaChamarra === null ? "<null>" : JSON.stringify(persona.tallaChamarra)}</td><td className="border p-2">{persona.estadoCampoChamarra}</td></tr>)}</tbody></table></div></section>;
}
function DetalleSinTalla({ personas, bloques }: { personas: PersonaTallaCuota[]; bloques: string[] }) {
  personas = personas.filter((persona) => persona.estadoCampoPolera !== "SIN DEFINIR" && persona.estadoCampoChamarra !== "SIN DEFINIR");
  const [sexo, setSexo] = useState("TODOS"), [rol, setRol] = useState("TODOS"), [pago, setPago] = useState("TODOS"), [faltante, setFaltante] = useState("TODOS"), [bloque, setBloque] = useState("TODOS");
  const roles = [...new Set(personas.flatMap((persona) => persona.roles))].sort();
  const filtradas = personas.filter((persona) => (sexo === "TODOS" || persona.sexo === sexo) && (rol === "TODOS" || persona.roles.includes(rol)) && (bloque === "TODOS" || persona.bloque === bloque) && (faltante === "TODOS" || persona.pendienteTalla === faltante) && (pago === "TODOS" || persona.estadoPagoReporte === pago || (pago === "PRIMERA CUOTA VERIFICADA" && persona.verificacionPrimeraCuota === "VERIFICADO") || (pago === "RECHAZADO" && persona.estadoVerificacionPago === "RECHAZADO")));
  const hombres = personas.filter((persona) => persona.sexo === "HOMBRE"), mujeres = personas.filter((persona) => persona.sexo === "MUJER");
  const conteo = (lista: PersonaTallaCuota[], criterio: (persona: PersonaTallaCuota) => boolean) => lista.filter(criterio).length;
  const porRoles = roles.map((nombre) => { const lista = personas.filter((persona) => persona.roles.includes(nombre)); return { nombre, hombres: conteo(lista, (p) => p.sexo === "HOMBRE"), mujeres: conteo(lista, (p) => p.sexo === "MUJER"), sinPago: conteo(lista, (p) => p.estadoPagoReporte === "SIN PAGO"), pendiente: conteo(lista, (p) => p.estadoPagoReporte === "PENDIENTE DE VERIFICACIÓN"), verificada: conteo(lista, (p) => p.verificacionPrimeraCuota === "VERIFICADO") }; });
  return <section className="mt-6 space-y-5 rounded-2xl border-2 border-amber-300 bg-amber-50/40 p-4">
    <div><h3 className="text-xl font-black text-[#74122A]">USUARIOS SIN TALLA O CON MEDICIÓN INCOMPLETA</h3><p className="text-sm text-slate-600">Cada persona aparece una sola vez. Los totales por prenda pueden coincidir cuando faltan ambas tallas.</p></div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metrica titulo="Total incompletos" valor={personas.length}/><Metrica titulo="Sin ninguna talla" valor={conteo(personas, (p) => p.pendienteTalla === "AMBAS")}/><Metrica titulo="Solo falta polera" valor={conteo(personas, (p) => p.pendienteTalla === "POLERA")}/><Metrica titulo="Solo falta chamarra" valor={conteo(personas, (p) => p.pendienteTalla === "CHAMARRA")}/><Metrica titulo="Sin primera cuota" valor={conteo(personas, (p) => p.estadoPagoReporte === "SIN PAGO")}/><Metrica titulo="Pago pendiente" valor={conteo(personas, (p) => p.estadoPagoReporte === "PENDIENTE DE VERIFICACIÓN")}/><Metrica titulo="Primera cuota verificada" valor={conteo(personas, (p) => p.verificacionPrimeraCuota === "VERIFICADO")}/><Metrica titulo="Pago parcial" valor={conteo(personas, (p) => p.estadoPagoReporte === "PAGO PARCIAL")}/></div>
    <div className="grid gap-3 md:grid-cols-2"><ResumenFaltantes titulo="Hombres" personas={hombres}/><ResumenFaltantes titulo="Mujeres" personas={mujeres}/></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-xs"><thead><tr>{["Rol", "Hombres", "Mujeres", "Sin pago", "Pendiente verificación", "Primera cuota verificada"].map((titulo) => <th key={titulo} className="border bg-[#74122A] p-2 text-left text-white">{titulo}</th>)}</tr></thead><tbody>{porRoles.map((fila) => <tr key={fila.nombre}><td className="border p-2 font-bold">{fila.nombre}</td><td className="border p-2">{fila.hombres}</td><td className="border p-2">{fila.mujeres}</td><td className="border p-2">{fila.sinPago}</td><td className="border p-2">{fila.pendiente}</td><td className="border p-2">{fila.verificada}</td></tr>)}</tbody></table></div>
    <div className="grid gap-2 md:grid-cols-3 xl:grid-cols-5"><Select valor={sexo} cambiar={setSexo} opciones={[["TODOS", "Sexo: todos"], ["HOMBRE", "Hombres"], ["MUJER", "Mujeres"]]}/><Select valor={rol} cambiar={setRol} opciones={[["TODOS", "Rol: todos"], ...roles.map((valor) => [valor, valor])]}/><Select valor={pago} cambiar={setPago} opciones={[["TODOS", "Pago: todos"], ["SIN PAGO", "Sin pago"], ["PENDIENTE DE VERIFICACIÓN", "Pendiente de verificación"], ["PRIMERA CUOTA VERIFICADA", "Primera cuota verificada"], ["PAGO PARCIAL", "Pago parcial"], ["PAGO COMPLETO", "Pago completo"], ["RECHAZADO", "Rechazado"]]}/><Select valor={faltante} cambiar={setFaltante} opciones={[["TODOS", "Talla faltante: todas"], ["POLERA", "Polera"], ["CHAMARRA", "Chamarra"], ["AMBAS", "Ambas"]]}/><Select valor={bloque} cambiar={setBloque} opciones={[["TODOS", "Bloque: todos"], ...bloques.map((valor) => [valor, valor])]}/></div>
    <p className="font-bold text-[#74122A]">{filtradas.length} persona(s) encontradas</p>
    <div className="max-h-[32rem] overflow-auto"><table className="min-w-[2400px] w-full text-xs"><thead className="sticky top-0"><tr>{columnasSinTalla.map((titulo) => <th key={titulo} className="border bg-slate-100 p-2 text-left">{titulo}</th>)}</tr></thead><tbody>{filtradas.map((persona, indice) => <tr key={persona.usuarioId}>{filaSinTalla(persona, indice).map((valor, posicion) => <td key={columnasSinTalla[posicion]} className="border p-2">{posicion === 5 && persona.whatsapp ? <a href={`https://wa.me/${persona.whatsapp.replace("+", "")}`} target="_blank" rel="noreferrer" className="font-bold text-emerald-700 underline">{String(valor)}</a> : String(valor)}</td>)}</tr>)}</tbody></table></div>
  </section>;
}
function ResumenFaltantes({ titulo, personas }: { titulo: string; personas: PersonaTallaCuota[] }) { return <div className="rounded-xl border bg-white p-4"><h4 className="font-black text-[#74122A]">{titulo}</h4><div className="mt-2 grid grid-cols-2 gap-2 text-sm"><span>Sin polera: <b>{personas.filter((p) => !p.tienePolera).length}</b></span><span>Sin chamarra: <b>{personas.filter((p) => !p.tieneChamarra).length}</b></span><span>Sin ninguna: <b>{personas.filter((p) => p.pendienteTalla === "AMBAS").length}</b></span><span>Incompleta: <b>{personas.filter((p) => p.pendienteTalla !== "AMBAS").length}</b></span></div></div>; }
function ListadoEspecial({ titulo, personas, tipo }: { titulo: string; personas: PersonaTallaCuota[]; tipo: "CUOTA" | "MEDICION" | "POSTULANTE" }) {
  const hombres = personas.filter((p) => p.sexo === "HOMBRE").length, mujeres = personas.filter((p) => p.sexo === "MUJER").length;
  const incompletos = personas.filter((p) => p.pendienteTalla !== "AMBAS").length;
  return <div className="rounded-2xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-black text-[#74122A]">{titulo}</h3><p className="text-sm text-slate-600">Total: <b>{personas.length}</b> · Hombres: <b>{hombres}</b> · Mujeres: <b>{mujeres}</b>{tipo === "MEDICION" && <> · Medición incompleta: <b>{incompletos}</b></>}</p></div><button onClick={() => void exportarListado(titulo, personas, tipo)} className="rounded-xl bg-emerald-700 px-4 py-2 font-bold text-white">Exportar Excel</button></div><div className="mt-3 max-h-72 overflow-auto"><table className="w-full min-w-[1200px] text-xs"><thead><tr>{["Nombre", "CI", "Sexo", "Teléfono", "WhatsApp", "Roles", "Asignación", "Bloque", "Monto", "Registrado", "Verificado", "Saldo", "Estado", "Verificación", "Tallas"].map((c) => <th key={c} className="border bg-slate-100 p-2 text-left">{c}</th>)}</tr></thead><tbody>{personas.map((p) => <tr key={p.usuarioId}><td className="border p-2 font-bold">{p.nombre}</td><td className="border p-2">{p.ci}</td><td className="border p-2">{p.sexo}</td><td className="border p-2">{p.telefono}</td><td className="border p-2">{p.whatsapp ?? ""}</td><td className="border p-2">{p.roles.join(" / ")}</td><td className="border p-2">{p.asignacion}</td><td className="border p-2">{p.bloque}</td><td className="border p-2">Bs {p.montoPrimeraCuota.toFixed(2)}</td><td className="border p-2">Bs {p.montoRegistradoPrimeraCuota.toFixed(2)}</td><td className="border p-2">Bs {p.montoVerificadoPrimeraCuota.toFixed(2)}</td><td className="border p-2">Bs {p.saldoPrimeraCuota.toFixed(2)}</td><td className="border p-2">{p.estadoPago}</td><td className="border p-2">{p.verificacionPrimeraCuota}</td><td className="border p-2">{p.pendienteTalla === "AMBAS" ? "SIN MEDICIÓN" : p.pendienteTalla ? "INCOMPLETA" : "COMPLETA"}</td></tr>)}</tbody></table></div></div>;
}
function TarjetaListado({ titulo, descripcion, abierto, alternar, cargando, error, personas, tipo }: { titulo: string; descripcion: string; abierto: boolean; alternar: () => void; cargando: boolean; error?: string; personas: PersonaTallaCuota[]; tipo: "CUOTA" | "MEDICION" | "POSTULANTE" }) {
  return <section className="rounded-2xl border border-[#74122A]/20 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h2 className="text-xl font-black text-[#74122A]">{titulo}</h2><p className="text-sm text-slate-600">{descripcion}</p></div><button onClick={alternar} className="rounded-xl bg-[#74122A] px-5 py-3 font-black text-white">{abierto ? "OCULTAR REPORTE" : "VER REPORTE"}</button></div>{abierto && <div className="mt-5">{cargando ? <p>Cargando reporte…</p> : error ? <p className="text-red-700">{error}</p> : <ListadoEspecial titulo={titulo} personas={personas} tipo={tipo}/>}</div>}</section>;
}
