import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { obtenerReporteIntegrantesMatricula, type IntegranteMatricula } from "@/api/ReporteApi";

const encabezados=["Nº","Matrícula","Nombre completo","CI","Sexo","Teléfono","Facultad","Carrera","Número fraterno","Bloque","Guías hombres","Guías mujeres","Talla polera","Talla chamarra","Condición","Estado","Observaciones"];
const fila=(p:IntegranteMatricula,n:number)=>[n,p.matricula||"SIN MATRÍCULA",p.nombreCompleto,p.ci,p.sexo,p.telefono,p.facultad,p.carrera,p.numeroFraterno,p.bloque,p.guiasHombres,p.guiasMujeres,p.tallaPolera,p.tallaChamarra,p.condicion,p.estado,p.observaciones];
const limpiarNombre=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[\\/*?:[\]]/g," ").replace(/\s+/g," ").trim();
const nombreHoja=(v:string,usados:Set<string>)=>{const base=(limpiarNombre(v)||"BLOQUE").slice(0,31);let nombre=base,n=2;while(usados.has(nombre))nombre=`${base.slice(0,27)} ${n++}`;usados.add(nombre);return nombre};

export default function ReporteIntegrantesMatricula(){
 const q=useQuery({queryKey:["reporte-integrantes-matricula"],queryFn:obtenerReporteIntegrantesMatricula});
 const [bloque,setBloque]=useState("TODOS"),[sexo,setSexo]=useState("TODOS"),[generando,setGenerando]=useState(false);
 const exportar=async()=>{if(!q.data)return;setGenerando(true);try{
  const {default:ExcelJS}=await import("exceljs"),wb=new ExcelJS.Workbook();wb.creator="Fraternidad Tinkus Puros";wb.created=new Date();
  const personas=q.data.personas.filter(p=>(bloque==="TODOS"||p.bloqueId===bloque)&&(sexo==="TODOS"||p.sexo===sexo));
  const usados=new Set<string>();
  const estilizar=(ws:any,filaCabecera:number)=>{const cab=ws.getRow(filaCabecera);cab.font={bold:true,color:{argb:"FFFFFFFF"}};cab.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF74122A"}};cab.alignment={vertical:"middle"};cab.eachCell((c:any)=>{c.border={top:{style:"thin"},left:{style:"thin"},bottom:{style:"thin"},right:{style:"thin"}}});ws.views=[{state:"frozen",ySplit:filaCabecera}];ws.autoFilter={from:{row:filaCabecera,column:1},to:{row:filaCabecera,column:encabezados.length}};ws.columns.forEach((c:any,i:number)=>c.width=[7,18,38,15,12,16,28,25,18,20,30,30,15,17,16,14,35][i]);};
  const datos=(nombre:string,items:IntegranteMatricula[])=>{const ws=wb.addWorksheet(nombreHoja(nombre,usados));ws.addRow(encabezados);items.forEach((p,i)=>ws.addRow(fila(p,i+1)));estilizar(ws,1);return ws};
  const resumen=wb.addWorksheet(nombreHoja("RESUMEN",usados));resumen.addRow(["FRATERNIDAD TINKUS PUROS Y NATURALES"]);resumen.getRow(1).font={bold:true,size:16,color:{argb:"FF74122A"}};resumen.addRows([["Gestión",q.data.gestion?.anio??q.data.gestion?.nombre],["Generado",new Date().toLocaleString("es-BO")],["Total con bloque",personas.length],["Con matrícula",personas.filter(p=>p.matricula).length],["Sin matrícula",personas.filter(p=>!p.matricula).length],["Hombres",personas.filter(p=>p.sexo==="HOMBRE").length],["Mujeres",personas.filter(p=>p.sexo==="MUJER").length],["Bloques",new Set(personas.map(p=>p.bloqueId)).size],["Inconsistencias",personas.filter(p=>p.observaciones).length],[],["PERSONAS POR BLOQUE","TOTAL"]]);q.data.resumen.detalleBloques.filter(b=>bloque==="TODOS"||b._id===bloque).forEach(b=>resumen.addRow([b.nombre,personas.filter(p=>p.bloqueId===b._id).length]));resumen.columns=[{width:38},{width:22}];
  datos("TODOS",personas);datos("CON MATRICULA",personas.filter(p=>p.matricula));datos("SIN MATRICULA",personas.filter(p=>!p.matricula));
  q.data.resumen.detalleBloques.filter(b=>bloque==="TODOS"||b._id===bloque).forEach(b=>{const items=personas.filter(p=>p.bloqueId===b._id),ws=wb.addWorksheet(nombreHoja(b.nombre,usados));const muestra=items[0];ws.addRows([["BLOQUE",b.nombre],["GUÍAS HOMBRES",muestra?.guiasHombres||"SIN GUÍAS"],["GUÍAS MUJERES",muestra?.guiasMujeres||"SIN GUÍAS"],["HOMBRES",`${items.filter(p=>p.sexo==="HOMBRE").length} / 40`],["MUJERES",`${items.filter(p=>p.sexo==="MUJER").length} / 80`],["TOTAL",`${items.length} / 120`],[],encabezados]);items.forEach((p,i)=>ws.addRow(fila(p,i+1)));estilizar(ws,8)});
  const contenido=await wb.xlsx.writeBuffer(),url=URL.createObjectURL(new Blob([contenido],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"})),a=document.createElement("a"),fecha=new Date().toISOString().slice(0,10);a.href=url;a.download=bloque==="TODOS"?`TINKUS_INTEGRANTES_POR_MATRICULA_${fecha}.xlsx`:`TINKUS_BLOQUE_${limpiarNombre(q.data.resumen.detalleBloques.find(b=>b._id===bloque)?.nombre||"BLOQUE").replace(/\s+/g,"_").toUpperCase()}_${fecha}.xlsx`;a.click();URL.revokeObjectURL(url);
 }finally{setGenerando(false)}};
 return <section className="rounded-2xl border bg-white p-5 print:hidden"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><h2 className="text-xl font-black text-[#74122A]">Integrantes por matrícula</h2><p className="text-sm text-slate-600">Incluye únicamente asignaciones activas, separa personas sin matrícula y crea una hoja por bloque.</p>{q.data?<p className="mt-1 text-xs text-slate-500">{q.data.resumen.total} integrantes · {q.data.resumen.conMatricula} con matrícula · {q.data.resumen.sinMatricula} sin matrícula</p>:null}</div><div className="flex flex-wrap gap-2"><select value={bloque} onChange={e=>setBloque(e.target.value)} className="rounded-xl border p-2"><option value="TODOS">Todos los bloques</option>{q.data?.resumen.detalleBloques.map(b=><option key={b._id} value={b._id}>{b.nombre}</option>)}</select><select value={sexo} onChange={e=>setSexo(e.target.value)} className="rounded-xl border p-2"><option value="TODOS">Hombres y mujeres</option><option value="HOMBRE">Hombres</option><option value="MUJER">Mujeres</option></select><button disabled={!q.data||q.isLoading||generando} onClick={()=>void exportar()} className="rounded-xl bg-emerald-700 px-5 py-3 font-black text-white disabled:opacity-50">{generando?"GENERANDO...":"DESCARGAR EXCEL"}</button></div></div>{q.error?<p className="mt-3 text-sm text-red-700">{q.error.message}</p>:null}</section>;
}
