import { useQuery } from "@tanstack/react-query";
import { useRef, useState } from "react";
import { toast } from "react-toastify";
import { obtenerReporteEntregaRopa, type PersonaEntregaRopa } from "@/api/IndumentariaApi";

const opciones=["TODOS","ENTREGA COMPLETA","ENTREGA PARCIAL","SOLO POLERA","SOLO CHAMARRA","SIN ENTREGAS","FALTA POLERA","FALTA CHAMARRA"];
const filtrar=(p:PersonaEntregaRopa,f:string)=>{const po=p.polera.estado==="ENTREGADA",ch=p.chamarra.estado==="ENTREGADA";return f==="TODOS"||f===p.estadoGeneral.replaceAll("_"," ")||(f==="SOLO POLERA"&&po&&!ch)||(f==="SOLO CHAMARRA"&&ch&&!po)||(f==="SIN ENTREGAS"&&!po&&!ch)||(f==="FALTA POLERA"&&!po)||(f==="FALTA CHAMARRA"&&!ch);};
const encabezados=["Nº","Matrícula","Nombre completo","CI","Sexo","Teléfono","Bloque","Talla polera","Polera estado","Polera fecha","Talla chamarra","Chamarra estado","Chamarra fecha","Estado general","Plan","Pagos verificados","Estado cuota","Total pagado","Saldo","Observaciones"];
const fecha=(v:string|null)=>v?new Date(v).toLocaleString("es-BO"):"—";
const fila=(p:PersonaEntregaRopa,n:number)=>[n,p.matricula||"SIN MATRÍCULA",p.nombre,p.ci,p.sexo,p.telefono,p.bloque,p.tallaPolera||"SIN REGISTRO",p.polera.estado,fecha(p.polera.fecha),p.tallaChamarra||"SIN REGISTRO",p.chamarra.estado,fecha(p.chamarra.fecha),p.estadoGeneral,p.plan??"SIN PLAN",p.pagosVerificados,p.estadoCuota,p.montoPagado,p.saldo??"SIN CUOTA",p.observaciones];

export default function ReporteEntregaRopa(){
  const q=useQuery({queryKey:["reporte-entrega-ropa"],queryFn:obtenerReporteEntregaRopa});
  const [filtro,setFiltro]=useState("TODOS"),[bloque,setBloque]=useState("TODOS"),[sexo,setSexo]=useState("TODOS"),[ocupado,setOcupado]=useState(false),lock=useRef(false);
  const bloques=[...new Set(q.data?.personas.map(p=>p.bloque)??[])].sort();
  const exportar=async()=>{
    if(!q.data||lock.current)return;const items=q.data.personas.filter(p=>filtrar(p,filtro)&&(bloque==="TODOS"||p.bloque===bloque)&&(sexo==="TODOS"||p.sexo===sexo));
    if(!items.length){toast.info("No hay personas para los filtros seleccionados.");return;}lock.current=true;setOcupado(true);
    try{const {default:ExcelJS}=await import("exceljs"),wb=new ExcelJS.Workbook(),usados=new Set<string>();wb.creator="Tinkus Puros y Naturales";
      const hoja=(nombre:string)=>{let base=nombre.replace(/[\\/*?:[\]]/g," ").slice(0,31)||"BLOQUE",n=1,v=base;while(usados.has(v.toUpperCase()))v=`${base.slice(0,27)} ${++n}`;usados.add(v.toUpperCase());return wb.addWorksheet(v);};
      const tabla=(nombre:string,personas:PersonaEntregaRopa[])=>{const ws=hoja(nombre);ws.addRow(encabezados);personas.forEach((p,i)=>ws.addRow(fila(p,i+1)));ws.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};ws.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF74122A"}};ws.views=[{state:"frozen",ySplit:1}];ws.autoFilter="A1:T1";ws.columns.forEach((c,i)=>{c.width=[7,18,38,15,12,16,22,16,18,23,18,18,23,24,14,18,18,18,16,35][i];});return ws;};
      const r=hoja("RESUMEN");r.addRows([["CONTROL DE ENTREGA DE INDUMENTARIA"],["Gestión",q.data.gestion?.anio??"SIN GESTIÓN"],["Generado",new Date().toLocaleString("es-BO")],["Total personas",items.length],["Poleras entregadas",items.filter(p=>p.polera.estado==="ENTREGADA").length],["Poleras pendientes",items.filter(p=>p.polera.estado!=="ENTREGADA").length],["Chamarras entregadas",items.filter(p=>p.chamarra.estado==="ENTREGADA").length],["Chamarras pendientes",items.filter(p=>p.chamarra.estado!=="ENTREGADA").length],["Entrega completa",items.filter(p=>p.estadoGeneral==="ENTREGA_COMPLETA").length],["Entrega parcial",items.filter(p=>p.estadoGeneral==="ENTREGA_PARCIAL").length],["Sin entregas",items.filter(p=>p.estadoGeneral==="PENDIENTE").length]]);r.getRow(1).font={bold:true,size:16};r.columns=[{width:42},{width:24}];
      ["TODOS","ENTREGA COMPLETA","SOLO POLERA","SOLO CHAMARRA","SIN ENTREGAS","FALTA POLERA","FALTA CHAMARRA"].forEach(f=>tabla(f,items.filter(p=>filtrar(p,f))));
      for(const b of [...new Set(items.map(p=>p.bloque))]){const ps=items.filter(p=>p.bloque===b),ws=tabla(b,ps);ws.addRow([]);ws.addRows([["Total",ps.length],["Completos",ps.filter(p=>p.estadoGeneral==="ENTREGA_COMPLETA").length],["Falta polera",ps.filter(p=>p.polera.estado!=="ENTREGADA").length],["Falta chamarra",ps.filter(p=>p.chamarra.estado!=="ENTREGADA").length],["Sin entregas",ps.filter(p=>p.estadoGeneral==="PENDIENTE").length]]);}
      const buffer=await wb.xlsx.writeBuffer(),url=URL.createObjectURL(new Blob([buffer],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"})),a=document.createElement("a");a.href=url;a.download=`TINKUS_CONTROL_ENTREGA_INDUMENTARIA_${new Date().toISOString().slice(0,10)}.xlsx`;a.click();URL.revokeObjectURL(url);
    }catch(e){console.error("Exportación de entregas fallida",e);toast.error("No se pudo generar el Excel.");}finally{lock.current=false;setOcupado(false);}
  };
  return <section className="rounded-2xl border bg-white p-5 print:hidden"><h2 className="text-xl font-black text-[#74122A]">CONTROL DE ENTREGA DE INDUMENTARIA</h2><p className="text-sm text-slate-600">Polera y chamarra independientes. Fraternos activos de la gestión, incluso sin bloque.</p><div className="mt-3 flex flex-wrap gap-2"><select className="rounded-xl border p-2" value={filtro} onChange={e=>setFiltro(e.target.value)}>{opciones.map(f=><option key={f}>{f}</option>)}</select><select className="rounded-xl border p-2" value={bloque} onChange={e=>setBloque(e.target.value)}><option value="TODOS">Todos los bloques</option>{bloques.map(b=><option key={b}>{b}</option>)}</select><select className="rounded-xl border p-2" value={sexo} onChange={e=>setSexo(e.target.value)}><option value="TODOS">Hombres y mujeres</option><option>HOMBRE</option><option>MUJER</option></select><button disabled={!q.data||ocupado} onClick={()=>void exportar()} className="rounded-xl bg-emerald-700 px-5 py-2 font-black text-white disabled:opacity-50">{ocupado?"GENERANDO EXCEL...":"DESCARGAR EXCEL"}</button></div>{q.isError&&<p className="mt-2 text-red-700">No se pudo consultar el reporte.</p>}</section>;
}
