import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { toast } from "react-toastify";
import { obtenerReporteIntegrantesMatricula, type IntegranteMatricula, type ReporteIntegrantesMatricula } from "@/api/ReporteApi";

type FiltroPago = "TODOS"|"PAGO_COMPLETO"|"SOLO_PRIMER_PAGO"|"HASTA_SEGUNDO_PAGO"|"TRES_PAGOS_VERIFICADOS"|"SIN_PAGO"|"PENDIENTE"|"OBSERVADO"|"RECHAZADO";
const encabezados = ["Nº","Matrícula","Nombre completo","CI","Sexo","Teléfono","Facultad","Número fraterno","Bloque","Guías del bloque","Talla polera","Talla chamarra","Plan de pagos","Estado cuota","Pagos verificados","Total pagado verificado","Saldo pendiente","Primer pago - estado","Primer pago - monto","Primer pago - fecha","Primer pago - verificación","Primer pago - método","Segundo pago - estado","Segundo pago - monto","Segundo pago - fecha","Segundo pago - verificación","Segundo pago - método","Tercer pago - estado","Tercer pago - monto","Tercer pago - fecha","Tercer pago - verificación","Tercer pago - método","Fecha pago completo","Clasificación de pago","Pendientes","Observados","Rechazados","Observaciones"];
const fecha = (valor:string|null) => valor ? new Date(valor).toLocaleString("es-BO") : "—";
const fila = (p:IntegranteMatricula,n:number) => [n,p.matricula||"SIN MATRÍCULA",p.nombreCompleto,p.ci,p.sexo,p.telefono,p.facultad,p.numeroFraterno,p.bloque,[p.guiasHombres,p.guiasMujeres].filter(Boolean).join(" / ")||"SIN GUÍAS",p.tallaPolera||"SIN REGISTRO",p.tallaChamarra||"SIN REGISTRO",p.planPagos?`${p.planPagos} cuota(s)`:"SIN PLAN",p.estadoCuota,p.pagosVerificados,p.montoVerificado,p.saldo??"SIN CUOTA",p.primerPago.estado,p.primerPago.monto,fecha(p.primerPago.fechaPago),fecha(p.primerPago.fechaVerificacion),p.primerPago.metodo,p.segundoPago.estado,p.segundoPago.monto,fecha(p.segundoPago.fechaPago),fecha(p.segundoPago.fechaVerificacion),p.segundoPago.metodo,p.tercerPago.estado,p.tercerPago.monto,fecha(p.tercerPago.fechaPago),fecha(p.tercerPago.fechaVerificacion),p.tercerPago.metodo,fecha(p.fechaPagoCompleto),p.clasificacionPago,p.pendientes,p.observados,p.rechazados,p.observaciones];
const limpiarNombre = (v:string) => v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[\\/*?:[\]]/g," ").replace(/\s+/g," ").trim();
const nombreHoja = (v:string,usados:Set<string>) => { const base=(limpiarNombre(v)||"BLOQUE").slice(0,31);let nombre=base,n=2;while(usados.has(nombre))nombre=`${base.slice(0,27)} ${n++}`;usados.add(nombre);return nombre; };
const coincidePago = (p:IntegranteMatricula,filtro:FiltroPago) => filtro==="TODOS" || (filtro==="TRES_PAGOS_VERIFICADOS"&&p.pagosVerificados>=3) || (filtro==="SIN_PAGO"&&p.pagosVerificados===0) || (filtro==="PENDIENTE"&&p.pendientes>0) || (filtro==="OBSERVADO"&&p.observados>0) || (filtro==="RECHAZADO"&&p.rechazados>0) || p.clasificacionPago===filtro;

export default function ReporteIntegrantesMatricula(){
  const consulta=useQuery({queryKey:["reporte-integrantes-matricula"],queryFn:obtenerReporteIntegrantesMatricula,retry:1});
  const [bloque,setBloque]=useState("TODOS"),[sexo,setSexo]=useState("TODOS"),[pago,setPago]=useState<FiltroPago>("TODOS"),[generando,setGenerando]=useState(false);
  const personas=useMemo(()=>consulta.data?.personas.filter(p=>(bloque==="TODOS"||p.bloqueId===bloque)&&(sexo==="TODOS"||p.sexo===sexo)&&coincidePago(p,pago))??[],[consulta.data,bloque,sexo,pago]);
  const exportar=async()=>{if(!consulta.data||generando)return;if(!personas.length){toast.info("No se encontraron integrantes para los filtros seleccionados.");return;}setGenerando(true);try{await generarExcel(consulta.data,personas,bloque);toast.success("Excel generado correctamente.");}catch(error){console.error("Error al generar reporte de integrantes",error);toast.error("No se pudo generar el reporte. Intenta nuevamente.");}finally{setGenerando(false);}};
  return <section className="rounded-2xl border bg-white p-5 print:hidden"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><h2 className="text-xl font-black text-[#74122A]">Integrantes por matrícula y control de pagos</h2><p className="text-sm text-slate-600">Asignaciones activas, matrícula real y detalle de pagos verificados, pendientes, observados o rechazados.</p>{consulta.data&&<p className="mt-1 text-xs text-slate-500">{consulta.data.resumen.total} integrantes · {consulta.data.resumen.conMatricula} con matrícula · {consulta.data.resumen.sinMatricula} sin matrícula · {consulta.data.resumen.pagoCompleto} con pago completo</p>}{consulta.isError&&<p className="mt-2 text-sm font-semibold text-red-700">No se pudo cargar el reporte desde el servidor. Intenta nuevamente.</p>}</div><div className="flex flex-wrap gap-2"><select value={bloque} onChange={e=>setBloque(e.target.value)} className="rounded-xl border p-2"><option value="TODOS">Todos los bloques</option>{consulta.data?.resumen.detalleBloques.map(b=><option key={b._id} value={b._id}>{b.nombre}</option>)}</select><select value={sexo} onChange={e=>setSexo(e.target.value)} className="rounded-xl border p-2"><option value="TODOS">Hombres y mujeres</option><option value="HOMBRE">Hombres</option><option value="MUJER">Mujeres</option></select><select value={pago} onChange={e=>setPago(e.target.value as FiltroPago)} className="rounded-xl border p-2"><option value="TODOS">Todos los pagos</option><option value="PAGO_COMPLETO">Pago completo</option><option value="SOLO_PRIMER_PAGO">Solo primer pago</option><option value="HASTA_SEGUNDO_PAGO">Hasta segundo pago</option><option value="TRES_PAGOS_VERIFICADOS">Tres pagos</option><option value="SIN_PAGO">Sin pago verificado</option><option value="PENDIENTE">Pendientes de verificación</option><option value="OBSERVADO">Observados</option><option value="RECHAZADO">Rechazados</option></select><button disabled={!consulta.data||consulta.isLoading||generando} onClick={()=>void exportar()} className="rounded-xl bg-emerald-700 px-5 py-3 font-black text-white disabled:opacity-50">{generando?"GENERANDO EXCEL...":"DESCARGAR EXCEL"}</button></div></div></section>;
}

async function generarExcel(reporte:ReporteIntegrantesMatricula,personas:IntegranteMatricula[],bloqueSeleccionado:string){
  const {default:ExcelJS}=await import("exceljs");const wb=new ExcelJS.Workbook();wb.creator="Fraternidad Tinkus Puros";wb.created=new Date();const usados=new Set<string>();
  const estilizar=(ws:any,cabecera:number)=>{const row=ws.getRow(cabecera);row.font={bold:true,color:{argb:"FFFFFFFF"}};row.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF74122A"}};row.alignment={vertical:"middle"};row.eachCell((c:any)=>{c.border={top:{style:"thin"},left:{style:"thin"},bottom:{style:"thin"},right:{style:"thin"}}});ws.views=[{state:"frozen",ySplit:cabecera}];ws.autoFilter={from:{row:cabecera,column:1},to:{row:cabecera,column:encabezados.length}};ws.columns.forEach((c:any,i:number)=>c.width=[7,18,38,15,12,16,28,18,20,36,15,17,16,18,17,22,18,20,18,22,22,16,20,18,22,22,16,20,18,22,22,16,22,25,12,12,12,38][i]);};
  const agregarDatos=(nombre:string,items:IntegranteMatricula[],ordenFecha?: (p:IntegranteMatricula)=>string|null)=>{const ws=wb.addWorksheet(nombreHoja(nombre,usados));ws.addRow(encabezados);const ordenados=ordenFecha?[...items].sort((a,b)=>new Date(ordenFecha(a)??0).getTime()-new Date(ordenFecha(b)??0).getTime()):items;ordenados.forEach((p,i)=>ws.addRow(fila(p,i+1)));estilizar(ws,1);return ws;};
  const r=wb.addWorksheet(nombreHoja("RESUMEN",usados));r.addRows([["FRATERNIDAD TINKUS PUROS Y NATURALES"],["Gestión",reporte.gestion.anio??reporte.gestion.nombre],["Generado",new Date().toLocaleString("es-BO")],["Total con bloque",personas.length],["Con matrícula",personas.filter(p=>p.matricula).length],["Sin matrícula",personas.filter(p=>!p.matricula).length],["Hombres",personas.filter(p=>p.sexo==="HOMBRE").length],["Mujeres",personas.filter(p=>p.sexo==="MUJER").length],[],["CONTROL DE PAGOS","TOTAL"],["Pago completo",personas.filter(p=>p.clasificacionPago==="PAGO_COMPLETO").length],["Solo primer pago",personas.filter(p=>p.clasificacionPago==="SOLO_PRIMER_PAGO").length],["Hasta segundo pago",personas.filter(p=>p.clasificacionPago==="HASTA_SEGUNDO_PAGO").length],["Tres pagos verificados",personas.filter(p=>p.pagosVerificados>=3).length],["Sin pagos verificados",personas.filter(p=>p.pagosVerificados===0).length],["Pendientes de verificación",personas.filter(p=>p.pendientes>0).length],["Observados",personas.filter(p=>p.observados>0).length],["Rechazados",personas.filter(p=>p.rechazados>0).length],[],["POR BLOQUE","Integrantes","Pago completo","Primer pago","Segundo pago","Tres pagos","Sin pago","Pendientes"]]);reporte.resumen.detalleBloques.filter(b=>bloqueSeleccionado==="TODOS"||b._id===bloqueSeleccionado).forEach(b=>{const items=personas.filter(p=>p.bloqueId===b._id);r.addRow([b.nombre,items.length,items.filter(p=>p.clasificacionPago==="PAGO_COMPLETO").length,items.filter(p=>p.clasificacionPago==="SOLO_PRIMER_PAGO").length,items.filter(p=>p.clasificacionPago==="HASTA_SEGUNDO_PAGO").length,items.filter(p=>p.pagosVerificados>=3).length,items.filter(p=>p.pagosVerificados===0).length,items.filter(p=>p.pendientes>0).length]);});r.getRow(1).font={bold:true,size:16,color:{argb:"FF74122A"}};r.getRow(10).font={bold:true};r.getRow(20).font={bold:true};r.columns=[{width:35},{width:18},{width:18},{width:18},{width:18},{width:18},{width:18},{width:18}];
  agregarDatos("TODOS",personas);agregarDatos("CON MATRICULA",personas.filter(p=>p.matricula));agregarDatos("SIN MATRICULA",personas.filter(p=>!p.matricula));agregarDatos("PAGO COMPLETO",personas.filter(p=>p.clasificacionPago==="PAGO_COMPLETO"),p=>p.fechaPagoCompleto);agregarDatos("SOLO PRIMER PAGO",personas.filter(p=>p.clasificacionPago==="SOLO_PRIMER_PAGO"),p=>p.primerPago.fechaPago);agregarDatos("HASTA SEGUNDO PAGO",personas.filter(p=>p.clasificacionPago==="HASTA_SEGUNDO_PAGO"),p=>p.segundoPago.fechaPago);agregarDatos("TRES PAGOS VERIFICADOS",personas.filter(p=>p.pagosVerificados>=3),p=>p.tercerPago.fechaPago);agregarDatos("SIN PAGO",personas.filter(p=>p.pagosVerificados===0));agregarDatos("PENDIENTES VERIFICACION",personas.filter(p=>p.pendientes>0));agregarDatos("OBSERVADOS",personas.filter(p=>p.observados>0));agregarDatos("RECHAZADOS",personas.filter(p=>p.rechazados>0));
  reporte.resumen.detalleBloques.filter(b=>bloqueSeleccionado==="TODOS"||b._id===bloqueSeleccionado).forEach(b=>{const items=personas.filter(p=>p.bloqueId===b._id),ws=wb.addWorksheet(nombreHoja(b.nombre,usados)),muestra=items[0];ws.addRows([["BLOQUE",b.nombre],["GUÍAS",[muestra?.guiasHombres,muestra?.guiasMujeres].filter(Boolean).join(" / ")||"SIN GUÍAS"],["HOMBRES",`${items.filter(p=>p.sexo==="HOMBRE").length} / 40`],["MUJERES",`${items.filter(p=>p.sexo==="MUJER").length} / 80`],["TOTAL",`${items.length} / 120`],["PAGO COMPLETO",items.filter(p=>p.clasificacionPago==="PAGO_COMPLETO").length],["SOLO PRIMER PAGO",items.filter(p=>p.clasificacionPago==="SOLO_PRIMER_PAGO").length],["HASTA SEGUNDO",items.filter(p=>p.clasificacionPago==="HASTA_SEGUNDO_PAGO").length],["TRES PAGOS",items.filter(p=>p.pagosVerificados>=3).length],["SIN PAGO",items.filter(p=>p.pagosVerificados===0).length],["PENDIENTES",items.filter(p=>p.pendientes>0).length],[],encabezados]);items.forEach((p,i)=>ws.addRow(fila(p,i+1)));estilizar(ws,13);});
  const contenido=await wb.xlsx.writeBuffer(),url=URL.createObjectURL(new Blob([contenido],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"})),a=document.createElement("a"),hoy=new Date().toISOString().slice(0,10);a.href=url;a.download=bloqueSeleccionado==="TODOS"?`TINKUS_INTEGRANTES_CONTROL_${hoy}.xlsx`:`TINKUS_BLOQUE_${limpiarNombre(reporte.resumen.detalleBloques.find(b=>b._id===bloqueSeleccionado)?.nombre||"BLOQUE").replace(/\s+/g,"_").toUpperCase()}_${hoy}.xlsx`;a.click();URL.revokeObjectURL(url);
}
